// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 3478-3526
// (bundle section "// src/view/app.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { cls, h } from './vdom.js';
import { menuScreen, nameScreen } from './screens/menu.js';
import { lobbyScreen } from './screens/lobby.js';
import { gameScreen } from './screens/table.js';
import { ladderTab } from './screens/ladder.js';
import { spectatorScreen } from './screens/spectator.js';
import { rulesTab } from './screens/rules.js';
import { configScreen } from './screens/botConfig.js';

  var TABS = [
    { tab: "play", label: "Play", tip: "Lobby, seats and the table" },
    { tab: "ladder", label: "The Ladder", tip: "Every hand, strongest at the top" },
    { tab: "rules", label: "Rules", tip: "How to play Fidice" }
  ];
  var header = (ui, dispatch) => h(
    "header",
    {},
    h(
      "div",
      { class: "brand", id: "brandBtn", on: { click: () => dispatch({ type: "nav", tab: "play" }) } },
      h("span", { class: "cup" }, "\u{1F964}"),
      " Fidice ",
      ui.game && h("span", { class: "pill", id: "roomPill" }, ui.game.code)
    ),
    h("span", { class: "badge", tip: "House rules from the Crowe house on Kezar Lake" }, "Kezar Lake, Maine"),
    h("nav", { class: "tabs", id: "tabs" }, TABS.map((t) => h("button", { class: cls(ui.tab === t.tab && "active"), attrs: { "data-tab": t.tab }, tip: t.tip, on: { click: () => dispatch({ type: "nav", tab: t.tab }) } }, t.label)))
  );
  var playTab = (ui, dispatch) => {
    const g = ui.game;
    const body = (() => {
      switch (ui.screen) {
        case "menu":
          return menuScreen(ui, dispatch);
        case "name":
          return nameScreen(ui, dispatch);
        case "lobby":
          return g ? lobbyScreen(ui, g, dispatch) : menuScreen(ui, dispatch);
        case "game":
          return g ? gameScreen(ui, g, dispatch) : menuScreen(ui, dispatch);
        case "spec":
          return g ? spectatorScreen(ui, g, dispatch) : menuScreen(ui, dispatch);
      }
    })();
    return h("section", { id: "tab-play" }, ui.configTarget ? configScreen(ui, ui.configTarget, dispatch) : body);
  };
  var appView = (ui, dispatch) => h(
    "div",
    { class: "app", id: "app-root" },
    header(ui, dispatch),
    h(
      "main",
      {},
      ui.tab === "play" && playTab(ui, dispatch),
      ui.tab === "ladder" && ladderTab(ui, dispatch),
      ui.tab === "rules" && rulesTab()
    ),
    h("div", { class: cls("toast", ui.toast && "show"), id: "toast" }, ui.toast ?? "")
  );

export { TABS, header, playTab, appView };
