// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 2428-2538
// (bundle section "// src/view/components.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { isOut, keepsScore } from '../domain/game.ts';
import { describeProfile, strategyFor } from '../bots/registry.ts';
import { cls, h } from './vdom.js';

  var die = (value, o = {}) => h("div", {
    class: cls("die", o.size, value === null ? "hidden-face" : `v${value}`, o.clickable && "clickable", o.selected && "selected"),
    attrs: { role: "img", "aria-label": value === null ? "hidden die" : `die showing ${value}` },
    ...o.tip ? { tip: o.tip } : {},
    ...o.onClick ? { on: { click: o.onClick } } : {}
  });
  var diceRow = (values, size = "") => h("div", { class: "dice" }, values.map((v) => die(v, { size })));
  var SHAPE_GLYPH = { pine: "\u{1F332}", kayak: "\u{1F6F6}", blank: "", step1: "", step2: "", step3: "", step4: "", step5: "" };
  var SHAPE_LABEL = {
    pine: "a die of the main number",
    kayak: "a die of the second number",
    blank: "any other die",
    step1: "lowest die of a run",
    step2: "second die of a run",
    step3: "middle die of a run",
    step4: "fourth die of a run",
    step5: "highest die of a run"
  };
  var CATEGORY_SHAPE = {
    five: ["pine", "pine", "pine", "pine", "pine"],
    quads: ["pine", "pine", "pine", "pine", "blank"],
    fullhouse: ["pine", "pine", "pine", "kayak", "kayak"],
    straight: ["step1", "step2", "step3", "step4", "step5"],
    trips: ["pine", "pine", "pine", "blank", "blank"],
    twopair: ["pine", "pine", "kayak", "kayak", "blank"],
    pair: ["pine", "pine", "blank", "blank", "blank"],
    high: ["pine", "blank", "blank", "blank", "blank"]
  };
  var shapeDie = (sym, size = "sm") => h("div", { class: cls("die", size, "abs", `abs-${sym}`), attrs: { role: "img", "aria-label": SHAPE_LABEL[sym] } }, SHAPE_GLYPH[sym]);
  var shapeRow = (cat, size = "sm") => h("div", { class: "dice shape" }, CATEGORY_SHAPE[cat].map((sym) => shapeDie(sym, size)));
  var kayak = (lost) => h("span", { style: lost ? "opacity:.28;filter:grayscale(1)" : void 0 }, "\u{1F6F6}");
  var kayaks = (lives, max) => h(
    "div",
    { class: "lives", tip: "Kayaks left \u2014 lose one each time a call goes against you" },
    Array.from({ length: Math.max(0, max) }, (_, i2) => kayak(i2 >= lives))
  );
  var lostPill = (losses) => h("div", { class: cls("lost", losses === 0 && "clean"), tip: "Rounds lost \u2014 the score at this table. Fewest wins." }, losses === 0 ? "no rounds lost" : `${losses} lost`);
  var seatStatus = (game, i2, p2) => {
    const r = game.round;
    if (game.phase === "lobby") return p2.bot ? `Computer \xB7 ${describeProfile(p2.bot)}` : "Ready";
    if (isOut(game, p2)) return "Out";
    const holding2 = r && r.holder === i2 && !game.reveal;
    if (holding2) return r.bid === null ? "Opening the round" : r.touched ? "Shuffling\u2026" : "Deciding\u2026";
    return r && r.bidder === i2 && !game.reveal ? "Bid on the table" : "";
  };
  var seatCard = (game, i2, p2, o) => {
    const r = game.round;
    const holding2 = !!r && r.holder === i2 && !game.reveal && game.phase === "playing";
    return h(
      "div",
      {
        class: cls("seat", i2 === o.mySeat && "me", holding2 && "holder", isOut(game, p2) && game.phase !== "lobby" && "out"),
        attrs: { "data-seat": String(i2) }
      },
      h(
        "div",
        { class: "nm" },
        h("span", { class: cls("dot", !p2.connected && "off"), tip: p2.connected ? "Connected" : "Disconnected" }),
        p2.name,
        i2 === game.hostSeat && h("span", { class: "small muted", tip: "Runs the table" }, " \u{1F451}"),
        p2.bot && h("span", { class: "small", tip: `Computer player (${describeProfile(p2.bot)})` }, " \u{1F916}"),
        i2 === o.mySeat && h("span", { class: "small muted" }, " (you)")
      ),
      game.phase !== "lobby" && (keepsScore(game) ? lostPill(p2.losses) : kayaks(p2.lives, game.lives)),
      p2.bot && game.phase === "lobby" && o.canRemoveBots ? botControls(i2, p2.name, p2.bot, o.dispatch) : h("div", { class: "status" }, seatStatus(game, i2, p2)),
      holding2 && h("span", { class: "cupbadge" }, "\u{1F964}"),
      p2.bot && game.phase === "lobby" && o.canRemoveBots && h("button", { class: "btn-ghost small remove-bot", style: "padding:2px 6px;font-size:11px;align-self:flex-start", on: { click: () => o.dispatch({ type: "lobby.removeBot", seat: i2 }) } }, "\u2715 remove")
    );
  };
  var botControls = (i2, name, bot, dispatch) => h(
    "div",
    { class: "bot-controls" },
    h("input", {
      id: `botName-${i2}`,
      class: "bot-name",
      tip: "Rename this computer (blank = a lake name)",
      attrs: { maxlength: "16", placeholder: "Name" },
      props: { value: name },
      on: {
        change: (e) => dispatch({ type: "lobby.renameBot", seat: i2, name: e.target.value }),
        keydown: (e) => {
          if (e.key === "Enter") e.target.blur();
        }
      }
    }),
    h(
      "div",
      { class: "row", style: "gap:6px;align-items:center" },
      h("span", { class: "bot-strategy", id: `botStrategy-${i2}`, tip: strategyFor(bot).blurb }, bot.random ? `\u{1F3B2} ${strategyFor(bot).name}` : strategyFor(bot).name),
      h("span", { class: "spacer" }),
      h("button", { class: "btn-ghost small", id: `btnConfig-${i2}`, style: "padding:2px 8px;font-size:12px", tip: "Choose its strategy \u2014 or the self-taught computer", on: { click: () => dispatch({ type: "config.open", target: { kind: "seat", seat: i2 } }) } }, "\u2699 Configure")
    ),
    h("div", { class: "small muted", style: "font-size:11.5px;line-height:1.3" }, bot.random ? `Drawn at random. ${strategyFor(bot).blurb}` : strategyFor(bot).blurb)
  );
  var seats = (game, o, fillEmpty) => h(
    "div",
    { class: "seats" },
    game.players.map((p2, i2) => seatCard(game, i2, p2, o)),
    fillEmpty && Array.from({ length: Math.max(0, 6 - game.players.length) }, (_, k) => h("div", { class: "seat empty-seat" }, game.players.length + k < 2 ? "Waiting for a player\u2026" : "Open seat"))
  );
  var clockTime = (at) => at === null ? "" : new Date(at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" });
  var logView = (entries, id = "log") => h("div", { class: "log", id }, entries.map((e) => h("div", { class: cls(e.big && "big") }, h("span", { class: "t" }, clockTime(e.at)), e.text)));
  var stepHeader = (n, title2, blurb) => [
    h("h4", {}, h("span", { class: "num" }, String(n)), title2),
    h("p", {}, blurb)
  ];
  var seatOptions = (ui, dispatch) => ({
    mySeat: ui.mySeat,
    canRemoveBots: ui.role === "host",
    dispatch
  });

export {
  die, diceRow, SHAPE_GLYPH, SHAPE_LABEL, CATEGORY_SHAPE, shapeDie, shapeRow, kayak,
  kayaks, lostPill, seatStatus, seatCard, botControls, seats, clockTime, logView,
  stepHeader, seatOptions,
};
