// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 2685-2718
// (bundle section "// src/view/ui.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

  var emptyLadder = { open: /* @__PURE__ */ new Set(), closed: /* @__PURE__ */ new Set(), allOpen: false };
  var emptyPicker = { query: "", selected: null, highlight: 0, listOpen: false };
  var initialUi = (shareBase, savedName) => ({
    screen: "menu",
    tab: "play",
    role: null,
    mySeat: null,
    game: null,
    pending: null,
    nameForm: { name: savedName, lives: 0, botChoice: "profiler", locals: [""] },
    configTarget: null,
    joinCode: "",
    localTable: false,
    handoff: null,
    shownSeat: null,
    busy: null,
    error: null,
    toast: null,
    ladders: { main: emptyLadder, spec: emptyLadder },
    picker: emptyPicker,
    rollSelection: /* @__PURE__ */ new Set(),
    rollCup: false,
    rollHidden: false,
    showTruth: false,
    shareBase,
    now: 0
  });
  var isMyTurn = (ui) => {
    const r = ui.game?.round;
    return !!r && ui.game?.phase === "playing" && !ui.game.reveal && ui.mySeat !== null && r.holder === ui.mySeat;
  };
  var isHostUi = (ui) => ui.role === "host";
  var playerLink = (ui, code) => `${ui.shareBase}#join=${code}`;
  var spectatorLink = (ui, code) => `${ui.shareBase}#watch=${code}`;

export { emptyLadder, emptyPicker, initialUi, isMyTurn, isHostUi, playerLink, spectatorLink };
