// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 2340-2425
// (bundle section "// src/view/vdom.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

  var flatten = (children) => children.flatMap((c) => {
    if (c === null || c === void 0 || c === false) return [];
    if (typeof c === "string" || typeof c === "number") return [{ kind: "text", text: String(c) }];
    if (Array.isArray(c)) return flatten(c);
    return [c];
  });
  var h = (tag, props = {}, ...children) => ({
    kind: "element",
    tag,
    props,
    children: flatten(children)
  });
  var RENDERED = /* @__PURE__ */ new WeakMap();
  var setProps = (doc, el, prev, next, listeners) => {
    if (prev.class !== next.class) next.class ? el.setAttribute("class", next.class) : el.removeAttribute("class");
    if (prev.id !== next.id) next.id ? el.setAttribute("id", next.id) : el.removeAttribute("id");
    if (prev.style !== next.style) next.style ? el.setAttribute("style", next.style) : el.removeAttribute("style");
    if (prev.tip !== next.tip) next.tip ? el.setAttribute("data-tip", next.tip) : el.removeAttribute("data-tip");
    const attrNames = /* @__PURE__ */ new Set([...Object.keys(prev.attrs ?? {}), ...Object.keys(next.attrs ?? {})]);
    attrNames.forEach((name) => {
      const v = next.attrs?.[name];
      if (v === prev.attrs?.[name]) return;
      v === void 0 ? el.removeAttribute(name) : el.setAttribute(name, v);
    });
    const propNames = /* @__PURE__ */ new Set([...Object.keys(prev.props ?? {}), ...Object.keys(next.props ?? {})]);
    propNames.forEach((name) => {
      const v = next.props?.[name];
      const target = el;
      if (v === void 0) {
        if (name in target) target[name] = typeof prev.props?.[name] === "boolean" ? false : "";
        return;
      }
      if (target[name] !== v) target[name] = v;
    });
    const eventNames = /* @__PURE__ */ new Set([...Object.keys(prev.on ?? {}), ...Object.keys(next.on ?? {})]);
    return [...eventNames].reduce((acc, name) => {
      const fn = next.on?.[name];
      const old = listeners[name];
      if (old) el.removeEventListener(name, old);
      if (fn) el.addEventListener(name, fn);
      return fn ? { ...acc, [name]: fn } : acc;
    }, {});
  };
  var create = (doc, v) => {
    if (v.kind === "text") {
      const n = doc.createTextNode(v.text);
      RENDERED.set(n, { vnode: v, listeners: {} });
      return n;
    }
    const el = doc.createElement(v.tag);
    const listeners = setProps(doc, el, {}, v.props, {});
    v.children.forEach((c) => el.appendChild(create(doc, c)));
    RENDERED.set(el, { vnode: v, listeners });
    return el;
  };
  var sameKind = (a, b2) => a.kind === b2.kind && (a.kind === "text" || a.tag === b2.tag && a.props.key === b2.props.key);
  var reconcile = (doc, node, next) => {
    const record = RENDERED.get(node);
    if (!record || !sameKind(record.vnode, next)) {
      const fresh = create(doc, next);
      node.parentNode?.insertBefore(fresh, node);
      node.parentNode?.removeChild(node);
      return fresh;
    }
    if (next.kind === "text") {
      if (record.vnode.text !== next.text) node.textContent = next.text;
      RENDERED.set(node, { vnode: next, listeners: {} });
      return node;
    }
    const el = node;
    const listeners = setProps(doc, el, record.vnode.props, next.props, record.listeners);
    patchChildren(doc, el, next.children);
    RENDERED.set(node, { vnode: next, listeners });
    return node;
  };
  var patchChildren = (doc, parent, children) => {
    const existing = Array.from(parent.childNodes);
    children.forEach((child, i2) => {
      const current = existing[i2];
      if (current) reconcile(doc, current, child);
      else parent.appendChild(create(doc, child));
    });
    existing.slice(children.length).forEach((extra) => parent.removeChild(extra));
  };
  var mount = (doc, root, tree) => patchChildren(doc, root, [tree]);
  var cls = (...parts) => parts.filter(Boolean).join(" ");

export { flatten, h, RENDERED, setProps, create, sameKind, reconcile, patchChildren, mount, cls };
