// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 384-391
// (bundle section "// src/domain/dice.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

  var DIE_VALUES = [1, 2, 3, 4, 5, 6];
  var rollDie = (rng) => {
    const index = Math.min(5, Math.floor(rng() * 6));
    return DIE_VALUES[index] ?? 6;
  };
  var rollDice = (count, rng) => Array.from({ length: count }, () => rollDie(rng));
  var sortDesc = (dice) => [...dice].sort((a, b2) => b2 - a);
  var faceCounts = (dice) => dice.reduce((m, v) => m.set(v, (m.get(v) ?? 0) + 1), /* @__PURE__ */ new Map());

export { DIE_VALUES, rollDie, rollDice, sortDesc, faceCounts };
