// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 666-859
// (bundle section "// src/domain/game.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { rollDice } from './dice.js';
import { handAt, rankOf, spokenName } from './hands.js';
import { err, ok } from './result.js';

  var seat = (n) => n;
  var bySeat = (s) => ({ kind: "seat", seat: s });
  var HOST = { kind: "host" };
  var MAX_SEATS = 6;
  var MIN_PLAYERS = 2;
  var LOG_LIMIT = 80;
  var RECORD_LIMIT = 60;
  var newGame = (code, lives) => ({
    code,
    lives,
    phase: "lobby",
    players: [],
    spectators: 0,
    roundNo: 0,
    round: null,
    reveal: null,
    winner: null,
    log: [],
    records: [],
    hostSeat: seat(0),
    autoNextAt: null
  });
  var withLog = (s, text, big = false) => ({
    ...s,
    log: [...s.log, { text, big, at: null }].slice(-LOG_LIMIT)
  });
  var stampLog = (s, now) => s.log.some((e) => e.at === null) ? { ...s, log: s.log.map((e) => e.at === null ? { ...e, at: now } : e) } : s;
  var playerAt = (s, i2) => s.players[i2];
  var nameOf = (s, i2) => playerAt(s, i2)?.name ?? "?";
  var keepsScore = (s) => s.lives === 0;
  var isOut = (s, p2) => !keepsScore(s) && p2.lives <= 0;
  var alivePlayers = (s) => s.players.filter((p2) => !isOut(s, p2));
  var isAlive = (s, i2) => {
    const p2 = playerAt(s, i2);
    return p2 !== void 0 && !isOut(s, p2);
  };
  var standings = (s) => s.players.map((p2, i2) => ({ p: p2, i: seat(i2) })).sort((a, b2) => a.p.losses - b2.p.losses || b2.p.lives - a.p.lives || a.i - b2.i).map((x) => x.i);
  var nextAlive = (s, from) => {
    const n = s.players.length;
    const found = Array.from({ length: n - 1 }, (_, k) => seat((from + k + 1) % n)).find((i2) => isAlive(s, i2));
    return found ?? from;
  };
  var cupIndices = (r) => r.dice.flatMap((d, i2) => d.inCup ? [i2] : []);
  var tableIndices = (r) => r.dice.flatMap((d, i2) => d.inCup ? [] : [i2]);
  var diceValues = (r) => r.dice.map((d) => d.value);
  var realRank = (r) => rankOf(diceValues(r));
  var holderMaySee = (r) => r.bid === null || r.touched;
  var isHostActor = (s, a) => a.kind === "host" || s.hostSeat !== null && a.seat === s.hostSeat;
  var startRound = (s, starter, rng) => withLog(
    {
      ...s,
      roundNo: s.roundNo + 1,
      reveal: null,
      autoNextAt: null,
      round: {
        holder: starter,
        bid: null,
        bidder: null,
        rolled: false,
        touched: false,
        history: [],
        dice: rollDice(5, rng).map((value) => ({ value, inCup: true }))
      }
    },
    `Round ${s.roundNo + 1}: ${nameOf(s, starter)} shakes the cup.`,
    true
  );
  var startGame = (s, rng) => {
    if (s.phase !== "lobby") return err("The game has already started.");
    if (s.players.length < MIN_PLAYERS) return err(`Need at least ${MIN_PLAYERS} players.`);
    const ready = withLog(
      { ...s, phase: "playing", players: s.players.map((p2) => ({ ...p2, lives: s.lives, losses: 0 })) },
      keepsScore(s) ? `Game on! ${s.players.length} players, keeping score.` : `Game on! ${s.players.length} players, ${s.lives} lives each.`,
      true
    );
    return ok(startRound(ready, seat(0), rng));
  };
  var nextRound = (s, rng) => {
    if (!s.reveal) return err("No round to advance.");
    const loser = s.reveal.loser;
    return ok(startRound(s, isAlive(s, loser) ? loser : nextAlive(s, loser), rng));
  };
  var updateRound = (s, r) => ({ ...s, round: r });
  var peek = (s, r, me) => r.touched ? err("You already accepted the cup.") : ok(withLog(updateRound(s, { ...r, touched: true }), `${me.name} accepts the cup and peeks.`));
  var pull = (s, r, me, index) => {
    if (!holderMaySee(r)) return err("Peek first.");
    const die2 = r.dice[index];
    if (!die2) return err("No such die.");
    if (!die2.inCup) return err("That die is already out.");
    const dice = r.dice.map((d, i2) => i2 === index ? { ...d, inCup: false } : d);
    return ok(withLog(updateRound(s, { ...r, dice, touched: true }), `${me.name} pulls a ${die2.value} out from under the cup.`));
  };
  var countDice = (n) => `${n} ${n === 1 ? "die" : "dice"}`;
  var roll = (s, r, me, cup, table, intoCup, rng) => {
    if (r.rolled) return err("You already rolled this turn.");
    if (!holderMaySee(r)) return err("Peek first.");
    const onTable = new Set(tableIndices(r));
    const tucked = new Set(intoCup.filter((i2) => onTable.has(i2)));
    const chosen = table.filter((i2) => onTable.has(i2) && !tucked.has(i2));
    const cupIdx = cupIndices(r);
    if (!cup && chosen.length === 0 && tucked.size === 0) return err("Pick something to roll.");
    if (cup && cupIdx.length === 0 && tucked.size === 0) return err("Nothing left under the cup.");
    const shakeCup = cup || tucked.size > 0;
    const rerolled = /* @__PURE__ */ new Set([...chosen, ...tucked, ...shakeCup ? cupIdx : []]);
    const dice = r.dice.map((d, i2) => rerolled.has(i2) ? { ...d, value: rollDice(1, rng)[0] ?? d.value, inCup: d.inCup || tucked.has(i2) } : d);
    const parts = [
      chosen.length ? `rolls ${countDice(chosen.length)} on the table \u2192 ${chosen.map((i2) => dice[i2]?.value).join(", ")}` : null,
      tucked.size ? `tucks ${countDice(tucked.size)} back under the cup` : null,
      shakeCup ? `shakes the cup (${countDice(cupIdx.length + tucked.size)})` : null
    ];
    const text = `${me.name} ${parts.filter((x) => x !== null).join(", ")}.`;
    return ok(withLog(updateRound(s, { ...r, dice, rolled: true, touched: true }), text));
  };
  var bid = (s, r, me, mySeat, rank) => {
    if (r.bid !== null && !r.touched) return err("Accept the cup before bidding.");
    if (r.bid !== null && rank <= r.bid) return err("Your bid must be higher than the current bid.");
    const next = {
      ...r,
      bid: rank,
      bidder: mySeat,
      history: [...r.history, { seat: mySeat, rank }],
      holder: nextAlive(s, mySeat),
      rolled: false,
      touched: false
    };
    return ok(withLog(updateRound(s, next), `${me.name} bids ${spokenName(rank)}.`, true));
  };
  var call = (s, r, me, mySeat) => {
    if (r.bid === null || r.bidder === null) return err("There is no bid to call.");
    if (r.touched) return err("You accepted the cup \u2014 you must bid.");
    const real = realRank(r);
    const holds = real >= r.bid;
    const loser = holds ? mySeat : r.bidder;
    const scoring = keepsScore(s);
    const players = s.players.map((p2, i2) => i2 === loser ? { ...p2, lives: scoring ? p2.lives : p2.lives - 1, losses: p2.losses + 1 } : p2);
    const reveal = { dice: diceValues(r), real, bid: r.bid, holds, caller: mySeat, bidder: r.bidder, loser };
    const record = { roundNo: s.roundNo, bids: r.history, bidder: r.bidder, caller: mySeat, bid: r.bid, real, holds, loser };
    const cost = scoring ? `loses the round (${players[loser]?.losses ?? 0} lost)` : "loses a life";
    const revealed = withLog(
      { ...s, players, reveal, records: [...s.records, record].slice(-RECORD_LIMIT) },
      `${me.name} calls liar! Under the cup: ${handAt(real).name}. ${holds ? "The bid holds" : "Busted"} \u2014 ${nameOf(s, loser)} ${cost}.`,
      true
    );
    if (scoring) return ok(revealed);
    const loserOut = (players[loser]?.lives ?? 0) === 0;
    const afterOut = loserOut ? withLog(revealed, `${nameOf(s, loser)} is out of lives.`, true) : revealed;
    const remaining = alivePlayers(afterOut);
    if (remaining.length > 1) return ok(afterOut);
    const champion = remaining[0];
    const winner = champion ? seat(afterOut.players.indexOf(champion)) : null;
    return ok(withLog({ ...afterOut, phase: "over", winner }, champion ? `\u{1F3C6} ${champion.name} wins \u2014 last kayak on the lake!` : "Everyone fell in?!", true));
  };
  var finish = (s, actor) => {
    if (!isHostActor(s, actor)) return err("Only the host can end the game.");
    const order = standings(s);
    const top = order[0];
    const runnerUp = order[1];
    const tied = top !== void 0 && runnerUp !== void 0 && (playerAt(s, top)?.losses ?? 0) === (playerAt(s, runnerUp)?.losses ?? 0);
    const winner = top !== void 0 && !tied ? top : null;
    const board = order.map((i2) => `${nameOf(s, i2)} ${playerAt(s, i2)?.losses ?? 0}`).join(", ");
    return ok(withLog({ ...s, phase: "over", winner }, `\u{1F3C1} The host ends the game. Rounds lost \u2014 ${board}.${winner === null ? " A tie at the top!" : ` ${nameOf(s, winner)} wins.`}`, true));
  };
  var apply = (s, actor, action, rng) => {
    if (s.phase === "lobby") {
      if (action.type !== "start") return err("The game has not started.");
      return isHostActor(s, actor) ? startGame(s, rng) : err("Only the host can start.");
    }
    if (s.phase === "over") return err("The game is over.");
    if (action.type === "finish") return finish(s, actor);
    const r = s.round;
    if (!r) return err("No round in progress.");
    if (s.reveal) return action.type === "next" ? nextRound(s, rng) : err("Waiting for the next round.");
    if (actor.kind !== "seat") return err("Only a seated player can play.");
    if (actor.seat !== r.holder) return err("It's not your turn.");
    const me = playerAt(s, actor.seat);
    if (!me) return err("No such seat.");
    switch (action.type) {
      case "peek":
        return peek(s, r, me);
      case "pull":
        return pull(s, r, me, action.die);
      case "roll":
        return roll(s, r, me, action.cup, action.table, action.intoCup, rng);
      case "bid":
        return bid(s, r, me, actor.seat, action.rank);
      case "call":
        return call(s, r, me, actor.seat);
      case "start":
      case "next":
      case "finish":
        return err("Not now.");
    }
  };
  var scheduleAutoNext = (s, at) => ({ ...s, autoNextAt: at });

export {
  seat, bySeat, HOST, MAX_SEATS, MIN_PLAYERS, LOG_LIMIT, RECORD_LIMIT, newGame,
  withLog, stampLog, playerAt, nameOf, keepsScore, isOut, alivePlayers, isAlive,
  standings, nextAlive, cupIndices, tableIndices, diceValues, realRank, holderMaySee, isHostActor,
  startRound, startGame, nextRound, updateRound, peek, pull, countDice, roll,
  bid, call, finish, apply, scheduleAutoNext,
};
