// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 394-548
// (bundle section "// src/domain/hands.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { DIE_VALUES, faceCounts, sortDesc } from './dice.js';

  var CATEGORIES = ["high", "pair", "twopair", "trips", "straight", "fullhouse", "quads", "five"];
  var CATEGORIES_STRONGEST_FIRST = [...CATEGORIES].reverse();
  var CATEGORY_LABEL = {
    five: "Five of a kind",
    quads: "Four of a kind",
    fullhouse: "Full house",
    straight: "Straight",
    trips: "Three of a kind",
    twopair: "Two pair",
    pair: "One pair",
    high: "High die"
  };
  var CATEGORY_BLURB = {
    five: "All five dice show the same number. The best you can do.",
    quads: "Four dice match; the fifth die is the kicker.",
    fullhouse: "Three of one number plus a pair of another.",
    straight: "Five in a row: 2-3-4-5-6 beats 1-2-3-4-5.",
    trips: "Three dice match; the other two are kickers.",
    twopair: "Two different pairs; the odd die is the kicker.",
    pair: "One pair; the other three dice are kickers.",
    high: "Nothing matches and no straight. Only the die values count."
  };
  var HAND_COUNT = 252;
  var TOP_RANK = HAND_COUNT - 1;
  var BOTTOM_RANK = 0;
  var isRank = (n) => typeof n === "number" && Number.isInteger(n) && n >= 0 && n < HAND_COUNT;
  var asRank = (n) => {
    if (!isRank(n)) throw new RangeError(`Not a rank: ${n}`);
    return n;
  };
  var rungOf = (rank) => rank + 1;
  var plural = (v) => `${v}s`;
  var describeKickers = (k) => k.length === 1 ? `a ${k[0]}` : k.join(", ");
  var valuesWithCount = (counts, n) => [...DIE_VALUES].reverse().filter((v) => counts.get(v) === n);
  var classify = (dice) => {
    const counts = faceCounts(dice);
    const sorted = sortDesc(dice);
    const of = (n) => valuesWithCount(counts, n);
    const [five] = of(5);
    const [four] = of(4);
    const [three] = of(3);
    const pairs = of(2);
    const singles = of(1);
    if (five) return { cat: "five", primary: five, secondary: 0, kickers: [] };
    if (four) return { cat: "quads", primary: four, secondary: 0, kickers: singles };
    if (three && pairs[0]) return { cat: "fullhouse", primary: three, secondary: pairs[0], kickers: [] };
    if (three) return { cat: "trips", primary: three, secondary: 0, kickers: singles };
    if (pairs.length === 2 && pairs[0] && pairs[1]) return { cat: "twopair", primary: pairs[0], secondary: pairs[1], kickers: singles };
    if (pairs[0]) return { cat: "pair", primary: pairs[0], secondary: 0, kickers: singles };
    const joined = sorted.join("");
    const top = sorted[0] ?? 6;
    if (joined === "65432" || joined === "54321") return { cat: "straight", primary: top, secondary: 0, kickers: [] };
    return { cat: "high", primary: top, secondary: 0, kickers: sorted.slice(1) };
  };
  var compareShapes = (a, b2) => {
    const byCategory = CATEGORIES.indexOf(a.cat) - CATEGORIES.indexOf(b2.cat);
    if (byCategory !== 0) return byCategory;
    if (a.primary !== b2.primary) return a.primary - b2.primary;
    if (a.secondary !== b2.secondary) return a.secondary - b2.secondary;
    const width = Math.max(a.kickers.length, b2.kickers.length);
    return Array.from({ length: width }, (_, i2) => (a.kickers[i2] ?? 0) - (b2.kickers[i2] ?? 0)).find((d) => d !== 0) ?? 0;
  };
  var groupNameOf = (h2) => {
    switch (h2.cat) {
      case "five":
        return `Five ${plural(h2.primary)}`;
      case "quads":
        return `Four ${plural(h2.primary)}`;
      case "fullhouse":
        return `${plural(h2.primary)} full`;
      case "straight":
        return h2.primary === 6 ? "Straight 2\u20136" : "Straight 1\u20135";
      case "trips":
        return `Three ${plural(h2.primary)}`;
      case "twopair":
        return `${plural(h2.primary)} and ${plural(h2.secondary)}`;
      case "pair":
        return `Pair of ${plural(h2.primary)}`;
      case "high":
        return `High die ${h2.primary}`;
    }
  };
  var handNameOf = (h2) => {
    if (h2.cat === "fullhouse") return `${plural(h2.primary)} full of ${plural(h2.secondary)}`;
    if (h2.kickers.length === 0) return groupNameOf(h2);
    if (h2.cat === "high") return `${groupNameOf(h2)} (${[h2.primary, ...h2.kickers].join("-")})`;
    return `${groupNameOf(h2)} with ${describeKickers(h2.kickers)}`;
  };
  var variantNameOf = (h2) => {
    if (h2.cat === "fullhouse") return `of ${plural(h2.secondary)}`;
    if (h2.kickers.length === 0) return groupNameOf(h2);
    if (h2.cat === "high") return [h2.primary, ...h2.kickers].join("-");
    return `with ${describeKickers(h2.kickers)}`;
  };
  var groupKeyOf = (h2) => `${h2.cat}|${h2.primary}|${h2.cat === "fullhouse" ? 0 : h2.secondary}`;
  var shapeKeyOf = (h2) => `${h2.cat}${h2.primary}${h2.secondary}${h2.kickers.join("")}`;
  var MATCHED = { five: 5, quads: 4, fullhouse: 3, trips: 3, twopair: 2, pair: 2 };
  var canonicalDice = (h2) => {
    if (h2.cat === "straight") return h2.primary === 6 ? [6, 5, 4, 3, 2] : [5, 4, 3, 2, 1];
    if (h2.cat === "high") return [h2.primary, ...h2.kickers];
    const core = Array.from({ length: MATCHED[h2.cat] ?? 0 }, () => h2.primary);
    const pair = h2.cat === "fullhouse" || h2.cat === "twopair" ? [h2.secondary, h2.secondary] : [];
    return [...core, ...pair, ...h2.kickers];
  };
  var multisets = (size, min = 1) => size === 0 ? [[]] : DIE_VALUES.filter((v) => v >= min).flatMap((v) => multisets(size - 1, v).map((rest) => [v, ...rest]));
  var buildHands = () => multisets(5).map(classify).sort(compareShapes).map((shape, rank) => ({
    ...shape,
    rank,
    name: handNameOf(shape),
    group: groupNameOf(shape),
    variant: variantNameOf(shape),
    groupKey: groupKeyOf(shape),
    dice: canonicalDice(shape),
    catLabel: CATEGORY_LABEL[shape.cat]
  }));
  var HANDS = buildHands();
  var BY_SHAPE = new Map(HANDS.map((h2) => [shapeKeyOf(h2), h2]));
  var handAt = (rank) => HANDS[rank];
  var rankOf = (dice) => BY_SHAPE.get(shapeKeyOf(classify(dice))).rank;
  var buildGroups = () => {
    const strongestFirst = [...HANDS].reverse();
    const byKey = strongestFirst.reduce(
      (m, h2) => m.set(h2.groupKey, [...m.get(h2.groupKey) ?? [], h2]),
      /* @__PURE__ */ new Map()
    );
    return [...byKey.entries()].map(([key, hands]) => {
      const top = hands[0];
      const bottom = hands[hands.length - 1];
      return { key, cat: top.cat, name: top.group, hands, maxRank: top.rank, minRank: bottom.rank, collapsible: hands.length > 1 };
    });
  };
  var GROUPS = buildGroups();
  var GROUP_BY_KEY = new Map(GROUPS.map((g) => [g.key, g]));
  var groupOf = (h2) => GROUP_BY_KEY.get(h2.groupKey);
  var groupByKey = (key) => GROUP_BY_KEY.get(key);
  var groupTop = (rank) => groupOf(handAt(rank)).maxRank;
  var spokenName = (rank) => {
    const hnd = handAt(rank);
    const g = groupOf(hnd);
    return g.collapsible && g.maxRank === rank ? g.name : hnd.name;
  };
  var CATEGORY_INFO = CATEGORIES_STRONGEST_FIRST.map((cat) => {
    const hands = HANDS.filter((h2) => h2.cat === cat);
    return {
      cat,
      label: CATEGORY_LABEL[cat],
      blurb: CATEGORY_BLURB[cat],
      hands,
      groups: GROUPS.filter((g) => g.cat === cat),
      minRank: hands[0].rank,
      maxRank: hands[hands.length - 1].rank,
      best: hands[hands.length - 1]
    };
  });
  var inRange = (rank, lo, hi) => rank != null && rank >= lo && rank <= hi;

export {
  CATEGORIES, CATEGORIES_STRONGEST_FIRST, CATEGORY_LABEL, CATEGORY_BLURB, HAND_COUNT, TOP_RANK, BOTTOM_RANK, isRank,
  asRank, rungOf, plural, describeKickers, valuesWithCount, classify, compareShapes, groupNameOf,
  handNameOf, variantNameOf, groupKeyOf, shapeKeyOf, MATCHED, canonicalDice, multisets, buildHands,
  HANDS, BY_SHAPE, handAt, rankOf, buildGroups, GROUPS, GROUP_BY_KEY, groupOf,
  groupByKey, groupTop, spokenName, CATEGORY_INFO, inRange,
};
