// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1816-1889
// (bundle section "// src/domain/lobby.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { err, ok } from './result.js';
import { MAX_SEATS, seat, withLog } from './game.js';

  var BOT_NAMES = ["Loon", "Moose", "Pike", "Otter", "Osprey", "Beaver", "Heron", "Trout", "Chickadee", "Blackfly"];
  var seatOf = (s, id) => {
    const i2 = s.players.findIndex((p2) => p2.id === id);
    return i2 < 0 ? null : seat(i2);
  };
  var findSeat = seatOf;
  var shiftHostSeat = (hostSeat, removed) => hostSeat === null ? null : hostSeat > removed ? seat(hostSeat - 1) : hostSeat;
  var seatPlayer = (s, player) => {
    if (s.phase !== "lobby") return err("The game already started.");
    if (s.players.length >= MAX_SEATS) return err(`Table is full (${MAX_SEATS}).`);
    const verb = player.bot ? `(a computer${player.bot.random ? ", strategy drawn at random" : ""}) sits down.` : "sits down at the table.";
    return ok(withLog({ ...s, players: [...s.players, player] }, `${player.name} ${verb}`));
  };
  var unseatPlayer = (s, id) => {
    const at = seatOf(s, id);
    if (at === null || s.phase !== "lobby") return s;
    const name = s.players[at]?.name ?? "?";
    return withLog(
      { ...s, players: s.players.filter((_, i2) => i2 !== at), hostSeat: shiftHostSeat(s.hostSeat, at) },
      `${name} leaves the table.`
    );
  };
  var setConnected = (s, id, connected, rename) => {
    const at = seatOf(s, id);
    if (at === null) return s;
    const players = s.players.map((p2, i2) => i2 === at ? { ...p2, connected, name: rename ?? p2.name } : p2);
    const name = players[at]?.name ?? "?";
    return withLog({ ...s, players }, connected ? `${name} is back at the table.` : `${name} disconnected.`);
  };
  var withSpectators = (s, delta) => ({ ...s, spectators: Math.max(0, s.spectators + delta) });
  var nextBotName = (s) => {
    const taken = new Set(s.players.map((p2) => p2.name));
    return BOT_NAMES.find((n) => !taken.has(n)) ?? `Bot ${s.players.length + 1}`;
  };
  var makeBot = (s, id, profile) => ({
    id,
    name: nextBotName(s),
    lives: s.lives,
    losses: 0,
    connected: true,
    bot: profile
  });
  var cleanName = (name) => name.trim().slice(0, 16);
  var renameBot = (s, id, name) => {
    const at = seatOf(s, id);
    const p2 = at === null ? void 0 : s.players[at];
    if (!p2?.bot || s.phase !== "lobby") return s;
    const fresh = cleanName(name) || nextBotName(s);
    if (fresh === p2.name) return s;
    return withLog({ ...s, players: s.players.map((q, i2) => i2 === at ? { ...q, name: fresh } : q) }, `${p2.name} is now called ${fresh}.`);
  };
  var setBotProfile = (s, id, profile, label) => {
    const at = seatOf(s, id);
    const p2 = at === null ? void 0 : s.players[at];
    if (!p2?.bot || s.phase !== "lobby") return s;
    if (p2.bot.strategy === profile.strategy && p2.bot.random === profile.random) return s;
    return withLog({ ...s, players: s.players.map((q, i2) => i2 === at ? { ...q, bot: profile } : q) }, `${p2.name} will play ${label}.`);
  };
  var makeHuman = (id, name, lives) => ({
    id,
    name: name.trim().slice(0, 16) || "Player",
    lives,
    losses: 0,
    connected: true,
    bot: null
  });
  var hostStandsUp = (s) => {
    if (s.hostSeat === null || s.phase !== "lobby") return s;
    return withLog({ ...s, players: s.players.filter((_, i2) => i2 !== s.hostSeat), hostSeat: null }, "The host stands up to watch.");
  };
  var hostSitsDown = (s, host) => {
    if (s.hostSeat !== null || s.phase !== "lobby") return s;
    return withLog({ ...s, players: [host, ...s.players], hostSeat: seat(0) }, `${host.name} takes a seat.`);
  };

export {
  BOT_NAMES, seatOf, findSeat, shiftHostSeat, seatPlayer, unseatPlayer, setConnected, withSpectators,
  nextBotName, makeBot, cleanName, renameBot, setBotProfile, makeHuman, hostStandsUp, hostSitsDown,
};
