// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 883-903
// (bundle section "// src/domain/probability.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { DIE_VALUES } from './dice.js';
import { HAND_COUNT, rankOf } from './hands.js';

  var cache = /* @__PURE__ */ new Map();
  var cartesian = (count) => count === 0 ? [[]] : DIE_VALUES.flatMap((v) => cartesian(count - 1).map((rest) => [v, ...rest]));
  var survivalFor = (tableDice, cupCount) => {
    const key = `${[...tableDice].sort().join("")}|${cupCount}`;
    const hit = cache.get(key);
    if (hit) return hit;
    const combos = cartesian(cupCount);
    const density = combos.reduce(
      (acc, cup) => {
        const r = rankOf([...tableDice, ...cup]);
        acc[r] = (acc[r] ?? 0) + 1 / combos.length;
        return acc;
      },
      Array.from({ length: HAND_COUNT + 1 }, () => 0)
    );
    const survival = density.reduceRight((acc, p2) => [p2 + (acc[0] ?? 0), ...acc], []);
    cache.set(key, survival);
    return survival;
  };
  var probabilityAtLeast = (tableDice, cupCount, rank) => survivalFor(tableDice, cupCount)[rank] ?? 0;
  var expectedRank = (kept, rerolled) => survivalFor(kept, rerolled).slice(1, HAND_COUNT).reduce((a, p2) => a + p2, 0);

export { cache, cartesian, survivalFor, probabilityAtLeast, expectedRank };
