// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 862-877
// (bundle section "// src/domain/publicState.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { holderMaySee } from './game.js';

  var canSeeCup = (s, viewer) => {
    if (viewer.kind === "spectator" || s.reveal) return true;
    const r = s.round;
    return r !== null && viewer.seat === r.holder && holderMaySee(r);
  };
  var redactFor = (s, viewer) => {
    const seeCup = canSeeCup(s, viewer);
    const round = s.round && {
      ...s.round,
      dice: s.round.dice.map((d) => ({ inCup: d.inCup, value: d.inCup && !seeCup ? null : d.value }))
    };
    const { code, lives, phase, players, spectators, roundNo, reveal, winner, log, records, hostSeat, autoNextAt } = s;
    return { code, lives, phase, players, spectators, roundNo, round, reveal, winner, log, records, hostSeat, autoNextAt };
  };
  var publicCupIndices = (r) => r.dice.flatMap((d, i2) => d.inCup ? [i2] : []);
  var publicTableIndices = (r) => r.dice.flatMap((d, i2) => d.inCup ? [] : [i2]);

export { canSeeCup, redactFor, publicCupIndices, publicTableIndices };
