// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 2222-2337
// (bundle section "// src/domain/search.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { GROUPS, HANDS, groupOf, isRank } from './hands.js';

  var NUMBER_WORDS = {
    one: "1",
    ones: "1",
    ace: "1",
    aces: "1",
    two: "2",
    twos: "2",
    deuce: "2",
    deuces: "2",
    three: "3",
    threes: "3",
    four: "4",
    fours: "4",
    five: "5",
    fives: "5",
    six: "6",
    sixes: "6"
  };
  var STOP_WORDS = /* @__PURE__ */ new Set(["a", "an", "the", "of", "with", "kicker", "kickers"]);
  var tokenize = (text) => text.toLowerCase().replace(/,/g, " ").replace(/[^a-z0-9\s-]/g, " ").split(/\s+/).filter(Boolean).map((w) => NUMBER_WORDS[w] ?? w).map((w) => w.replace(/^(\d)s$/, "$1")).filter((w) => !STOP_WORDS.has(w));
  var p = (v) => `${v}`;
  var groupAliases = (g) => {
    const h2 = g.hands[0];
    const a = p(h2.primary);
    const b2 = h2.secondary === 0 ? "" : p(h2.secondary);
    switch (g.cat) {
      case "five":
        return [`five ${a}s`, `5 ${a}s`, a.repeat(5), `yahtzee ${a}`, `five of a kind ${a}`];
      case "quads":
        return [`four ${a}s`, `4 ${a}s`, `quad ${a}s`, `quads ${a}`, a.repeat(4), `four of a kind ${a}`];
      case "fullhouse":
        return [`${a}s full`, `${a}s over`, `${a} over`, `full house ${a}`, `${a}s full of`, `boat ${a}`];
      case "straight":
        return h2.primary === 6 ? ["straight 2-6", "high straight", "23456", "straight"] : ["straight 1-5", "low straight", "12345", "straight"];
      case "trips":
        return [`three ${a}s`, `3 ${a}s`, `trip ${a}s`, `trips ${a}`, `set of ${a}s`, a.repeat(3), `three of a kind ${a}`];
      case "twopair":
        return [`${a}s and ${b2}s`, `${a} and ${b2}`, `${a}s ${b2}s`, `two pair ${a} ${b2}`, `${a}${a}${b2}${b2}`, `${b2}s and ${a}s`];
      case "pair":
        return [`pair of ${a}s`, `pair ${a}`, `${a}s pair`, `one pair ${a}`, a.repeat(2), `two ${a}s`];
      case "high":
        return [`high die ${a}`, `high ${a}`, "nothing", "bust"];
    }
  };
  var handAliases = (h2) => {
    const base = groupAliases(groupOf(h2));
    const a = p(h2.primary);
    const b2 = h2.secondary === 0 ? "" : p(h2.secondary);
    const k = h2.kickers.join(" ");
    const kd = h2.kickers.join("");
    const specific = h2.cat === "fullhouse" ? [`${a}s over ${b2}s`, `${a} over ${b2}`, `${a}s full of ${b2}s`, `${a} full ${b2}`, `${a}${a}${a}${b2}${b2}`] : h2.cat === "high" ? [[h2.primary, ...h2.kickers].join(" "), [h2.primary, ...h2.kickers].join("-"), [h2.primary, ...h2.kickers].join("")] : h2.kickers.length ? base.flatMap((x) => [`${x} with ${k}`, `${x} ${k}`, `${x}${kd}`]) : [];
    return [...specific, ...base];
  };
  var isSubsequence = (needle, hay) => [...needle].reduce((pos, ch) => pos < 0 ? -1 : hay.indexOf(ch, pos) < 0 ? -1 : hay.indexOf(ch, pos) + 1, 0) >= 0;
  var scoreAlias = (queryTokens, alias) => {
    const tokens = tokenize(alias);
    const joined = tokens.join(" ");
    const scan = queryTokens.reduce(
      (acc, t) => {
        if (!acc.ok) return acc;
        const exactAfter = tokens.indexOf(t, acc.last + 1);
        const exact = exactAfter >= 0 ? exactAfter : tokens.indexOf(t);
        if (exact >= 0) return { ...acc, score: acc.score + 3, ordered: acc.ordered && exact > acc.last, last: exact };
        const prefix = tokens.findIndex((w) => w.startsWith(t));
        if (prefix >= 0) return { ...acc, score: acc.score + 2, ordered: acc.ordered && prefix > acc.last, last: prefix };
        if (joined.includes(t)) return { ...acc, score: acc.score + 1.5 };
        if (isSubsequence(t, joined)) return { ...acc, score: acc.score + 0.5 };
        return { ...acc, ok: false };
      },
      { score: 0, ok: true, last: -1, ordered: true }
    );
    if (!scan.ok) return 0;
    const orderBonus = scan.ordered ? 2 : 0;
    const lengthBonus = Math.max(0, 2 - Math.abs(tokens.length - queryTokens.length)) * 0.3;
    return scan.score + orderBonus + lengthBonus;
  };
  var bestScore = (queryTokens, aliases) => Math.max(0, ...aliases.map((a) => scoreAlias(queryTokens, a)));
  var topLegal = (g, legal) => g.hands.map((h2) => h2.rank).find((r) => legal.has(r)) ?? null;
  var groupSuggestion = (g, rank, score) => ({
    group: true,
    label: g.name,
    rank,
    variants: g.hands.length,
    score
  });
  var handSuggestion = (h2, score) => ({
    group: false,
    label: h2.name,
    rank: h2.rank,
    variants: 1,
    score
  });
  var byScoreThenStrength = (a, b2) => b2.score - a.score || (a.group === b2.group ? b2.rank - a.rank : a.group ? -1 : 1);
  var suggestHands = (query, above, limit = 14) => {
    const legal = new Set(HANDS.filter((h2) => above === null || h2.rank > above).map((h2) => h2.rank));
    const legalGroups = GROUPS.flatMap((g) => {
      const top = topLegal(g, legal);
      return top === null ? [] : [{ g, top }];
    });
    const q = query.trim();
    if (!q) return legalGroups.map(({ g, top }) => groupSuggestion(g, top, 0)).reverse().slice(0, 40);
    const rung = /^#?\s*(\d{1,3})$/.exec(q);
    const rungRank = rung ? Number(rung[1]) - 1 : NaN;
    const byRung = isRank(rungRank) && legal.has(rungRank) ? [handSuggestion(HANDS[rungRank], 100)] : [];
    const tokens = tokenize(q);
    if (tokens.length === 0) return byRung;
    const groups = legalGroups.flatMap(({ g, top }) => {
      const sc = bestScore(tokens, groupAliases(g));
      return sc > 0 ? [groupSuggestion(g, top, sc + 0.2)] : [];
    });
    const hands = HANDS.filter((h2) => legal.has(h2.rank) && groupOf(h2).collapsible).flatMap((h2) => {
      const sc = bestScore(tokens, handAliases(h2));
      return sc > 0 ? [handSuggestion(h2, sc)] : [];
    });
    return [...byRung, ...groups, ...hands].sort(byScoreThenStrength).slice(0, limit);
  };

export {
  NUMBER_WORDS, STOP_WORDS, tokenize, p, groupAliases, handAliases, isSubsequence, scoreAlias,
  bestScore, topLegal, groupSuggestion, handSuggestion, byScoreThenStrength, suggestHands,
};
