// Cuts the pure helpers of the legacy gin page's two UI IIFEs (the multiplayer UI and the Score
// Counter) into test/fixtures/legacy/gin-ui.cjs (docs/MIGRATION.md step 11), function by function:
// the card and meld markup, the table-fit loop, the sound-cue machine, the status, deadwood and
// hand blocks of `render()`, the scorer's maths, CSV export and voice parser, plus the two copies
// of the rules list. Each cut is verbatim; the module wraps them in a factory that takes the free
// variables the page supplied (`E`, `$`, `document`, `app`, `fx`, `toast`, `state`, ...) so node
// can call them as the oracle of the ui/, scorer/ and cues differential tests. Run:
//   node --experimental-strip-types tools/legacy/extract-gin-ui.ts
import {
  findLine,
  isMain,
  readRepoFile,
  textOfRanges,
  writeFixture,
  type Extracted,
  type LineRange,
} from './extract.ts';

export const GIN_UI_PAGE = 'legacy/gin-rummy/index.html';
export const GIN_UI_FIXTURE = 'gin-ui.cjs';
export const GIN_UI_KEY = 'gin-ui';
const TOOL = 'tools/legacy/extract-gin-ui.ts';

const UI_OPEN = '<script>/* Gin Rummy — multiplayer UI + PeerJS transport.';
const SCORER_OPEN = '<script>/* Standalone scorer mode';
const RULES_OPEN = '<ul class="rules-list">';
const RULES_CLOSE = '</ul>';

/** A cut: verbatim page lines, optionally wrapped in a generated function so node can call them. */
type Cut = Readonly<{
  range: LineRange;
  /** Lines emitted before and after the verbatim text (a wrapper for a block inside `render()`). */
  before: ReadonlyArray<string>;
  after: ReadonlyArray<string>;
}>;

const HEADER = [
  `// GENERATED by ${TOOL} from ${GIN_UI_PAGE}; do not edit.`,
  '// The pure helpers of the multiplayer UI IIFE and the Score Counter IIFE, verbatim and function by',
  '// function, inside a factory that supplies the free variables the page had in scope. Blocks cut',
  '// from inside render() are wrapped in a generated function each (marked "wrapper"). The two',
  '// copies of the rules list are exported as RULES_BLOCKS. Pinned to the page by',
  '// test/fixtures/legacy/MANIFEST.json.',
].join('\n');

/** The braces a line opens minus the ones it closes (template literals hold none here). */
const braceDelta = (line: string): number =>
  (line.match(/{/g) ?? []).length - (line.match(/}/g) ?? []).length;

/** Range of the top-level `function name(` at two-space indent, single- or multi-line. */
const functionRange = (lines: ReadonlyArray<string>, name: string, from: number): LineRange => {
  const start = findLine(
    lines,
    (l) => l.startsWith(`  function ${name}(`),
    `function ${name}`,
    from,
  );
  const opening = lines[start] ?? '';
  if (braceDelta(opening) === 0) return { startLine: start + 1, endLine: start + 1 };
  const end = findLine(lines, (l) => l === '  }', `end of function ${name}`, start);
  return { startLine: start + 1, endLine: end + 1 };
};

/** Range of one line: the first at or after `from` starting with `prefix`. */
const lineRange = (lines: ReadonlyArray<string>, prefix: string, from: number): LineRange => {
  const at = findLine(lines, (l) => l.startsWith(prefix), prefix, from);
  return { startLine: at + 1, endLine: at + 1 };
};

/** Range from the line starting with `startPrefix` to the next starting with `endPrefix`. */
const blockRange = (
  lines: ReadonlyArray<string>,
  startPrefix: string,
  endPrefix: string,
  from: number,
): LineRange => {
  const start = findLine(lines, (l) => l.startsWith(startPrefix), startPrefix, from);
  const end = findLine(lines, (l) => l.startsWith(endPrefix), endPrefix, start);
  return { startLine: start + 1, endLine: end + 1 };
};

const plain = (range: LineRange): Cut => ({ range, before: [], after: [] });
/** A block of render() as a function of the view: `locals` are the render() consts it read. */
const wrapped = (
  range: LineRange,
  signature: string,
  locals: ReadonlyArray<string>,
  returns: string,
): Cut => ({
  range,
  before: [
    `  // wrapper: the block below is cut from inside render()`,
    `  function ${signature} {`,
    ...locals.map((local) => `    const ${local} = v.${local};`),
  ],
  after: [`    return ${returns};`, '  }'],
});

/** Every cut, in page order, from the two IIFEs. */
const cutsOf = (lines: ReadonlyArray<string>): ReadonlyArray<Cut> => {
  const ui = findLine(lines, (l) => l.startsWith(UI_OPEN), UI_OPEN);
  const scorer = findLine(lines, (l) => l.startsWith(SCORER_OPEN), SCORER_OPEN);
  return [
    plain(functionRange(lines, 'fmtDuration', ui)),
    plain(functionRange(lines, 'fitTable', ui)),
    plain(lineRange(lines, '  const cueState = ', ui)),
    plain(functionRange(lines, 'playCuesFor', ui)),
    plain(functionRange(lines, 'cardHtml', ui)),
    plain(functionRange(lines, 'backHtml', ui)),
    plain(functionRange(lines, 'meldGroupsHtml', ui)),
    wrapped(
      blockRange(
        lines,
        "    let status = '', sub = '';",
        "    else if (v.phase === 'discard') {",
        ui,
      ),
      'legacyStatus(v)',
      ['opp'],
      '{ status, sub }',
    ),
    wrapped(
      blockRange(lines, '    let dwText;', '    } else dwText = ', ui),
      'legacyDeadwoodText(v)',
      ['me'],
      'dwText',
    ),
    wrapped(
      blockRange(lines, '    const deadHtml = me.deadwood.length', '    me.melds.forEach(', ui),
      'legacyHandHtml(v)',
      ['me'],
      'html + deadHtml',
    ),
    plain(lineRange(lines, '  const GIN_BONUS = 25, UNDERCUT_BONUS = 25;', scorer)),
    plain(lineRange(lines, '  const KNOCK_LABELS = ', scorer)),
    plain(functionRange(lines, 'totalFor', scorer)),
    plain(functionRange(lines, 'computeRoundScores', scorer)),
    plain(functionRange(lines, 'csvEscape', scorer)),
    plain(functionRange(lines, 'exportGame', scorer)),
    plain(lineRange(lines, '  const NUM_ONES = ', scorer)),
    plain(lineRange(lines, '  const NUM_TENS = ', scorer)),
    plain(functionRange(lines, 'wordsToNumber', scorer)),
    plain(functionRange(lines, 'extractNumber', scorer)),
    plain(functionRange(lines, 'parseVoiceScores', scorer)),
  ];
};

/** The two `<ul class="rules-list">` blocks (the home tab and the in-game overlay), in page order. */
const rulesRanges = (lines: ReadonlyArray<string>): ReadonlyArray<LineRange> => {
  const first = findLine(lines, (l) => l.trim() === RULES_OPEN, RULES_OPEN);
  const second = findLine(lines, (l) => l.trim() === RULES_OPEN, `second ${RULES_OPEN}`, first + 1);
  return [first, second].map((start) => ({
    startLine: start + 1,
    endLine: findLine(lines, (l) => l.trim() === RULES_CLOSE, RULES_CLOSE, start) + 1,
  }));
};

const FACTORY_OPEN = [
  "'use strict';",
  '/**',
  ' * deps: engine (window.GinEngine), $ (id -> element), document, app (the UI state object), fx',
  ' * (the sound object), toast, Blob, URL, setTimeout and the scorer `state`; each is what the page',
  ' * had under that name. Returns the cut functions; setState swaps the scorer state.',
  ' */',
  'module.exports = function legacyGinUi(deps) {',
  '  const E = deps.engine;',
  '  const $ = deps.$;',
  '  const document = deps.document;',
  '  const app = deps.app;',
  '  const fx = deps.fx;',
  '  const toast = deps.toast;',
  '  const Blob = deps.Blob;',
  '  const URL = deps.URL;',
  '  const setTimeout = deps.setTimeout;',
  '  let state = deps.state;',
];

const FACTORY_CLOSE = [
  '  return {',
  '    fmtDuration, fitTable, cueState, playCuesFor, cardHtml, backHtml, meldGroupsHtml,',
  '    legacyStatus, legacyDeadwoodText, legacyHandHtml,',
  '    GIN_BONUS, UNDERCUT_BONUS, KNOCK_LABELS, totalFor, computeRoundScores, csvEscape, exportGame,',
  '    NUM_ONES, NUM_TENS, wordsToNumber, extractNumber, parseVoiceScores,',
  '    setState: (s) => { state = s; },',
  '  };',
  '};',
];

const section = (page: string, range: LineRange): string =>
  `  // ---- ${page} lines ${String(range.startLine)}-${String(range.endLine)}`;

export const extractGinUi = (page: string): Extracted => {
  const lines = page.split('\n');
  const cuts = cutsOf(lines);
  const rules = rulesRanges(lines);
  const ranges = [...rules, ...cuts.map((c) => c.range)].sort((a, b) => a.startLine - b.startLine);
  const body = cuts.flatMap((cut) => [
    section(GIN_UI_PAGE, cut.range),
    ...cut.before,
    ...lines.slice(cut.range.startLine - 1, cut.range.endLine),
    ...cut.after,
  ]);
  const rulesExport = [
    `// The two rules lists (${rules.map((r) => `lines ${String(r.startLine)}-${String(r.endLine)}`).join(', ')}), verbatim.`,
    'module.exports.RULES_BLOCKS = [',
    ...rules.map((r) => `  ${JSON.stringify(lines.slice(r.startLine - 1, r.endLine).join('\n'))},`),
    '];',
  ];
  const fixture = [HEADER, ...FACTORY_OPEN, ...body, ...FACTORY_CLOSE, ...rulesExport].join('\n');
  const first = ranges[0];
  const last = ranges.at(-1);
  if (first === undefined || last === undefined) throw new Error('no ranges');
  return {
    startLine: first.startLine,
    endLine: last.endLine,
    ranges,
    source: textOfRanges(lines, ranges),
    fixture: `${fixture}\n`,
  };
};

if (isMain(import.meta.url)) {
  writeFixture(
    GIN_UI_KEY,
    GIN_UI_PAGE,
    GIN_UI_FIXTURE,
    TOOL,
    extractGinUi(readRepoFile(GIN_UI_PAGE)),
  );
}
