// Cuts the GinEngine UMD block out of the legacy gin page into test/fixtures/legacy/gin-engine.cjs
// (docs/MIGRATION.md step 2). The block is copied verbatim minus its `<script>` tag; its UMD
// wrapper takes the `module.exports` branch under node. Run:
//   node --experimental-strip-types tools/legacy/extract-gin-engine.ts
import { findLine, isMain, readRepoFile, writeFixture, type Extracted } from './extract.ts';

export const GIN_PAGE = 'games/gin-rummy/index.html';
export const GIN_FIXTURE = 'gin-engine.cjs';
export const GIN_KEY = 'gin-engine';
const TOOL = 'tools/legacy/extract-gin-engine.ts';

const SCRIPT_OPEN = '<script>';
const ENGINE_OPEN = `${SCRIPT_OPEN}/* Gin Rummy engine`;
const SCRIPT_CLOSE = '</script>';

const HEADER = [
  `// GENERATED by ${TOOL} from ${GIN_PAGE}; do not edit.`,
  '// The GinEngine UMD block, verbatim, with the <script> tag stripped; it loads through its',
  '// module.exports branch. Pinned to the page by test/fixtures/legacy/MANIFEST.json.',
].join('\n');

export const extractGinEngine = (page: string): Extracted => {
  const lines = page.split('\n');
  const start = findLine(lines, (line) => line.startsWith(ENGINE_OPEN), ENGINE_OPEN);
  const end = findLine(lines, (line) => line === SCRIPT_CLOSE, SCRIPT_CLOSE, start);
  const source = lines.slice(start, end + 1).join('\n');
  const body = lines.slice(start, end).join('\n').slice(SCRIPT_OPEN.length);
  return { startLine: start + 1, endLine: end + 1, source, fixture: `${HEADER}\n${body}\n` };
};

if (isMain(import.meta.url)) {
  writeFixture(GIN_KEY, GIN_PAGE, GIN_FIXTURE, TOOL, extractGinEngine(readRepoFile(GIN_PAGE)));
}
