// Cuts the fidice esbuild bundle from its IIFE start through the "// src/domain/search.ts" section
// into test/fixtures/legacy/fidice-core.cjs (docs/MIGRATION.md step 2), then closes the IIFE with
// a `module.exports` of every top-level binding in that range, so the domain (hands, game, lobby,
// publicState, probability, search), the bots and the protocol codecs are callable from node.
// The view and app sections after the cut need a DOM and are not part of the core. Run:
//   node --experimental-strip-types tools/legacy/extract-fidice-core.ts
import {
  findLine,
  isMain,
  readRepoFile,
  trimBlankBefore,
  writeFixture,
  type Extracted,
} from './extract.ts';

export const FIDICE_PAGE = 'legacy/fidice/index.html';
export const FIDICE_FIXTURE = 'fidice-core.cjs';
export const FIDICE_KEY = 'fidice-core';
const TOOL = 'tools/legacy/extract-fidice-core.ts';

const USE_STRICT = '"use strict";';
const IIFE_OPEN = '(() => {';
const LAST_SECTION = '  // src/domain/search.ts';
const STOP_SECTION = '  // src/view/vdom.ts';
const IIFE_CLOSE = '})();';
const NAMES_PER_LINE = 8;

const HEADER = [
  `// GENERATED by ${TOOL} from ${FIDICE_PAGE}; do not edit.`,
  '// The bundle from its IIFE start through the "// src/domain/search.ts" section, verbatim, plus a',
  '// generated module.exports of every top-level binding. Pinned to the page by',
  '// test/fixtures/legacy/MANIFEST.json.',
].join('\n');

const TOP_LEVEL_VAR = /^ {2}var ([A-Za-z_$][\w$]*) = /;

/** Every `  var name = ...` declared directly inside the IIFE, in source order, once each. */
export const topLevelNames = (lines: ReadonlyArray<string>): ReadonlyArray<string> => {
  const names = lines.flatMap((line) => {
    const match = TOP_LEVEL_VAR.exec(line);
    return match?.[1] === undefined ? [] : [match[1]];
  });
  return names.filter((name, i) => names.indexOf(name) === i);
};

const exportLines = (names: ReadonlyArray<string>): ReadonlyArray<string> => {
  const rows = Array.from({ length: Math.ceil(names.length / NAMES_PER_LINE) }, (_, i) =>
    names.slice(i * NAMES_PER_LINE, (i + 1) * NAMES_PER_LINE).join(', '),
  );
  return [
    '',
    '  // exports: every top-level binding above, generated',
    '  module.exports = {',
    ...rows.map((row) => `    ${row},`),
    '  };',
  ];
};

export const extractFidiceCore = (page: string): Extracted => {
  const lines = page.split('\n');
  const start = findLine(lines, (line) => line === USE_STRICT, USE_STRICT);
  if (lines[start + 1] !== IIFE_OPEN) throw new Error(`expected ${IIFE_OPEN} after ${USE_STRICT}`);
  const lastSection = findLine(lines, (line) => line === LAST_SECTION, LAST_SECTION, start);
  const stop = findLine(lines, (line) => line === STOP_SECTION, STOP_SECTION, lastSection);
  const end = trimBlankBefore(lines, stop);
  const body = lines.slice(start, end);
  const source = body.join('\n');
  const fixture = [HEADER, ...body, ...exportLines(topLevelNames(body)), IIFE_CLOSE, ''].join('\n');
  return { startLine: start + 1, endLine: end, source, fixture };
};

if (isMain(import.meta.url)) {
  writeFixture(
    FIDICE_KEY,
    FIDICE_PAGE,
    FIDICE_FIXTURE,
    TOOL,
    extractFidiceCore(readRepoFile(FIDICE_PAGE)),
  );
}
