// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1802-1813
// (bundle section "// src/bots/brain.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { redactFor } from '../domain/publicState.js';
import { strategyFor } from './registry.js';

  var emptyMemories = /* @__PURE__ */ new Map();
  var decide = (s, memories, rng) => {
    const r = s.round;
    if (s.phase !== "playing" || !r || s.reveal) return null;
    const me = s.players[r.holder];
    if (!me?.bot) return null;
    const strategy = strategyFor(me.bot);
    const memory = memories.has(me.id) ? memories.get(me.id) : strategy.fresh();
    const view = { state: redactFor(s, { kind: "seat", seat: r.holder }), me: r.holder };
    const d = strategy.decide(view, memory, rng);
    return { step: d.step, memories: new Map(memories).set(me.id, d.memory) };
  };

export { emptyMemories, decide };
