// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1769-1799
// (bundle section "// src/bots/registry.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { anyStrategy } from './strategy.js';
import { classicCautious, classicReckless, classicSteady } from './strategies/classic.js';
import { profiler } from './strategies/profiler.js';
import { trapper } from './strategies/trapper.js';
import { gambler } from './strategies/gambler.js';
import { pressure } from './strategies/pressure.js';
import { learnerWith } from './strategies/learner.js';
import { CHECKPOINTS } from './strategies/learnerWeights.js';

  var LEARNERS = CHECKPOINTS.map((c) => anyStrategy(learnerWith(`learner-${c.generation}`, `Learner (gen ${c.generation})`, `Trained by evolution for ${c.generation} generations against the shipped AIs; won ${(c.fitness * 100).toFixed(0)}% of its training games.`, c.weights)));
  var RANDOM_STRATEGY = "random";
  var SHIPPED = [
    anyStrategy(gambler),
    anyStrategy(profiler),
    anyStrategy(pressure)
  ];
  var POOL = [
    ...SHIPPED,
    anyStrategy(trapper),
    anyStrategy(classicCautious),
    anyStrategy(classicSteady),
    anyStrategy(classicReckless),
    ...LEARNERS
  ];
  var byId = new Map(POOL.map((s) => [s.id, s]));
  var strategyFor = (profile) => byId.get(profile.strategy) ?? SHIPPED[0];
  var profileFor = (choice, rng) => choice === RANDOM_STRATEGY ? { strategy: SHIPPED[Math.floor(rng() * SHIPPED.length)].id, random: true } : { strategy: byId.has(choice) ? choice : SHIPPED[0].id, random: false };
  var DIFFICULTIES = [
    { id: "easy", label: "Easy", strategy: anyStrategy(pressure), blurb: "The Showman \u2014 all theatre; calls too much and can be bluffed." },
    { id: "medium", label: "Medium", strategy: anyStrategy(profiler), blurb: "The Reader \u2014 learns your habits over the game and uses them." },
    { id: "hard", label: "Hard", strategy: anyStrategy(gambler), blurb: "The Gambler \u2014 the tournament winner; punishes small raises and rarely calls wrong." }
  ];
  var difficultyById = (id) => DIFFICULTIES.find((d) => d.id === id) ?? DIFFICULTIES[1];
  var difficultyOfChoice = (choice) => DIFFICULTIES.find((d) => d.strategy.id === choice)?.id ?? null;
  var learnerGeneration = (choice) => {
    const m = /^learner-(\d+)$/.exec(choice);
    return m ? Number(m[1]) : null;
  };
  var choiceLabel = (choice) => choice === RANDOM_STRATEGY ? "\u{1F3B2} Random strategy" : learnerGeneration(choice) !== null ? `Self-taught \xB7 ${learnerGeneration(choice)} generations` : byId.get(choice)?.name ?? SHIPPED[0].name;
  var describeProfile = (profile) => `${strategyFor(profile).name}${profile.random ? " (random)" : ""}`;

export {
  LEARNERS, RANDOM_STRATEGY, SHIPPED, POOL, byId, strategyFor, profileFor, DIFFICULTIES,
  difficultyById, difficultyOfChoice, learnerGeneration, choiceLabel, describeProfile,
};
