// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 880-880
// (bundle section "// src/bots/strategy.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

  var anyStrategy = (s) => s;

export { anyStrategy };
