// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 906-972
// (bundle section "// src/bots/toolkit.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { faceCounts } from '../domain/dice.js';
import {
  BOTTOM_RANK, TOP_RANK, asRank, groupOf, groupTop, handAt, rankOf,
} from '../domain/hands.js';
import { publicCupIndices, publicTableIndices } from '../domain/publicState.js';
import { expectedRank, probabilityAtLeast } from '../domain/probability.js';

  var tableValues = (r) => r.dice.flatMap((d) => !d.inCup && d.value !== null ? [d.value] : []);
  var canSeeAll = (r) => r.dice.every((d) => d.value !== null);
  var visibleRank = (r) => canSeeAll(r) ? rankOf(r.dice.map((d) => d.value)) : null;
  var oddsAtLeast = (r, rank) => probabilityAtLeast(tableValues(r), publicCupIndices(r).length, rank);
  var oddsBidTrue = (r) => r.bid === null ? 1 : oddsAtLeast(r, r.bid);
  var floorBid = (r) => r.bid === null ? BOTTOM_RANK : asRank(Math.min(TOP_RANK, r.bid + 1));
  var clampRank = (n, floor) => asRank(Math.max(floor, Math.min(TOP_RANK, Math.round(n))));
  var truthfulTop = (real) => {
    const top = groupTop(real);
    if (top === real) return top;
    const below = groupOf(handAt(real)).minRank - 1;
    return below < BOTTOM_RANK ? null : groupTop(asRank(below));
  };
  var say = (raw, real, floor) => {
    const wanted = clampRank(raw, floor);
    const honest = wanted <= real ? truthfulTop(wanted) : null;
    return honest !== null && honest >= floor ? honest : groupTop(wanted);
  };
  var keepFace = (r) => {
    const counts = faceCounts(r.dice.flatMap((d) => d.value === null ? [] : [d.value]));
    const [best] = [...counts.entries()].sort(([va, ca], [vb, cb]) => cb - ca || vb - va);
    return best && best[1] >= 2 ? best[0] : null;
  };
  var subsets = (n) => Array.from({ length: 2 ** n }, (_, mask) => Array.from({ length: n }, (_2, i2) => i2).filter((i2) => mask >> i2 & 1));
  var bestKeep = (r, floor) => {
    if (!canSeeAll(r)) return null;
    const values = r.dice.map((d) => d.value);
    const plans = subsets(values.length).map((keep) => {
      const kept = keep.map((i2) => values[i2]);
      return { keep, expected: expectedRank(kept, values.length - keep.length), clears: probabilityAtLeast(kept, values.length - keep.length, floor) };
    });
    return plans.reduce((best, p2) => p2.clears > best.clears + 1e-9 || Math.abs(p2.clears - best.clears) <= 1e-9 && p2.expected > best.expected ? p2 : best);
  };
  var rollFor = (r, plan) => {
    const keep = new Set(plan.keep);
    const pulls = publicCupIndices(r).filter((i2) => keep.has(i2));
    const tucks = publicTableIndices(r).filter((i2) => !keep.has(i2));
    const cupLeft = publicCupIndices(r).filter((i2) => !keep.has(i2));
    const roll2 = cupLeft.length + tucks.length === 0 ? null : { type: "roll", cup: cupLeft.length > 0, table: [], intoCup: tucks };
    return { pulls, roll: roll2 };
  };
  var seatsAfter = (s, from) => {
    const n = s.players.length;
    return Array.from({ length: n - 1 }, (_, k) => (from + k + 1) % n).filter((i2) => (s.players[i2]?.lives ?? 0) > 0);
  };
  var nextSeat = (view) => seatsAfter(view.state, view.me)[0] ?? view.me;
  var livesOf = (s, i2) => s.lives === 0 ? 3 : s.players[i2]?.lives ?? 0;
  var raisesBy = (bids, seat2) => bids.flatMap((b2, i2) => b2.seat === seat2 && i2 > 0 ? [b2.rank - bids[i2 - 1].rank] : []);
  var mean = (xs, fallback) => xs.length ? xs.reduce((a, b2) => a + b2, 0) / xs.length : fallback;
  var readSeat = (records, seat2) => {
    const theirCalledBids = records.filter((r) => r.bidder === seat2);
    const theirCalls = records.filter((r) => r.caller === seat2);
    const received = records.flatMap((r) => [
      ...r.bids.slice(1).filter((b2) => b2.seat === seat2).map(() => "raised"),
      ...r.caller === seat2 ? ["called"] : []
    ]);
    return {
      bluffRate: mean(theirCalledBids.map((r) => r.holds ? 0 : 1), 0.4),
      calledBids: theirCalledBids.length,
      callRate: mean(received.map((x) => x === "called" ? 1 : 0), 0.3),
      callAccuracy: mean(theirCalls.map((r) => r.holds ? 0 : 1), 0.5),
      calls: theirCalls.length,
      avgRaise: mean(records.flatMap((r) => raisesBy(r.bids, seat2)), 4),
      losses: records.filter((r) => r.loser === seat2).length
    };
  };
  var jitter = (rng, w) => (rng() - 0.5) * 2 * w;

export {
  tableValues, canSeeAll, visibleRank, oddsAtLeast, oddsBidTrue, floorBid, clampRank, truthfulTop,
  say, keepFace, subsets, bestKeep, rollFor, seatsAfter, nextSeat, livesOf,
  raisesBy, mean, readSeat, jitter,
};
