// The backgammon engine as one module (understand.md §4 step 4; panel E1 §5): the UI, protocol
// and storage import only from here. Pure: no DOM, no clock, no randomness of its own; `rng` and
// `now` are injected into `createGame`, `nextGame` and `applyAction` (docs/ARCHITECTURE.md
// "Module boundaries").
export { actorOf, applyAction, canDouble, MESSAGES } from './apply.ts';
export {
  afterMove,
  boardKey,
  canBearOff,
  checkerCount,
  emptyBoard,
  entryPoint,
  highestPoint,
  hits,
  isHomogeneous,
  isOpen,
  isWellFormed,
  otherSeat,
  POINT_INDICES,
  stackAt,
  topIs,
} from './board.ts';
export {
  decodeAction,
  decodeBoard,
  decodeDie,
  decodeMove,
  decodePointIndex,
  decodeSeat,
  decodeState,
  decodeView,
  pair,
} from './decode.ts';
export {
  chainsFrom,
  compareMoves,
  distinctOutcomes,
  expandDice,
  legalFirstMoves,
  legalMoves,
  levelCount,
  maximalPlays,
  moveKey,
  movesEqual,
  movesFrom,
  moveTo,
  playableDepth,
  reachableLevels,
  remainingDice,
  removeOne,
  singleSteps,
  sortMoves,
} from './moves.ts';
export {
  diceText,
  formatPosition,
  moveLabel,
  moveText,
  parseMove,
  parsePosition,
  playText,
  pointName,
  pointsText,
} from './notation.ts';
export { crawfordFor, matchOver, matchWinner, multiplierFor, pipCount, winnerOf } from './score.ts';
export {
  createGame,
  nextGame,
  OPENING_TIE_CAP,
  openingRoll,
  rollDie,
  startingBoard,
  withPosition,
  type Opening,
} from './setup.ts';
export {
  ACTION_TYPES,
  BAR_PIPS,
  CHECKERS,
  CUBE_MAX,
  DEFAULT_MATCH_LENGTH,
  DEFAULT_VARIANT,
  HOME_SIZE,
  MATCH_LENGTHS,
  PLAYS_CAP,
  POINTS,
} from './types.ts';
export type {
  Action,
  Board,
  CreateGameOptions,
  Cube,
  CubeValue,
  Dice,
  Die,
  From,
  GameRecord,
  GameResult,
  LogEntry,
  LogKind,
  Match,
  MatchOptions,
  Move,
  Multiplier,
  Now,
  Pair,
  Phase,
  Play,
  PlayedMove,
  Player,
  PointIndex,
  ResultReason,
  Seat,
  ShippedVariant,
  Stack,
  State,
  To,
  Variant,
  VariantRules,
  View,
} from './types.ts';
export { isShippedVariant, rulesOf, SHIPPED_VARIANTS, VARIANTS } from './variants.ts';
export { legalActions, viewFor } from './view.ts';
