// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 3529-3958
// (bundle section "// src/app/controller.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { CATEGORY_INFO, groupByKey, handAt } from '../domain/hands.js';
import { difficultyById } from '../bots/registry.js';
import { suggestHands } from '../domain/search.js';
import { mount } from '../view/vdom.js';
import { emptyLadder, emptyPicker, initialUi, isMyTurn } from '../view/ui.js';
import { catId, catKey, isOpen, mainMarks, rowId } from '../view/screens/ladder.js';
import { spectatorMarks } from '../view/screens/spectator.js';
import { appView } from '../view/app.js';

  var NAME_KEY = "fidice-name";
  var TOAST_MS = 2200;
  var TICK_MS = 500;
  var HANDOFF_CONFIRM_MS = 2500;
  var LOG_IDS = ["log", "spec-log"];
  var toggleKey = (l, key, open) => {
    const opened = new Set(l.open);
    const closed = new Set(l.closed);
    open ? (opened.delete(key), closed.add(key)) : (closed.delete(key), opened.add(key));
    return { ...l, open: opened, closed };
  };
  var openPath = (l, rank) => {
    const hnd = handAt(rank);
    const keys = [catKey(hnd.cat), hnd.groupKey];
    return { ...l, open: /* @__PURE__ */ new Set([...l.open, ...keys]), closed: new Set([...l.closed].filter((k) => !keys.includes(k))) };
  };
  var withLadder = (ui, id, f) => ({
    ...ui,
    ladders: { ...ui.ladders, [id]: f(ui.ladders[id]) }
  });
  var currentBid = (ui) => ui.game?.round?.bid ?? null;
  var reducePicker = (p2, intent, bid2) => {
    const suggestions = suggestHands(p2.query, bid2);
    switch (intent.type) {
      case "picker.query":
        return { ...p2, query: intent.value, highlight: 0, listOpen: true };
      case "picker.focus":
        return { ...p2, listOpen: true };
      case "picker.move":
        return { ...p2, highlight: Math.max(0, Math.min(suggestions.length - 1, p2.highlight + intent.delta)), listOpen: true };
      case "picker.choose":
        return { ...p2, selected: intent.rank, listOpen: false };
      case "picker.close":
        return { ...p2, listOpen: false };
      case "picker.enter": {
        const hit = suggestions[p2.highlight];
        return p2.listOpen && hit ? { ...p2, selected: hit.rank, listOpen: false } : p2;
      }
      default:
        return p2;
    }
  };
  var screenFor = (game, me, isHost) => {
    if (me.role === "spectator") return isHost && game.phase === "lobby" ? "lobby" : "spec";
    return game.phase === "lobby" ? "lobby" : "game";
  };
  var Controller = class {
    ui;
    session = null;
    host = null;
    hostName = "Host";
    toastTimer = null;
    tickTimer = null;
    deps;
    dispatch;
    constructor(deps, shareBase) {
      this.deps = deps;
      this.ui = initialUi(shareBase, deps.effects.storage.get(NAME_KEY) ?? "");
      this.dispatch = (intent) => this.handle(intent);
    }
    get state() {
      return this.ui;
    }
    /** Apply the URL hash (#join=CODE / #watch=CODE) and draw the first frame. */
    start() {
      const hash = /#(join|watch)=([A-Z0-9]{5})/i.exec(this.deps.effects.readHash());
      if (hash?.[1]?.toLowerCase() === "watch" && hash[2]) this.joinAs(hash[2].toUpperCase(), "spectator", null);
      else if (hash?.[2]) this.set({ joinCode: hash[2].toUpperCase(), pending: { kind: "join", code: hash[2].toUpperCase() }, screen: "name", error: null });
      this.render();
    }
    shownLogLength = 0;
    set(patch) {
      this.ui = { ...this.ui, ...patch };
    }
    render() {
      mount(this.deps.doc, this.deps.root, appView(this.ui, this.dispatch));
      this.followLog();
      this.manageTicker();
    }
    /** Keep the table talk pinned to its newest line whenever a line is added. */
    followLog() {
      const len = this.ui.game?.log.length ?? 0;
      if (len === this.shownLogLength) return;
      this.shownLogLength = len;
      LOG_IDS.forEach((id) => this.deps.effects.scrollToBottom(id));
    }
    toast(message) {
      this.set({ toast: message });
      if (this.toastTimer !== null) this.deps.clock.clearTimeout(this.toastTimer);
      this.toastTimer = this.deps.clock.setTimeout(() => {
        this.toastTimer = null;
        this.set({ toast: null });
        this.render();
      }, TOAST_MS);
    }
    /** Keep the "next round in Ns" countdown fresh while a reveal is showing. */
    manageTicker() {
      const counting = !!this.ui.game?.reveal && this.ui.game.autoNextAt !== null && this.ui.game.phase === "playing";
      if (counting && this.tickTimer === null) {
        this.tickTimer = this.deps.clock.setTimeout(() => {
          this.tickTimer = null;
          this.set({ now: this.deps.clock.now() });
          this.render();
        }, TICK_MS);
      }
    }
    /* ---------- sessions ---------- */
    events() {
      return {
        onReady: () => {
          this.set({ busy: null });
          this.render();
        },
        onState: (game, me) => {
          const isHost = this.session?.kind === "host";
          const screen = screenFor(game, me, isHost);
          const role = isHost ? "host" : me.role;
          const changedScreen = screen !== this.ui.screen;
          const turnStarted = isMyTurn({ ...this.ui, game, mySeat: me.seat }) && !isMyTurn(this.ui);
          this.set({
            game,
            mySeat: me.seat,
            role,
            screen,
            busy: null,
            now: this.deps.clock.now(),
            ...changedScreen ? { tab: "play" } : {},
            ...turnStarted ? { picker: emptyPicker, rollSelection: /* @__PURE__ */ new Set(), rollCup: false, rollHidden: false } : {},
            ...this.handoffFor(game, me.seat)
          });
          this.render();
        },
        onInfo: (m) => {
          this.toast(m);
          this.render();
        },
        onError: (m) => {
          this.toast(m);
          this.render();
        },
        onClosed: (reason) => {
          this.teardown();
          this.set({ screen: "name", error: reason, busy: null });
          this.render();
        }
      };
    }
    teardown() {
      this.session?.close();
      this.session = null;
      this.host = null;
      this.clearHandoffTimer();
      this.set({ game: null, mySeat: null, role: null, localTable: false, handoff: null, shownSeat: null });
    }
    /* ---------- pass the phone ---------- */
    handoffTimer = null;
    clearHandoffTimer() {
      if (this.handoffTimer !== null) this.deps.clock.clearTimeout(this.handoffTimer);
      this.handoffTimer = null;
    }
    /**
     * At a pass-the-phone table the screen must be covered whenever the cup reaches a human who is
     * not the one we last uncovered it for. Computers' turns and the public reveal need no cover.
     */
    handoffFor(game, mySeat) {
      if (!this.ui.localTable || game.phase !== "playing" || !game.round || game.reveal) return { handoff: null };
      const holder = game.round.holder;
      const human = game.players[holder]?.bot === null;
      if (!human || mySeat !== holder) return { handoff: null };
      if (holder === this.ui.shownSeat) return {};
      if (this.ui.handoff?.seat === holder) return {};
      this.clearHandoffTimer();
      return { handoff: { seat: holder, stage: "cover" } };
    }
    /** The big cover was tapped: show the small confirm, but bring the cover back if it isn't pressed soon. */
    handoffTap() {
      const h2 = this.ui.handoff;
      if (!h2) return;
      this.set({ handoff: { ...h2, stage: "confirm" } });
      this.clearHandoffTimer();
      this.handoffTimer = this.deps.clock.setTimeout(() => {
        this.handoffTimer = null;
        if (this.ui.handoff?.stage === "confirm") {
          this.set({ handoff: { ...this.ui.handoff, stage: "cover" } });
          this.render();
        }
      }, HANDOFF_CONFIRM_MS);
    }
    handoffConfirm() {
      const h2 = this.ui.handoff;
      if (!h2 || h2.stage !== "confirm") return;
      this.clearHandoffTimer();
      this.set({ handoff: null, shownSeat: h2.seat });
    }
    createHost(opts) {
      this.teardown();
      const host = this.deps.makeHost({ ...opts, code: this.deps.effects.randomCode() }, this.events());
      this.session = host;
      this.host = host;
      this.set({ role: "host", screen: opts.watch && opts.autostart ? "spec" : "lobby", busy: "Setting up the table\u2026", error: null });
      this.render();
    }
    joinAs(code, role, name) {
      this.teardown();
      this.session = this.deps.makeClient(code, role, name, this.events());
      this.set({ role, screen: role === "spectator" ? "spec" : "lobby", busy: "Paddling out to the host\u2026", error: null, game: null });
      this.render();
    }
    submitForm() {
      const name = this.ui.nameForm.name.trim().slice(0, 16) || "Player";
      this.deps.effects.storage.set(NAME_KEY, name);
      this.hostName = name;
      const p2 = this.ui.pending;
      if (!p2) return;
      if (p2.kind === "host") this.createHost({ hostName: name, lives: this.ui.nameForm.lives, watch: false, bots: 0, autostart: false });
      else if (p2.kind === "local") {
        const locals = this.ui.nameForm.locals.map((n) => n.trim().slice(0, 16)).filter((n) => n.length > 0);
        if (locals.length === 0) {
          this.set({ error: "Add at least one more player to pass the phone to." });
          return;
        }
        this.createHost({ hostName: name, lives: this.ui.nameForm.lives, watch: false, bots: 0, autostart: false, locals });
        this.set({ localTable: true });
      } else if (p2.kind === "solo") this.createHost({ hostName: name, lives: this.ui.nameForm.lives, watch: false, bots: p2.bots, autostart: false, botChoice: this.ui.nameForm.botChoice });
      else {
        const code = this.ui.joinCode.trim().toUpperCase();
        if (code.length !== 5) {
          this.set({ error: "Codes are 5 characters" });
          return;
        }
        this.set({ joinCode: code, pending: { kind: "join", code } });
        this.joinAs(code, "player", name);
      }
    }
    leave() {
      const g = this.ui.game;
      if (this.host && g?.phase === "playing" && !this.deps.effects.confirm("You are the host \u2014 leaving closes the table for everyone. Leave?")) return;
      this.teardown();
      this.deps.effects.setHash("");
      this.set({ screen: "menu", tab: "play", pending: null, error: null, busy: null });
    }
    play(action) {
      if (!this.session) return;
      this.session.act(action);
      if (action.type === "bid") this.set({ picker: emptyPicker });
      if (action.type === "roll") this.set({ rollSelection: /* @__PURE__ */ new Set(), rollCup: false, rollHidden: false });
    }
    /* ---------- intents ---------- */
    handle(intent) {
      switch (intent.type) {
        case "nav":
          this.set({ tab: intent.tab });
          this.deps.effects.scrollToTop();
          break;
        case "menu.create":
          this.set({ pending: { kind: "host" }, screen: "name", error: null });
          break;
        case "menu.solo":
          this.set({ pending: { kind: "solo", bots: 2 }, screen: "name", error: null });
          break;
        case "menu.local":
          this.set({ pending: { kind: "local" }, screen: "name", error: null });
          break;
        case "form.local.set":
          this.set({ nameForm: { ...this.ui.nameForm, locals: this.ui.nameForm.locals.map((n, i2) => i2 === intent.index ? intent.value : n) } });
          break;
        case "form.local.add":
          if (this.ui.nameForm.locals.length < 5) this.set({ nameForm: { ...this.ui.nameForm, locals: [...this.ui.nameForm.locals, ""] } });
          break;
        case "form.local.remove":
          this.set({ nameForm: { ...this.ui.nameForm, locals: this.ui.nameForm.locals.filter((_, i2) => i2 !== intent.index) } });
          break;
        case "handoff.tap":
          this.handoffTap();
          break;
        case "handoff.confirm":
          this.handoffConfirm();
          break;
        case "menu.watchBots":
          this.hostName = "Host";
          this.createHost({ hostName: "Host", lives: 3, watch: true, bots: 4, autostart: true });
          break;
        case "menu.join":
          this.set({ pending: { kind: "join", code: "" }, screen: "name", error: null });
          break;
        case "form.name":
          this.set({ nameForm: { ...this.ui.nameForm, name: intent.value } });
          break;
        case "form.lives":
          this.set({ nameForm: { ...this.ui.nameForm, lives: intent.value } });
          break;
        case "form.difficulty":
          this.set({ nameForm: { ...this.ui.nameForm, botChoice: difficultyById(intent.value).strategy.id } });
          break;
        case "config.open":
          this.set({ configTarget: intent.target });
          this.deps.effects.scrollToTop();
          break;
        case "config.close":
          this.set({ configTarget: null });
          break;
        case "config.pick": {
          const target = this.ui.configTarget;
          if (!target) break;
          if (target.kind === "solo") this.set({ nameForm: { ...this.ui.nameForm, botChoice: intent.choice } });
          else this.host?.setBot(target.seat, intent.choice);
          break;
        }
        case "form.code":
          this.set({ joinCode: intent.value.toUpperCase() });
          break;
        case "form.submit":
          this.submitForm();
          break;
        case "form.back":
          this.teardown();
          this.set({ screen: "menu", pending: null, error: null });
          break;
        case "lobby.start":
          this.session?.act({ type: "start" });
          break;
        case "lobby.addBot":
          this.host?.addBot();
          break;
        case "lobby.removeBot":
          this.host?.removeBot(intent.seat);
          break;
        case "lobby.renameBot":
          this.host?.renameBot(intent.seat, intent.name);
          break;
        case "lobby.setBot":
          this.host?.setBot(intent.seat, intent.choice);
          break;
        case "lobby.watch":
          this.host?.hostWatches(intent.watching, this.hostName);
          break;
        case "copy":
          void this.deps.effects.copyToClipboard(intent.text).then((ok2) => {
            this.toast(ok2 ? "Copied!" : "Select the link and press Ctrl/Cmd+C to copy");
            this.render();
          });
          break;
        case "leave":
          this.leave();
          break;
        case "play":
          this.play(intent.action);
          break;
        case "roll.toggleDie": {
          const sel = new Set(this.ui.rollSelection);
          sel.has(intent.die) ? sel.delete(intent.die) : sel.add(intent.die);
          this.set({ rollSelection: sel });
          break;
        }
        case "roll.cup":
          this.set({ rollCup: intent.on });
          break;
        // Tucking dice under the cup commits you to shaking the cup; un-tucking leaves the shake ticked until you untick it.
        case "roll.hidden":
          this.set({ rollHidden: intent.on, ...intent.on ? { rollCup: true } : {} });
          break;
        case "roll.go": {
          const { rollCup, rollHidden, rollSelection } = this.ui;
          if (!rollCup && rollSelection.size === 0) {
            this.toast('Select table dice or tick "Shake the cup" first');
            break;
          }
          const picked = [...rollSelection];
          const tucking = rollHidden && picked.length > 0;
          this.play({ type: "roll", cup: rollCup || tucking, table: tucking ? [] : picked, intoCup: tucking ? picked : [] });
          break;
        }
        case "picker.query":
        case "picker.focus":
        case "picker.move":
        case "picker.choose":
        case "picker.close":
          this.set({ picker: reducePicker(this.ui.picker, intent, currentBid(this.ui)) });
          break;
        case "picker.enter": {
          const before = this.ui.picker;
          const after = reducePicker(before, intent, currentBid(this.ui));
          if (after !== before) this.set({ picker: after });
          else if (before.selected !== null) this.play({ type: "bid", rank: before.selected });
          break;
        }
        case "picker.place":
          if (this.ui.picker.selected !== null) this.play({ type: "bid", rank: this.ui.picker.selected });
          break;
        case "ladder.toggle": {
          const marks = intent.ladder === "main" ? mainMarks(this.ui) : this.ui.game ? spectatorMarks(this.ui, this.ui.game) : mainMarks(this.ui);
          const l = this.ui.ladders[intent.ladder];
          const open = this.isKeyOpen(l, intent.key, marks);
          this.set(withLadder(this.ui, intent.ladder, (x) => toggleKey(x, intent.key, open)));
          break;
        }
        case "ladder.expandAll":
          this.set(withLadder(this.ui, intent.ladder, (l) => ({ ...emptyLadder, allOpen: !l.allOpen })));
          break;
        case "ladder.jump":
          this.set(withLadder(this.ui, "main", (l) => toggleKey({ ...l, closed: new Set([...l.closed].filter((k) => k !== catKey(intent.cat))) }, catKey(intent.cat), false)));
          this.render();
          this.deps.effects.scrollIntoView(catId("main", intent.cat));
          return;
        case "ladder.showBid": {
          const bid2 = currentBid(this.ui);
          this.set({ tab: "ladder", ...bid2 === null ? {} : withLadder(this.ui, "main", (l) => openPath(l, bid2)) });
          this.render();
          if (bid2 !== null) this.deps.effects.scrollIntoView(rowId("main", bid2));
          return;
        }
        case "spec.truth":
          this.set({ showTruth: intent.on });
          break;
      }
      this.render();
    }
    isKeyOpen(l, key, marks) {
      const range = keyRange(key);
      return range ? isOpen(l, key, range.lo, range.hi, marks) : l.open.has(key);
    }
  };
  var keyRange = (key) => {
    if (key.startsWith("cat:")) {
      const c = CATEGORY_INFO.find((x) => x.cat === key.slice(4));
      return c ? { lo: c.minRank, hi: c.maxRank } : null;
    }
    const g = groupByKey(key);
    return g ? { lo: g.minRank, hi: g.maxRank } : null;
  };

export {
  NAME_KEY, TOAST_MS, TICK_MS, HANDOFF_CONFIRM_MS, LOG_IDS, toggleKey, openPath, withLadder,
  currentBid, reducePicker, screenFor, Controller, keyRange,
};
