// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 3961-3999
// (bundle section "// src/app/effects.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

  var CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
  var browserEffects = () => {
    const storage = {
      get: (k) => {
        try {
          return localStorage.getItem(k) ?? sessionStorage.getItem(k);
        } catch {
          return null;
        }
      },
      set: (k, v) => {
        try {
          localStorage.setItem(k, v);
        } catch {
          try {
            sessionStorage.setItem(k, v);
          } catch {
          }
        }
      }
    };
    return {
      storage,
      copyToClipboard: (t) => navigator.clipboard.writeText(t).then(() => true, () => false),
      setHash: (h2) => {
        location.hash = h2;
      },
      readHash: () => location.hash,
      scrollToTop: () => window.scrollTo(0, 0),
      scrollIntoView: (id) => document.getElementById(id)?.scrollIntoView({ block: "center", behavior: "smooth" }),
      scrollToBottom: (id) => {
        const el = document.getElementById(id);
        if (el) el.scrollTop = el.scrollHeight;
      },
      confirm: (q) => window.confirm(q),
      randomCode: () => Array.from({ length: 5 }, () => CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)]).join(""),
      randomId: () => Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2)
    };
  };

export { CODE_ALPHABET, browserEffects };
