// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 4002-4030
// (bundle section "// src/app/main.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { DICE_IMAGES } from './src/assets/diceImages.js';
import './src/domain/dice.js';
import './src/domain/hands.js';
import './src/domain/result.js';
import './src/net/protocol.js';
import { ClientSession } from './src/net/client.js';
import './src/domain/game.js';
import './src/domain/publicState.js';
import './src/bots/strategy.js';
import './src/domain/probability.js';
import './src/bots/toolkit.js';
import './src/bots/strategies/classic.js';
import './src/bots/strategies/profiler.js';
import './src/bots/strategies/trapper.js';
import './src/bots/strategies/gambler.js';
import './src/bots/strategies/pressure.js';
import './src/bots/strategies/learner.js';
import './src/bots/strategies/learnerWeights.js';
import './src/bots/registry.js';
import './src/bots/brain.js';
import './src/domain/lobby.js';
import { HostSession } from './src/net/host.js';
import { clientTransport, hostTransport } from './src/net/peerjs.js';
import { realClock } from './src/net/session.js';
import './src/domain/search.js';
import './src/view/vdom.js';
import './src/view/components.js';
import './src/view/screens/menu.js';
import './src/view/ui.js';
import './src/view/screens/lobby.js';
import './src/view/screens/table.js';
import './src/view/screens/ladder.js';
import './src/view/screens/spectator.js';
import './src/view/screens/rules.js';
import './src/view/screens/botConfig.js';
import './src/view/app.js';
import { Controller } from './src/app/controller.js';
import { browserEffects } from './src/app/effects.js';

  var injectDiceStyles = () => {
    const style = document.createElement("style");
    style.textContent = Object.entries(DICE_IMAGES).map(([v, url]) => `.die.v${v}{background-image:url("${url}")}`).join("\n");
    document.head.appendChild(style);
  };
  var boot = () => {
    injectDiceStyles();
    const effects = browserEffects();
    const root = document.getElementById("app");
    if (!root) throw new Error("Missing #app root");
    const tokenKey = (code) => `fidice-token-${code}`;
    const controller = new Controller(
      {
        effects,
        clock: realClock,
        doc: document,
        root,
        makeHost: (opts, events) => new HostSession({ transport: hostTransport(opts.code), events, clock: realClock, rng: globalThis.__rng ?? Math.random, newId: effects.randomId }, opts),
        makeClient: (code, role, name, events) => new ClientSession(
          { transport: clientTransport(code), events, clock: realClock, rememberToken: (t) => effects.storage.set(tokenKey(code), t) },
          { role, name, savedToken: role === "player" ? effects.storage.get(tokenKey(code)) : null }
        )
      },
      `${location.origin}${location.pathname}${location.search}`
    );
    window.__fidice = { controller };
    controller.start();
  };
  boot();
