// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 3080-3169
// (bundle section "// src/view/screens/ladder.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { CATEGORY_INFO, inRange, rungOf } from '../../domain/hands.ts';
import { cls, h } from '../vdom.js';
import { diceRow, shapeRow } from '../components.js';

  var noMarks = { bid: null, cup: null, dimAtOrBelow: null };
  var catKey = (cat) => `cat:${cat}`;
  var rowId = (ladder, rank) => `${ladder}-r${rank}`;
  var groupId = (ladder, key) => `${ladder}-g${key.replace(/\|/g, "_")}`;
  var catId = (ladder, cat) => `${ladder}-cat-${cat}`;
  var isOpen = (l, key, lo, hi, marks) => {
    if (l.closed.has(key)) return false;
    if (l.allOpen || l.open.has(key)) return true;
    return inRange(marks.bid, lo, hi) || inRange(marks.cup, lo, hi);
  };
  var markers = (lo, hi, marks) => [
    ...inRange(marks.bid, lo, hi) ? [h("span", { class: "tab-marker bid" }, "\u{1F4E3} BID")] : [],
    ...inRange(marks.cup, lo, hi) ? [h("span", { class: "tab-marker cup" }, "\u{1F964} CUP")] : []
  ];
  var markClasses = (lo, hi, marks) => cls(inRange(marks.bid, lo, hi) && "mark-bid", inRange(marks.cup, lo, hi) && "mark-cup");
  var dim = (rank, marks) => cls(marks.dimAtOrBelow !== null && rank <= marks.dimAtOrBelow && "dim");
  var rungCell = (lo, hi) => h("div", { class: "rank" }, h("b", {}, lo === hi ? String(rungOf(lo)) : `${rungOf(lo)}\u2013${rungOf(hi)}`), lo === hi ? "rung" : "rungs");
  var handRow = (ladder, hnd, variant, marks) => h(
    "div",
    { class: cls("lrow", variant ? "variant" : "hand", markClasses(hnd.rank, hnd.rank, marks), dim(hnd.rank, marks)), id: rowId(ladder, hnd.rank), key: `r${hnd.rank}` },
    rungCell(hnd.rank, hnd.rank),
    h("div", {}, h("div", { class: "nm" }, hnd.name)),
    diceRow(hnd.dice, "sm"),
    markers(hnd.rank, hnd.rank, marks)
  );
  var groupRows = (ladder, l, g, marks, dispatch) => {
    if (!g.collapsible) return [handRow(ladder, g.hands[0], false, marks)];
    const open = isOpen(l, g.key, g.minRank, g.maxRank, marks);
    const top = g.hands[0];
    const coreCount = g.cat === "fullhouse" ? 3 : top.dice.length - top.kickers.length;
    const row = h(
      "div",
      {
        class: cls("lrow group tip-below", open && "open", !open && markClasses(g.minRank, g.maxRank, marks), dim(g.maxRank, marks)),
        id: groupId(ladder, g.key),
        key: `g${g.key}`,
        tip: open ? "Collapse" : "Show variants",
        on: { click: () => dispatch({ type: "ladder.toggle", ladder, key: g.key }) }
      },
      rungCell(g.minRank, g.maxRank),
      h("div", {}, h("div", { class: "nm" }, g.name), h("div", { class: "sub" }, `${g.hands.length} variants`)),
      diceRow(top.dice.slice(0, coreCount), "sm"),
      !open && markers(g.minRank, g.maxRank, marks)
    );
    return [row, ...open ? g.hands.map((hnd) => handRow(ladder, hnd, true, marks)) : []];
  };
  var categoryRows = (ladder, l, c, marks, dispatch) => {
    const key = catKey(c.cat);
    const open = isOpen(l, key, c.minRank, c.maxRank, marks);
    const row = h(
      "div",
      {
        class: cls("lrow catrow tip-below", open && "open", !open && markClasses(c.minRank, c.maxRank, marks)),
        id: catId(ladder, c.cat),
        key,
        tip: open ? "Collapse" : "Expand",
        on: { click: () => dispatch({ type: "ladder.toggle", ladder, key }) }
      },
      rungCell(c.minRank, c.maxRank),
      h("div", {}, h("div", { class: "nm" }, c.label), h("div", { class: "sub" }, `${c.blurb} \xB7 ${c.hands.length} hand${c.hands.length > 1 ? "s" : ""}`)),
      shapeRow(c.cat),
      !open && markers(c.minRank, c.maxRank, marks)
    );
    return [row, ...open ? c.groups.flatMap((g) => groupRows(ladder, l, g, marks, dispatch)) : []];
  };
  var ladderView = (ladder, l, marks, dispatch, extraClass, style) => h(
    "div",
    { class: cls("ladder", extraClass), id: `${ladder}Ladder`, ...style ? { style } : {} },
    CATEGORY_INFO.flatMap((c) => categoryRows(ladder, l, c, marks, dispatch))
  );
  var mainMarks = (ui) => ({ bid: ui.game?.round?.bid ?? null, cup: null, dimAtOrBelow: null });
  var ladderTab = (ui, dispatch) => h(
    "section",
    { id: "tab-ladder" },
    h(
      "div",
      { class: "ladder-head" },
      h("h2", { style: "font-size:26px;color:var(--pine)" }, "The Ladder"),
      h("span", { class: "muted small" }, "252 hands \xB7 strongest at the top. Collapsed, it's just the 8 poker hands \u2014 click a category to open it, then a hand to see its kicker variants."),
      h("span", { class: "spacer" }),
      h("button", { class: "btn-secondary", id: "btnExpandAll", tip: "Open or close every group", on: { click: () => dispatch({ type: "ladder.expandAll", ladder: "main" }) } }, ui.ladders.main.allOpen ? "Collapse all" : "Expand all")
    ),
    h(
      "div",
      { class: "ladder-head", style: "margin-top:-4px" },
      h("span", { class: "small muted", style: "font-weight:800" }, "Jump to:"),
      h("div", { class: "legend" }, CATEGORY_INFO.map((c) => h("span", { class: "chip", on: { click: () => dispatch({ type: "ladder.jump", cat: c.cat }) } }, c.label)))
    ),
    ladderView("main", ui.ladders.main, mainMarks(ui), dispatch)
  );

export {
  noMarks, catKey, rowId, groupId, catId, isOpen, markers, markClasses,
  dim, rungCell, handRow, groupRows, categoryRows, ladderView, mainMarks, ladderTab,
};
