// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 2541-2682
// (bundle section "// src/view/screens/menu.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import {
  DIFFICULTIES, choiceLabel, difficultyById, difficultyOfChoice,
} from '../../bots/registry.ts';
import { cls, h } from '../vdom.js';
import { die } from '../components.js';

  var onEnter = (fn) => (e) => {
    if (e.key === "Enter") fn();
  };
  var option = (id, icon, title2, sub, tip, primary, onPick) => h(
    "button",
    { id, class: cls("opt", primary && "primary"), tip, on: { click: onPick } },
    h("span", { class: "opt-ic", attrs: { "aria-hidden": "true" } }, icon),
    h("span", { class: "opt-text" }, h("span", { class: "opt-t" }, title2), h("span", { class: "opt-s" }, sub)),
    h("span", { class: "opt-go", attrs: { "aria-hidden": "true" } }, "\u203A")
  );
  var menuScreen = (ui, dispatch) => h(
    "div",
    { class: "menu", id: "screen-menu" },
    h("div", { class: "dice-hero" }, [6, 6, 6, 5, 2].map((v) => die(v, { size: "sm" }))),
    h("h1", {}, "Fidice"),
    h("div", { class: "where" }, "Kezar Lake, Maine"),
    h("div", { class: "tag" }, "One cup. Five dice. Don't get caught."),
    h(
      "div",
      { class: "menu-options" },
      option("btnLocal", "\u{1F4F1}", "Pass the phone", "Everyone on this device \u2014 it covers itself between turns", "Two to six people, one screen", true, () => dispatch({ type: "menu.local" })),
      option("btnCreate", "\u{1F310}", "Host online", "Start a table and share a link with friends", "Friends join from their own phones", false, () => dispatch({ type: "menu.create" })),
      option("btnJoin", "\u{1F511}", "Join with a code", "Type the host's five-letter code", "Sit down at a friend's table", false, () => dispatch({ type: "menu.join" })),
      option("btnSolo", "\u{1F916}", "Play the computers", "You against two \u2014 Easy, Medium, Hard or your own mix", "Solo practice", false, () => dispatch({ type: "menu.solo" })),
      option("btnWatchBots", "\u{1F37F}", "Watch the computers", "Four computers play; you watch the ladder", "Learn the game by watching", false, () => dispatch({ type: "menu.watchBots" }))
    ),
    h(
      "div",
      { class: "links", style: "margin-top:14px" },
      h("button", { on: { click: () => dispatch({ type: "nav", tab: "ladder" }) } }, "\u{1F4DC} See the ladder"),
      h("button", { on: { click: () => dispatch({ type: "nav", tab: "rules" }) } }, "\u{1F4D6} Read the rules")
    ),
    h("p", { class: "small muted", style: "margin-top:14px" }, "Everything is in your browser \u2014 no accounts, no downloads.")
  );
  var joinField = (ui, dispatch) => h(
    "div",
    { class: "join", style: "justify-content:center" },
    h("input", {
      id: "joinCode",
      tip: "Ask the host for their 5-letter code \u2014 it's on their lobby screen",
      attrs: { maxlength: "5", placeholder: "CODE", autocomplete: "off", autocapitalize: "characters" },
      props: { value: ui.joinCode },
      on: { input: (e) => dispatch({ type: "form.code", value: e.target.value }), keydown: onEnter(() => dispatch({ type: "form.submit" })) }
    })
  );
  var titleFor = (ui) => {
    switch (ui.pending?.kind) {
      case "solo":
        return { title: "You vs the computers", sub: "Two computers will sit down with you. Add more, rename them or change their strategy in the lobby." };
      case "local":
        return { title: "Pass the phone", sub: "Everyone plays on this device. Who's at the table?" };
      case "join":
        return ui.joinCode.length === 5 ? { title: `Joining ${ui.joinCode}`, sub: "Your friends will see this name at the table." } : { title: "Join with a code", sub: "Enter the host's code and the name your friends will see." };
      default:
        return { title: "Host a table online", sub: "Pick a name and how the table scores; then share the link." };
    }
  };
  var difficultyPicker = (ui, dispatch) => {
    const choice = ui.nameForm.botChoice;
    const on = difficultyOfChoice(choice);
    const blurb = on ? difficultyById(on).blurb : `Custom: ${choiceLabel(choice)}`;
    return h(
      "div",
      { class: "difficulty", id: "difficulty" },
      h("label", {}, "How good are the computers?"),
      h(
        "div",
        { class: "row", style: "gap:8px;justify-content:center" },
        h("div", { class: "seg", attrs: { role: "radiogroup" } }, DIFFICULTIES.map((d) => h("button", {
          id: `difficulty-${d.id}`,
          class: cls("seg-btn", d.id === on && "on"),
          tip: d.blurb,
          attrs: { role: "radio", "aria-checked": String(d.id === on) },
          on: { click: () => dispatch({ type: "form.difficulty", value: d.id }) }
        }, d.label))),
        h("button", { class: "btn-secondary", id: "btnConfigSolo", tip: "Pick an exact strategy, or the self-taught computer and how long it trained", on: { click: () => dispatch({ type: "config.open", target: { kind: "solo" } }) } }, "\u2699 Settings")
      ),
      h("div", { class: "small muted", id: "difficultyBlurb" }, blurb)
    );
  };
  var localPlayers = (ui, dispatch) => h(
    "div",
    { class: "locals", id: "locals" },
    ui.nameForm.locals.map((name, i2) => h(
      "div",
      { class: "row", key: `l${i2}`, style: "gap:6px" },
      h("input", {
        id: `localName-${i2}`,
        attrs: { maxlength: "16", placeholder: `Player ${i2 + 2}`, autocomplete: "off" },
        props: { value: name },
        on: { input: (e) => dispatch({ type: "form.local.set", index: i2, value: e.target.value }), keydown: onEnter(() => dispatch({ type: "form.submit" })) }
      }),
      ui.nameForm.locals.length > 1 && h("button", { class: "btn-ghost small", tip: "Remove this player", on: { click: () => dispatch({ type: "form.local.remove", index: i2 }) } }, "\u2715")
    )),
    ui.nameForm.locals.length < 5 && h("button", { class: "btn-ghost", id: "btnAddLocal", on: { click: () => dispatch({ type: "form.local.add" }) } }, "+ Add a player")
  );
  var nameScreen = (ui, dispatch) => {
    const { title: title2, sub } = titleFor(ui);
    const showLives = ui.pending?.kind !== "join";
    return h(
      "div",
      { class: "menu", id: "screen-name" },
      h("h2", { style: "font-size:30px;color:var(--pine)" }, title2),
      h("p", { class: "muted" }, sub),
      h(
        "div",
        { class: "stack", style: "margin-top:14px" },
        h("input", {
          id: "nameInput",
          attrs: { maxlength: "16", placeholder: "Your name (e.g. Andy)", autocomplete: "off" },
          props: { value: ui.nameForm.name },
          on: { input: (e) => dispatch({ type: "form.name", value: e.target.value }), keydown: onEnter(() => dispatch({ type: "form.submit" })) }
        }),
        ui.pending?.kind === "join" && joinField(ui, dispatch),
        ui.pending?.kind === "local" && localPlayers(ui, dispatch),
        ui.pending?.kind === "solo" && difficultyPicker(ui, dispatch),
        showLives && h(
          "div",
          { class: "row", style: "justify-content:center" },
          h(
            "div",
            {},
            h("label", {}, "Scoring"),
            h(
              "select",
              {
                id: "livesSel",
                tip: "Keep score (every round lost is a mark; the host ends the game) \u2014 or play for kayaks, where losing a call costs one and the last player standing wins.",
                props: { value: String(ui.nameForm.lives) },
                on: { change: (e) => dispatch({ type: "form.lives", value: Number(e.target.value) }) }
              },
              h("option", { attrs: { value: "0" }, props: { selected: ui.nameForm.lives === 0 } }, "Keep score \u2014 no kayaks"),
              [1, 2, 3, 4, 5].map((n) => h("option", { attrs: { value: String(n) }, props: { selected: n === ui.nameForm.lives } }, `${n} kayak${n === 1 ? "" : "s"} each`))
            )
          )
        ),
        h("button", { class: "btn-primary btn-big", id: "btnNameGo", on: { click: () => dispatch({ type: "form.submit" }) } }, "Let's go"),
        h("button", { class: "btn-ghost", id: "btnNameBack", on: { click: () => dispatch({ type: "form.back" }) } }, "\u2190 Back")
      ),
      ui.error && h("div", { class: "banner err", style: "margin-top:14px" }, ui.error)
    );
  };

export {
  onEnter, option, menuScreen, joinField, titleFor, difficultyPicker, localPlayers, nameScreen,
};
