// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 3172-3294
// (bundle section "// src/view/screens/spectator.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { HAND_COUNT, handAt, rankOf, rungOf, spokenName } from '../../domain/hands.ts';
import { publicCupIndices, publicTableIndices } from '../../domain/publicState.ts';
import { cls, h } from '../vdom.js';
import { die, logView, seatOptions, seats } from '../components.js';
import { isHostUi } from '../ui.js';
import { ladderView, noMarks } from './ladder.js';

  var nameAt2 = (g, i2) => i2 === null ? "?" : g.players[i2]?.name ?? "?";
  var trueRank = (r) => {
    const values = r.dice.map((d) => d.value);
    return values.every((v) => v !== null) ? rankOf(values) : null;
  };
  var spectatorMarks = (ui, g) => {
    const r = g.round;
    if (!r) return noMarks;
    const showTruth = ui.showTruth || g.reveal !== null;
    return { bid: r.bid, cup: showTruth ? trueRank(r) : null, dimAtOrBelow: r.bid };
  };
  var cupStage = (g, r) => {
    if (g.reveal) return `${nameAt2(g, g.reveal.caller)} called ${nameAt2(g, g.reveal.bidder)}`;
    if (r.bid === null) return "Opening the round";
    return r.touched ? "Accepted the cup \u2014 must raise" : "Deciding: call or accept";
  };
  var cupCard = (ui, g, dispatch) => {
    const r = g.round;
    const showTruth = ui.showTruth || g.reveal !== null;
    const real = r ? trueRank(r) : null;
    const truthLine = r && showTruth && real !== null ? h(
      "div",
      { class: "small", id: "specTruth" },
      "True hand: ",
      h("b", {}, handAt(real).name),
      r.bid !== null && (real >= r.bid ? h("span", { style: "color:var(--pine)" }, " \u2014 bid holds") : h("span", { style: "color:var(--red)" }, " \u2014 bid is a lie"))
    ) : h("div", { class: "small", id: "specTruth" });
    const who = g.phase === "over" ? `\u{1F3C6} ${g.winner === null ? "\u2014" : nameAt2(g, g.winner)}` : g.reveal ? "Cup lifted!" : r ? `${nameAt2(g, r.holder)} has the cup` : "Waiting for the game to start";
    return h(
      "div",
      { class: "card cup" },
      h("h3", {}, "\u{1F964} The cup"),
      h("div", { class: "bigval", id: "specCupWho" }, who),
      h("div", { class: "small muted", id: "specCupStage" }, r ? cupStage(g, r) : `${g.players.length} players seated`),
      h(
        "div",
        {},
        h("div", { class: "small muted", style: "font-weight:800" }, "Dice on the table (public)"),
        h("div", { class: "dice", id: "specOutDice" }, r && publicTableIndices(r).length ? publicTableIndices(r).map((i2) => die(r.dice[i2]?.value ?? null, { size: "sm" })) : h("span", { class: "small muted" }, "none"))
      ),
      h(
        "div",
        {},
        h("div", { class: "small muted", style: "font-weight:800" }, "Under the cup"),
        h("div", { class: "dice", id: "specCupDice" }, r && publicCupIndices(r).length ? publicCupIndices(r).map((i2) => die(showTruth ? r.dice[i2]?.value ?? null : null, { size: "sm" })) : h("span", { class: "small muted" }, "empty"))
      ),
      h(
        "label",
        { class: "toggle", tip: "Reveals the real hand to spectators only. Players must NOT be looking at this screen!" },
        h("input", { id: "truthToggle", attrs: { type: "checkbox" }, props: { checked: ui.showTruth }, on: { change: (e) => dispatch({ type: "spec.truth", on: e.target.checked }) } }),
        " Show the true hand"
      ),
      truthLine
    );
  };
  var bidCard2 = (g) => {
    const r = g.round;
    const bid2 = r?.bid ?? null;
    const history = r ? [...r.history].reverse() : [];
    return h(
      "div",
      { class: "card bid" },
      h("h3", {}, "\u{1F4E3} The bid"),
      h("div", { class: "bigval", id: "specBidName" }, bid2 === null ? "No bid yet" : spokenName(bid2)),
      h("div", { class: "small muted", id: "specBidWho" }, bid2 === null || !r ? "" : `by ${nameAt2(g, r.bidder)} \xB7 rung ${rungOf(bid2)} of ${HAND_COUNT}`),
      h("div", { class: "dice", id: "specBidDice" }, bid2 === null ? [] : handAt(bid2).dice.map((v) => die(v, { size: "sm" }))),
      h("div", { class: "small muted", style: "font-weight:800" }, "This round's bids"),
      h(
        "div",
        { class: "bidhist", id: "specBidHist" },
        history.length === 0 ? h("div", {}, h("span", { class: "muted" }, "\u2014")) : history.map((b2, i2) => h("div", { class: cls(i2 === 0 && "cur") }, h("span", {}, nameAt2(g, b2.seat)), h("span", {}, spokenName(b2.rank))))
      )
    );
  };
  var spectatorScreen = (ui, g, dispatch) => {
    const host = isHostUi(ui);
    return h(
      "div",
      { id: "screen-spec" },
      h(
        "div",
        { class: "row", style: "margin-bottom:14px" },
        h("div", { class: "banner", style: "flex:1", id: "specBanner" }, ui.busy ?? "\u{1F440} You're watching. Nothing you do here affects the game."),
        h("button", { class: "btn-ghost", id: "btnLeaveSpec", on: { click: () => dispatch({ type: "leave" }) } }, host ? "Close table" : "Leave")
      ),
      host && g.phase === "lobby" && h(
        "div",
        { class: "panel", id: "specHostBar", style: "margin-bottom:14px;padding:12px 16px" },
        h(
          "div",
          { class: "row" },
          h("b", {}, "You're hosting this table of computers."),
          h("span", { class: "small muted" }, `${g.players.length}/6 seated \xB7 code ${g.code}`),
          h("span", { class: "spacer" }),
          h("button", { class: "btn-secondary", props: { disabled: g.players.length >= 6 }, on: { click: () => dispatch({ type: "lobby.addBot" }) } }, "+ Add a computer"),
          h("button", { class: "btn-primary", props: { disabled: g.players.length < 2 }, on: { click: () => dispatch({ type: "lobby.start" }) } }, "Start game")
        )
      ),
      h(
        "div",
        { class: "spec" },
        h("div", { class: "ticker" }, cupCard(ui, g, dispatch)),
        h(
          "div",
          {},
          h(
            "div",
            { class: "ladder-head" },
            h("h2", { style: "font-size:22px;color:var(--pine)" }, "The Ladder"),
            h("span", { class: "small muted" }, "Strongest at the top \xB7 ", h("span", { style: "color:var(--accent);font-weight:800" }, "\u25AE bid"), " on the right \xB7 ", h("span", { style: "color:var(--lake);font-weight:800" }, "\u25AE cup"), " on the left")
          ),
          ladderView("spec", ui.ladders.spec, spectatorMarks(ui, g), dispatch, void 0, "max-height:78vh;overflow:auto")
        ),
        h(
          "div",
          { class: "ticker" },
          bidCard2(g),
          h("div", { class: "card", id: "specTalk" }, h("h3", {}, "Table talk"), logView(g.log, "spec-log")),
          h("div", { class: "card", id: "specPlayers" }, h("h3", {}, "Players"), seats(g, seatOptions(ui, dispatch), false))
        )
      )
    );
  };

export { nameAt2, trueRank, spectatorMarks, cupStage, cupCard, bidCard2, spectatorScreen };
