// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 975-1035
// (bundle section "// src/bots/strategies/classic.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { BOTTOM_RANK, TOP_RANK } from '../../domain/hands.js';
import { publicCupIndices, publicTableIndices } from '../../domain/publicState.js';
import { bestKeep, floorBid, jitter, oddsBidTrue, rollFor, say, visibleRank } from '../toolkit.js';

  var turnKey = (view) => `${view.state.roundNo}:${view.state.round?.history.length ?? 0}`;
  var decideCallOrAccept = (r, style, rng) => {
    if (r.bid !== null && r.bid >= TOP_RANK) return { type: "call" };
    return oddsBidTrue(r) + jitter(rng, style.noise) < style.callAt ? { type: "call" } : { type: "peek" };
  };
  var planTurn = (r, real, rng) => {
    const need = r.bid === null ? BOTTOM_RANK : r.bid + 1;
    const comfortable = real >= need + 2 && rng() < 0.75;
    if (comfortable) return { stage: "bidding", toPull: [], keep: [] };
    const best = bestKeep(r, floorBid(r));
    if (best === null || best.keep.length === r.dice.length) return { stage: "bidding", toPull: [], keep: [] };
    const { pulls } = rollFor(r, best);
    return { stage: pulls.length ? "pulling" : "rolling", toPull: pulls, keep: best.keep };
  };
  var chooseBid = (r, real, style, rng) => {
    const cur = r.bid;
    const floor = floorBid(r);
    if (cur === null) {
      const roll2 = rng();
      const raw = roll2 < 0.55 ? real : roll2 < 0.8 ? real - Math.floor(rng() * 12) : real + Math.floor(rng() * style.jump);
      return say(raw, real, floor);
    }
    if (real > cur) {
      const room = real - cur;
      const honest = rng() < 0.7 ? real : cur + 1 + Math.floor(rng() * Math.min(room, 4));
      const puffed = rng() < style.bluff * 0.4 ? real + 1 + Math.floor(rng() * style.jump) : honest;
      return say(puffed, real, floor);
    }
    const leap = rng() < style.bluff ? style.jump : 2;
    return say(cur + 1 + Math.floor(rng() * leap), real, floor);
  };
  var classic = (id, name, blurb, style) => ({
    id,
    name,
    blurb,
    fresh: () => null,
    decide(view, memory, rng) {
      const r = view.state.round;
      if (r.bid !== null && !r.touched) return { step: { delay: 1400 + rng() * 800, action: decideCallOrAccept(r, style, rng) }, memory };
      const real = visibleRank(r) ?? BOTTOM_RANK;
      const turn = turnKey(view);
      const plan = memory && memory.turn === turn ? memory : { turn, ...planTurn(r, real, rng) };
      if (plan.stage === "pulling") {
        const [next, ...rest] = plan.toPull;
        if (next !== void 0) {
          return { step: { delay: 900, action: { type: "pull", die: next } }, memory: { ...plan, stage: rest.length ? "pulling" : "rolling", toPull: rest } };
        }
      }
      if (plan.stage !== "bidding" && !r.rolled) {
        const keep = new Set(plan.keep);
        const cupLeft = publicCupIndices(r).filter((i2) => !keep.has(i2));
        const tucks = publicTableIndices(r).filter((i2) => !keep.has(i2));
        const action = { type: "roll", cup: cupLeft.length > 0, table: [], intoCup: tucks };
        if (cupLeft.length + tucks.length > 0) return { step: { delay: 1100, action }, memory: { ...plan, stage: "bidding", toPull: [] } };
      }
      return { step: { delay: 1500 + rng() * 900, action: { type: "bid", rank: chooseBid(r, real, style, rng) } }, memory: { ...plan, stage: "bidding" } };
    }
  });
  var classicCautious = classic("classic-cautious", "Cautious classic", "Calls early, bluffs small, plays the odds.", { callAt: 0.42, bluff: 0.25, jump: 3, noise: 0.08 });
  var classicSteady = classic("classic-steady", "Steady classic", "Middle of the road: bids its hand, bluffs now and then.", { callAt: 0.5, bluff: 0.4, jump: 5, noise: 0.08 });
  var classicReckless = classic("classic-reckless", "Reckless classic", "Lets bids ride and bluffs big.", { callAt: 0.6, bluff: 0.65, jump: 9, noise: 0.08 });

export {
  turnKey, decideCallOrAccept, planTurn, chooseBid, classic, classicCautious, classicSteady, classicReckless,
};
