// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1279-1519
// (bundle section "// src/bots/strategies/gambler.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { BOTTOM_RANK, GROUPS, TOP_RANK, asRank } from '../../domain/hands.js';
import { publicCupIndices, publicTableIndices } from '../../domain/publicState.js';
import {
  bestKeep, floorBid, jitter, keepFace, livesOf, nextSeat, oddsAtLeast, oddsBidTrue,
  readSeat, rollFor, say, visibleRank,
} from '../toolkit.js';

  var freshMemory = () => ({
    turn: "",
    stage: "bidding",
    toPull: [],
    toTuck: [],
    bids: 0,
    bluffs: 0,
    raises: 0,
    minRaises: 0,
    received: 0,
    calls: 0
  });
  var turnKey4 = (view) => `${view.state.roundNo}:${view.state.round?.history.length ?? 0}:${view.me}`;
  var clamp2 = (x, lo, hi) => Math.max(lo, Math.min(hi, x));
  var share = (n, d, fallback) => d > 0 ? n / d : fallback;
  var valueAt2 = (r, i2) => r.dice[i2]?.value ?? null;
  var GROUP_TOPS = [...GROUPS].map((g) => g.maxRank).sort((a, b2) => a - b2);
  var sayableFrom = (floor) => GROUP_TOPS.filter((c) => c >= floor);
  var calledRaises = (s, seat2) => s.records.flatMap((rec) => {
    if (rec.caller !== seat2) return [];
    const prev = rec.bids[rec.bids.length - 2];
    return [prev ? rec.bid - prev.rank : -1];
  });
  var listenerAt = (s, seat2) => {
    const read = readSeat(s.records, seat2);
    const observed = 0.34 + 0.95 * (read.callRate - 0.3);
    const punished = read.calls >= 2 ? 0.14 * (read.callAccuracy - 0.5) : 0;
    const desperate = livesOf(s, seat2) <= 1 ? -0.05 : 0;
    const raises = calledRaises(s, seat2).filter((x) => x >= 0);
    return {
      bar: clamp2(observed + punished + desperate, 0.12, 0.72),
      taste: raises.length > 0 ? raises.reduce((a, b2) => a + b2, 0) / raises.length : 22,
      tasteWeight: Math.min(0.35, 0.12 * raises.length)
    };
  };
  var callChance = (l, q, raise, maxed) => {
    if (maxed) return 1;
    const byOdds = 0.05 + 0.85 / (1 + Math.exp((q - l.bar) / 0.085));
    const byShape = 0.06 + 0.8 * Math.exp(-(((raise - l.taste) / 17) ** 2));
    return clamp2((1 - l.tasteWeight) * byOdds + l.tasteWeight * byShape, 0.03, 1);
  };
  var lieLean = (read, lives) => clamp2(
    0.3 * (read.bluffRate - 0.4) + 8e-3 * (read.avgRaise - 4) + 0.02 * Math.min(read.losses, 4) + (lives <= 1 ? 0.04 : 0),
    -0.12,
    0.18
  );
  var lastRaiseSize = (r) => {
    const h2 = r.history;
    const prev = h2[h2.length - 2];
    return r.bid !== null && prev ? r.bid - prev.rank : -1;
  };
  var honestyOdds = (raise, rank, q, lean) => {
    const opened = raise < 0;
    const leap = opened ? 0.86 : 0.25 + 0.56 / (1 + Math.exp(-(raise - 22) / 9));
    const high = opened ? 0 : -0.06 * (rank / TOP_RANK);
    const cheap = Math.max(0, (q - 0.6) / 0.4);
    const base = clamp2(leap + high - lean, 0.05, 0.95);
    return base + (1 - base) * cheap;
  };
  var aliveCount = (s) => s.players.filter((p2) => p2.lives > 0).length;
  var bestRival = (s, me) => s.players.reduce((m, p2, i2) => i2 === me ? m : Math.max(m, p2.lives), 0);
  var lifeCost = (s, me) => {
    const mine = livesOf(s, me);
    const edge = mine - bestRival(s, me);
    const scared = mine <= 1 ? 0.18 : 0;
    return clamp2(1 + 0.16 * edge + scared, 0.72, 1.42);
  };
  var lifeGain = (s, target, me) => {
    const theirs = livesOf(s, target);
    const leader = theirs >= bestRival(s, me) ? 0.22 : 0;
    const kill = theirs <= 1 ? 0.3 : 0;
    const spare = aliveCount(s) > 2 && livesOf(s, me) > theirs + 1 ? -0.14 : 0;
    return clamp2(1 + leader + kill + spare, 0.7, 1.6);
  };
  var stakesFor = (view) => {
    const s = view.state;
    const next = nextSeat(view);
    return {
      alive: aliveCount(s),
      myCost: lifeCost(s, view.me),
      gainNext: lifeGain(s, next, view.me),
      next: listenerAt(s, next)
    };
  };
  var escapeChance = (r, floor) => {
    const q = oddsAtLeast(r, floor);
    const shake2 = publicCupIndices(r).length > 0 || publicTableIndices(r).length > 0 ? q : 0;
    return 1 - (1 - q) * (1 - shake2);
  };
  var appetiteOf = (mem, s, me) => {
    const bluffShare = share(mem.bluffs, mem.bids, 0.3);
    const minShare = share(mem.minRaises, mem.raises, 0.2);
    const behind = livesOf(s, me) < bestRival(s, me) ? 0.06 : 0;
    return {
      bluff: clamp2(0.34 - bluffShare, -0.06, 0.16) + behind,
      minPenalty: clamp2(0.7 * (minShare - 0.22), 0, 0.14)
    };
  };
  var scoreBid = (r, real, c, st, app, floor, qFloor) => {
    const honest = c <= real;
    if (!honest && c >= TOP_RANK) return -9;
    const q = oddsAtLeast(r, c);
    const raise = r.bid === null ? -1 : c - r.bid;
    const pCall = callChance(st.next, q, raise, c >= TOP_RANK);
    const immediate = honest ? pCall * st.gainNext : -pCall * st.myCost;
    const above = asRank(Math.min(TOP_RANK, c + 1));
    const squeeze = (1 - oddsAtLeast(r, above)) ** 2;
    const whoProfits = st.alive === 2 ? 0.5 * st.gainNext : 0.16;
    const follow = (1 - pCall) * squeeze * whoProfits;
    const quiet = honest ? 0 : 4 * (qFloor - q);
    const style = (honest ? 0 : app.bluff) - (c === floor ? app.minPenalty : 0);
    return immediate + follow + style - quiet;
  };
  var bestBid = (r, real, st, app, rng) => {
    const floor = floorBid(r);
    const sayable = sayableFrom(floor);
    const plausible = sayable.filter((c, i2) => c <= real || i2 < 26 || oddsAtLeast(r, c) > 0.04);
    const pool = plausible.length > 0 ? plausible : sayable.slice(0, 1);
    const qFloor = oddsAtLeast(r, pool[0]);
    const scored = pool.map((c) => ({ c, v: scoreBid(r, real, c, st, app, floor, qFloor) + jitter(rng, 0.03) }));
    const pick = scored.reduce((a, b2) => b2.v > a.v ? b2 : a);
    return say(pick.c, real, floor);
  };
  var handValue = (r, hand, q, floor, lieRisk, st) => {
    if (hand < floor) return -lieRisk * st.myCost;
    const raise = r.bid === null ? -1 : hand - r.bid;
    return callChance(st.next, q, raise, hand >= TOP_RANK) * st.gainNext;
  };
  var sayableUpTo = (real) => GROUP_TOPS.filter((c) => c <= real).slice(-1)[0] ?? null;
  var shakeValue = (r, floor, st) => {
    const surv = GROUP_TOPS.map((c) => oddsAtLeast(r, c));
    const lieRisk = callChance(st.next, oddsAtLeast(r, floor), 4, false);
    const bottom = (1 - (surv[0] ?? 0)) * handValue(r, BOTTOM_RANK, 1, floor, lieRisk, st);
    return GROUP_TOPS.reduce(
      (acc, c, i2) => acc + ((surv[i2] ?? 0) - (surv[i2 + 1] ?? 0)) * handValue(r, c, surv[i2] ?? 0, floor, lieRisk, st),
      bottom
    );
  };
  var moved = (r, idx, inCup) => ({
    ...r,
    dice: r.dice.map((d, i2) => idx.includes(i2) ? { ...d, inCup } : d)
  });
  var keepers = (r, face) => face === null ? [] : publicCupIndices(r).filter((i2) => valueAt2(r, i2) === face);
  var junk = (r, face) => [...publicTableIndices(r).filter((i2) => valueAt2(r, i2) !== face)].sort((a, b2) => (valueAt2(r, a) ?? 0) - (valueAt2(r, b2) ?? 0)).slice(0, 2);
  var cupPlans = (r, real, floor, st) => {
    const face = keepFace(r);
    const keep = keepers(r, face);
    const bury = junk(r, face);
    const said = sayableUpTo(real);
    const lieRisk = callChance(st.next, oddsAtLeast(r, floor), 4, false);
    const stand = {
      pull: [],
      tuck: [],
      shake: false,
      worth: said === null || said < floor ? -lieRisk * st.myCost : handValue(r, said, oddsAtLeast(r, said), floor, lieRisk, st)
    };
    if (r.rolled) return [stand];
    const best = bestKeep(r, floor);
    if (best === null || best.keep.length === r.dice.length) return [stand];
    const { pulls } = rollFor(r, best);
    const tucks = publicTableIndices(r).filter((i2) => !best.keep.includes(i2));
    const shaken = moved(moved(r, pulls, false), tucks, true);
    return [stand, { pull: pulls, tuck: tucks, shake: true, worth: shakeValue(shaken, floor, st) }];
  };
  var rollAction = (r, tuck) => {
    const tucks = tuck.filter((i2) => r.dice[i2]?.inCup === false);
    if (publicCupIndices(r).length > 0 || tucks.length > 0) return { type: "roll", cup: true, table: [], intoCup: tucks };
    return { type: "roll", cup: false, table: publicTableIndices(r), intoCup: [] };
  };
  var planTurn4 = (r, real, st, rng) => {
    const floor = floorBid(r);
    const plans = cupPlans(r, real, floor, st);
    const best = plans.reduce((a, b2) => b2.worth + jitter(rng, 0.01) > a.worth ? b2 : a);
    if (!best.shake) return { stage: "bidding", toPull: [], toTuck: [] };
    return { stage: best.pull.length > 0 ? "pulling" : "rolling", toPull: best.pull, toTuck: best.tuck };
  };
  var callOrAccept = (view, r, mem, rng) => {
    if (r.bid === null || r.bid >= TOP_RANK) return true;
    const s = view.state;
    const bidder = r.bidder ?? nextSeat(view);
    const st = stakesFor(view);
    const p2 = clamp2(
      honestyOdds(lastRaiseSize(r), r.bid, oddsBidTrue(r), lieLean(readSeat(s.records, bidder), livesOf(s, bidder))),
      0.03,
      0.97
    );
    const evCall = (1 - p2) * lifeGain(s, bidder, view.me) - p2 * st.myCost;
    const floor = floorBid(r);
    const escape = escapeChance(r, floor);
    const pCallNext = callChance(st.next, oddsAtLeast(r, floor), 12, false);
    const evAccept = escape * pCallNext * st.gainNext - (1 - escape) * pCallNext * st.myCost + (st.alive > 2 ? 0.3 : 0.02);
    const callShare = share(mem.calls, mem.received, 0.3);
    const habit = callShare < 0.26 ? -0.08 : callShare > 0.58 ? 0.08 : 0;
    return evCall > evAccept + habit + jitter(rng, 0.05);
  };
  var gambler = {
    id: "gambler",
    name: "The Gambler",
    blurb: "Plays the chair on its left, not the dice: calls the squeezed, hides its good hands, dresses up its lies, and prices every life by the score.",
    fresh: freshMemory,
    decide(view, memory, rng) {
      const r = view.state.round;
      const mem = memory ?? freshMemory();
      if (r.bid !== null && !r.touched) {
        const call2 = callOrAccept(view, r, mem, rng);
        const seen = { ...mem, received: mem.received + 1, calls: mem.calls + (call2 ? 1 : 0) };
        return {
          step: { delay: 1200 + rng() * 900, action: call2 ? { type: "call" } : { type: "peek" } },
          memory: seen
        };
      }
      const real = visibleRank(r) ?? BOTTOM_RANK;
      const st = stakesFor(view);
      const turn = turnKey4(view);
      const plan = mem.turn === turn ? mem : { ...mem, turn, ...planTurn4(r, real, st, rng) };
      if (plan.stage === "pulling") {
        const [next, ...rest] = plan.toPull;
        if (next !== void 0 && valueAt2(r, next) !== null && r.dice[next]?.inCup === true) {
          const stage = rest.length > 0 ? "pulling" : r.rolled ? "bidding" : "rolling";
          return { step: { delay: 800 + rng() * 300, action: { type: "pull", die: next } }, memory: { ...plan, stage, toPull: rest } };
        }
      }
      if (plan.stage !== "bidding" && !r.rolled) {
        return { step: { delay: 950 + rng() * 400, action: rollAction(r, plan.toTuck) }, memory: { ...plan, stage: "bidding", toPull: [], toTuck: [] } };
      }
      const floor = floorBid(r);
      const app = appetiteOf(plan, view.state, view.me);
      const rank = bestBid(r, real, st, app, rng);
      const told = {
        ...plan,
        stage: "bidding",
        toPull: [],
        toTuck: [],
        bids: plan.bids + 1,
        bluffs: plan.bluffs + (rank > real ? 1 : 0),
        raises: plan.raises + (r.bid !== null ? 1 : 0),
        minRaises: plan.minRaises + (r.bid !== null && rank === floor ? 1 : 0)
      };
      return { step: { delay: 1400 + rng() * 800, action: { type: "bid", rank } }, memory: told };
    }
  };

export {
  freshMemory, turnKey4, clamp2, share, valueAt2, GROUP_TOPS, sayableFrom, calledRaises,
  listenerAt, callChance, lieLean, lastRaiseSize, honestyOdds, aliveCount, bestRival, lifeCost,
  lifeGain, stakesFor, escapeChance, appetiteOf, scoreBid, bestBid, handValue, sayableUpTo,
  shakeValue, moved, keepers, junk, cupPlans, rollAction, planTurn4, callOrAccept,
  gambler,
};
