// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1656-1759
// (bundle section "// src/bots/strategies/learner.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { BOTTOM_RANK, GROUPS, TOP_RANK, groupTop } from '../../domain/hands.js';
import { publicCupIndices } from '../../domain/publicState.js';
import {
  bestKeep, floorBid, livesOf, nextSeat, oddsAtLeast, oddsBidTrue, readSeat, rollFor,
  visibleRank,
} from '../toolkit.js';

  var RECEIVE_FEATURES = 11;
  var ROLL_FEATURES = 7;
  var BID_FEATURES = 10;
  var WEIGHT_COUNT = RECEIVE_FEATURES + ROLL_FEATURES + BID_FEATURES;
  var dot = (w, f) => f.reduce((a, x, i2) => a + x * (w[i2] ?? 0), 0);
  var clip = (x, lo, hi) => Math.max(lo, Math.min(hi, x));
  var turnKey6 = (view) => `${view.state.roundNo}:${view.state.round?.history.length ?? 0}`;
  var BID_LADDER = [...GROUPS].reverse().map((g) => g.maxRank);
  var raiseSize = (r) => {
    const prev = r.history[r.history.length - 2];
    return r.bid !== null && prev ? r.bid - prev.rank : 0;
  };
  var receiveFeatures = (view, r) => {
    const s = view.state;
    const bidder = r.bidder ?? view.me;
    const read = readSeat(s.records, bidder);
    return [
      1,
      oddsBidTrue(r),
      clip(raiseSize(r) / 50, 0, 2),
      r.history.length <= 1 ? 1 : 0,
      read.bluffRate,
      read.calledBids > 0 ? 1 : 0,
      livesOf(s, view.me) / 3,
      livesOf(s, bidder) / 3,
      oddsAtLeast(r, floorBid(r)),
      readSeat(s.records, nextSeat(view)).callRate,
      (r.bid ?? 0) / TOP_RANK
    ];
  };
  var rollFeatures = (view, r, real, floor, clears, expected) => [
    1,
    real >= floor ? 1 : 0,
    clip((real - floor) / 50, -2, 2),
    clears,
    (expected - real) / TOP_RANK,
    publicCupIndices(r).length / 5,
    livesOf(view.state, view.me) / 3
  ];
  var bidFeatures = (view, r, real, floor, cand) => {
    const honestTop2 = groupTop(real);
    const honest = honestTop2 >= cand;
    const next = nextSeat(view);
    const plausible = oddsAtLeast(r, cand);
    const nextCalls = readSeat(view.state.records, next).callRate;
    return [
      1,
      honest ? 1 : 0,
      clip((cand - floor) / 50, 0, 5),
      plausible,
      honest ? clip((honestTop2 - cand) / 50, 0, 5) : 0,
      honest ? 0 : clip((cand - honestTop2) / 50, 0, 5),
      nextCalls,
      livesOf(view.state, next) / 3,
      cand >= TOP_RANK ? 1 : 0,
      plausible * nextCalls
    ];
  };
  var slices = (w) => ({
    receive: w.slice(0, RECEIVE_FEATURES),
    roll: w.slice(RECEIVE_FEATURES, RECEIVE_FEATURES + ROLL_FEATURES),
    bid: w.slice(RECEIVE_FEATURES + ROLL_FEATURES, WEIGHT_COUNT)
  });
  var chooseBid3 = (view, r, real, floor, w) => {
    const legal = BID_LADDER.filter((c) => c >= floor);
    const scored = legal.map((cand) => ({ cand, score: dot(w, bidFeatures(view, r, real, floor, cand)) }));
    return scored.reduce((best, x) => x.score > best.score ? x : best).cand;
  };
  var learnerWith = (id, name, blurb, weights) => {
    const w = slices(weights);
    return {
      id,
      name,
      blurb,
      fresh: () => null,
      decide(view, memory, rng) {
        const r = view.state.round;
        if (r.bid !== null && !r.touched) {
          const call2 = r.bid >= TOP_RANK || dot(w.receive, receiveFeatures(view, r)) > 0;
          return { step: { delay: 1300 + rng() * 600, action: call2 ? { type: "call" } : { type: "peek" } }, memory: null };
        }
        const real = visibleRank(r) ?? BOTTOM_RANK;
        const floor = floorBid(r);
        const turn = turnKey6(view);
        const plan = memory && memory.turn === turn ? memory : (() => {
          const best = r.rolled ? null : bestKeep(r, floor);
          const wantsRoll = best !== null && best.keep.length < r.dice.length && dot(w.roll, rollFeatures(view, r, real, floor, best.clears, best.expected)) > 0;
          if (!wantsRoll || best === null) return { turn, stage: "bid", pulls: [] };
          const { pulls } = rollFor(r, best);
          return { turn, stage: pulls.length ? "pull" : "roll", pulls };
        })();
        const [next, ...rest] = plan.pulls;
        if (plan.stage === "pull" && next !== void 0 && r.dice[next]?.inCup) {
          return { step: { delay: 800, action: { type: "pull", die: next } }, memory: { ...plan, stage: rest.length ? "pull" : "roll", pulls: rest } };
        }
        if (plan.stage === "roll" && !r.rolled) {
          const best = bestKeep(r, floor);
          const roll2 = best ? rollFor(r, best).roll : null;
          if (roll2) return { step: { delay: 1e3, action: roll2 }, memory: { ...plan, stage: "bid" } };
        }
        return { step: { delay: 1400 + rng() * 600, action: { type: "bid", rank: chooseBid3(view, r, real, floor, w.bid) } }, memory: { ...plan, stage: "bid" } };
      }
    };
  };

export {
  RECEIVE_FEATURES, ROLL_FEATURES, BID_FEATURES, WEIGHT_COUNT, dot, clip, turnKey6, BID_LADDER,
  raiseSize, receiveFeatures, rollFeatures, bidFeatures, slices, chooseBid3, learnerWith,
};
