// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1522-1653
// (bundle section "// src/bots/strategies/pressure.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { BOTTOM_RANK, HAND_COUNT, TOP_RANK, asRank } from '../../domain/hands.js';
import { publicCupIndices, publicTableIndices } from '../../domain/publicState.js';
import { probabilityAtLeast } from '../../domain/probability.js';
import {
  bestKeep, floorBid, jitter, livesOf, nextSeat, oddsBidTrue, readSeat, rollFor,
  say, tableValues, truthfulTop, visibleRank,
} from '../toolkit.js';

  var RANKS = Array.from({ length: HAND_COUNT }, (_, i2) => i2);
  var ceilingOf = (table, cupCount, trust) => RANKS.findLast((r) => probabilityAtLeast(table, cupCount, r) >= trust) ?? BOTTOM_RANK;
  var clamp3 = (x, lo, hi) => Math.max(lo, Math.min(hi, x));
  var subsets2 = (xs) => {
    const [head, ...rest] = xs;
    if (head === void 0) return [[]];
    const tail = subsets2(rest);
    return [...tail, ...tail.map((s) => [head, ...s])];
  };
  var valueAt3 = (r, i2) => r.dice[i2]?.value ?? 1;
  var hereCeiling = (r, trust) => ceilingOf(tableValues(r), publicCupIndices(r).length, trust);
  var bestShow = (r, trust, showy) => {
    const cup = publicCupIndices(r);
    const table = tableValues(r);
    const scored = subsets2(cup).map((dice) => ({
      dice,
      ceiling: ceilingOf([...table, ...dice.map((i2) => valueAt3(r, i2))], cup.length - dice.length, trust)
    }));
    return scored.reduce(
      (a, b2) => b2.ceiling !== a.ceiling ? b2.ceiling > a.ceiling ? b2 : a : (showy ? b2.dice.length > a.dice.length : b2.dice.length < a.dice.length) ? b2 : a
    );
  };
  var bestErase = (r, trust, hungry) => {
    const table = publicTableIndices(r);
    if (table.length === 0) return { dice: [], ceiling: hereCeiling(r, trust) };
    const scored = subsets2(table).filter((dice) => dice.length > 0).map((dice) => {
      const left = table.filter((i2) => !dice.includes(i2)).map((i2) => valueAt3(r, i2));
      return { dice, ceiling: ceilingOf(left, 5 - left.length, trust) };
    });
    return scored.reduce(
      (a, b2) => b2.ceiling !== a.ceiling ? b2.ceiling > a.ceiling ? b2 : a : (hungry ? b2.dice.length > a.dice.length : b2.dice.length < a.dice.length) ? b2 : a
    );
  };
  var trustNeededBy = (s, victim) => {
    const read = readSeat(s.records, victim);
    const seen = clamp3(s.records.length / 4, 0, 1);
    const eager = 0.5 * (read.callRate - 0.3) * seen;
    const scared = livesOf(s, victim) <= 1 ? -0.08 : 0;
    return clamp3(0.44 + eager + scared, 0.28, 0.76);
  };
  var callBar = (s, bidder, rng, adj) => {
    const read = readSeat(s.records, bidder);
    const confidence = Math.min(1, read.calledBids / 2);
    return clamp3(0.5 + adj + 0.4 * (read.bluffRate - 0.4) * confidence + jitter(rng, 0.05), 0.3, 0.75);
  };
  var credit = (s, me) => {
    const mine = s.records.filter((rec) => rec.bidder === me);
    const busts = mine.filter((rec) => !rec.holds).length;
    return clamp3(1 - 0.4 * busts + 0.12 * (mine.length - busts), 0, 1);
  };
  var turnKey5 = (view) => `${view.state.roundNo}:${view.state.round?.history.length ?? 0}`;
  var freshTurn = (view, style, rng) => {
    const cred = credit(view.state, view.me);
    const draw = rng() * (0.55 + 0.45 * cred);
    const act = draw < 0.18 ? "straight" : draw < 0.36 ? "tell" : "show";
    return {
      turn: turnKey5(view),
      act,
      showy: act !== "straight" && rng() < style.showP,
      erasing: act !== "straight" && rng() < style.eraseP,
      puffing: act !== "straight" && rng() < style.puff * (0.4 + 0.6 * cred)
    };
  };
  var honestTop = (real, floor) => {
    const top = truthfulTop(real);
    return top !== null && top >= floor ? top : null;
  };
  var reachable = (r, trust) => {
    const cup = publicCupIndices(r).length;
    const best = Math.max(hereCeiling(r, trust), bestErase(r, trust, true).ceiling);
    return asRank(Math.min(TOP_RANK, best + (cup >= 2 ? 30 : 6)));
  };
  var receive2 = (view, r, style, rng) => {
    if (r.bid === null || r.bid >= TOP_RANK) return { type: "call" };
    const s = view.state;
    const bidder = r.bidder ?? view.me;
    const read = readSeat(s.records, bidder);
    const belief = oddsBidTrue(r) - 0.28 * (read.bluffRate - 0.4) * Math.min(1, read.calledBids / 2);
    if (belief < callBar(s, bidder, rng, style.callAdj)) return { type: "call" };
    const stuck = reachable(r, trustNeededBy(s, nextSeat(view))) <= r.bid;
    return stuck && belief < style.stuckAt ? { type: "call" } : { type: "peek" };
  };
  var step = (action, delay, memory) => ({ step: { action, delay }, memory });
  var makeShowman = (id, name, blurb, style) => ({
    id,
    name,
    blurb,
    fresh: () => null,
    decide(view, memory, rng) {
      const r = view.state.round;
      if (r.bid !== null && !r.touched) return { step: { delay: 1300 + rng() * 700, action: receive2(view, r, style, rng) }, memory };
      const turn = turnKey5(view);
      const plan = memory && memory.turn === turn ? memory : freshTurn(view, style, rng);
      const real = visibleRank(r) ?? BOTTOM_RANK;
      const floor = floorBid(r);
      const honest = honestTop(real, floor);
      const trust = clamp3(trustNeededBy(view.state, nextSeat(view)) + style.margin, 0.3, 0.9);
      const base = hereCeiling(r, trust);
      const cup = publicCupIndices(r);
      const poor = honest === null || honest < floor + style.hungerAt;
      if (!r.rolled) {
        const erase = bestErase(r, trust, poor);
        const sweep = erase.dice.length > 0 && erase.ceiling >= base - style.sweepTol;
        const wantsRoll = honest === null || plan.erasing && sweep && poor;
        const best = wantsRoll ? bestKeep(r, floor) : null;
        if (best !== null && best.keep.length < r.dice.length) {
          const { pulls, roll: roll2 } = rollFor(r, best);
          const pullNext = pulls[0];
          if (pullNext !== void 0) return step({ type: "pull", die: pullNext }, 800 + rng() * 400, plan);
          if (roll2 !== null) return step(roll2, 1100 + rng() * 500, plan);
        }
      }
      const show = bestShow(r, trust, plan.act === "show");
      const gate = plan.act === "straight" ? 12 : honest === null ? 1 : 22;
      const staging = show.ceiling > base + gate && (honest === null || plan.showy) ? show.dice : [];
      const next = staging[0];
      if (next !== void 0) return step({ type: "pull", die: next }, 800 + rng() * 400, plan);
      if (plan.act === "tell" && cup.length >= 2 && plan.showy) {
        const solo = cup.filter((i2) => valueAt3(r, i2) >= 5).find((i2) => ceilingOf([...tableValues(r), valueAt3(r, i2)], cup.length - 1, trust) >= base - 3);
        if (solo !== void 0) return step({ type: "pull", die: solo }, 900 + rng() * 400, plan);
      }
      const ceiling = hereCeiling(r, trust);
      const aim = honest !== null ? plan.puffing && ceiling > honest ? ceiling : honest : floor + Math.round(Math.max(0, ceiling - floor) * style.push);
      return step({ type: "bid", rank: say(aim, real, floor) }, 1400 + rng() * 800, plan);
    }
  });
  var pressure = makeShowman(
    "pressure",
    "The Showman",
    "Plays the cup like a prop: shows dice so its lies are believable, sweeps them away to erase what you learned, and says the biggest thing the room will swallow.",
    { margin: 0.18, push: 0.6, puff: 0.35, showP: 0.35, eraseP: 0.3, callAdj: 0, hungerAt: 24, stuckAt: 0.58, sweepTol: 8 }
  );

export {
  RANKS, ceilingOf, clamp3, subsets2, valueAt3, hereCeiling, bestShow, bestErase,
  trustNeededBy, callBar, credit, turnKey5, freshTurn, honestTop, reachable, receive2,
  step, makeShowman, pressure,
};
