// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1156-1276
// (bundle section "// src/bots/strategies/trapper.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { BOTTOM_RANK, TOP_RANK, rankOf } from '../../domain/hands.js';
import { publicCupIndices, publicTableIndices } from '../../domain/publicState.js';
import {
  bestKeep, canSeeAll, floorBid, jitter, keepFace, livesOf, nextSeat, oddsAtLeast,
  oddsBidTrue, readSeat, rollFor, say, seatsAfter, visibleRank,
} from '../toolkit.js';

  var SHAKE = "shakes the cup";
  var MIN_HIDDEN = 2;
  var JUNK_FACE = 4;
  var turnKey3 = (view) => `${view.state.roundNo}:${view.state.round?.history.length ?? 0}`;
  var valueAt = (r, i2) => r.dice[i2]?.value ?? 0;
  var shakesHeard = (s) => {
    const from = s.log.findIndex((e) => e.text.startsWith(`Round ${s.roundNo}:`));
    return from < 0 ? null : s.log.slice(from).filter((e) => e.text.includes(SHAKE)).length;
  };
  var snapshot = (s, r) => {
    const shakes = shakesHeard(s);
    return canSeeAll(r) && shakes !== null ? { roundNo: s.roundNo, shakes, values: r.dice.map((d) => d.value) } : null;
  };
  var exactRank = (s, r, k) => {
    if (k === null || k.roundNo !== s.roundNo || shakesHeard(s) !== k.shakes) return null;
    const values = r.dice.flatMap((d, i2) => {
      const seen = d.value ?? k.values[i2] ?? null;
      return seen === null ? [] : [seen];
    });
    return values.length === r.dice.length ? rankOf(values) : null;
  };
  var climbAhead = (view) => {
    const middle = seatsAfter(view.state, view.me).slice(0, -1);
    return middle.reduce((sum, i2) => sum + Math.min(14, Math.max(2, readSeat(view.state.records, i2).avgRaise)), 0);
  };
  var stickiness = (s, i2) => {
    const name = s.players[i2]?.name;
    const theirs = name === void 0 ? [] : s.log.filter((e) => e.text.startsWith(`${name} `));
    const turns = theirs.filter((e) => e.text.includes(" bids ")).length;
    const shakes = theirs.filter((e) => e.text.includes(SHAKE)).length;
    return turns < 2 ? 0 : Math.max(0, 1 - shakes / turns);
  };
  var stickyAhead = (view) => {
    const middle = seatsAfter(view.state, view.me).slice(0, -1);
    return middle.length === 0 ? 0 : middle.reduce((sum, i2) => sum + stickiness(view.state, i2), 0) / middle.length;
  };
  var timidity = (view) => 1 - Math.min(1, readSeat(view.state.records, nextSeat(view)).callRate * 1.6);
  var receive = (view, r, know, rng) => {
    const s = view.state;
    const bid2 = r.bid;
    if (bid2 >= TOP_RANK) return { delay: 1400, action: { type: "call" } };
    const real = exactRank(s, r, know);
    if (real !== null) return { delay: 900 + rng() * 500, action: bid2 > real ? { type: "call" } : { type: "peek" } };
    const bidder = r.bidder;
    const read = readSeat(s.records, bidder);
    const honesty = read.calledBids >= 2 ? 1 - read.bluffRate : 0.55;
    const p2 = oddsBidTrue(r);
    const believable = p2 + (1 - p2) * honesty;
    const room = oddsAtLeast(r, floorBid(r));
    const theirTrigger = Math.min(0.8, Math.max(0.12, readSeat(s.records, nextSeat(view)).callRate));
    const worthIt = 0.035 + 2 * (1 - room) * theirTrigger + (livesOf(s, view.me) <= 1 ? -0.08 : 0) + jitter(rng, 0.05);
    return { delay: 1300 + rng() * 700, action: believable < worthIt ? { type: "call" } : { type: "peek" } };
  };
  var planTurn3 = (r, real, floor, rng) => {
    const face = keepFace(r);
    const spare = Math.max(0, publicCupIndices(r).length - MIN_HIDDEN);
    if (real >= floor) {
      const show = publicCupIndices(r).filter((i2) => valueAt(r, i2) !== face && valueAt(r, i2) <= JUNK_FACE).slice(0, rng() < 0.55 ? Math.min(spare, 2) : 0);
      return { stage: show.length ? "pull" : "bid", toPull: show, intoCup: [], rollCup: false };
    }
    if (r.rolled) return { stage: "bid", toPull: [], intoCup: [], rollCup: false };
    const best = bestKeep(r, floor);
    if (best === null || best.keep.length === r.dice.length) return { stage: "bid", toPull: [], intoCup: [], rollCup: false };
    const { pulls } = rollFor(r, best);
    const hide = publicTableIndices(r).filter((i2) => !best.keep.includes(i2));
    return { stage: pulls.length ? "pull" : "roll", toPull: pulls, intoCup: hide, rollCup: true };
  };
  var chooseBid2 = (view, r, real, rng) => {
    const s = view.state;
    const floor = floorBid(r);
    if (real < floor) {
      const shy = timidity(view);
      const leap = rng() < 0.25 + 0.3 * shy ? Math.floor(rng() * 10) : Math.floor(rng() * 4);
      return say(floor + leap, real, floor);
    }
    const next = nextSeat(view);
    const read = readSeat(s.records, next);
    const asleep = read.calls === 0 && read.callRate < 0.15 && s.records.length >= 6;
    if (asleep && livesOf(s, view.me) > 1 && livesOf(s, next) > 1 && rng() < 0.5) {
      return say(Math.min(TOP_RANK - 12, real + 6 + Math.floor(rng() * (10 + 22 * timidity(view)))), real, floor);
    }
    const lure = Math.max(0, 1.2 * stickyAhead(view) * climbAhead(view) * (1 + jitter(rng, 0.4)));
    return say(Math.max(floor, real - lure), real, floor);
  };
  var holding = (view, r, mem, rng) => {
    const real = visibleRank(r) ?? BOTTOM_RANK;
    const turn = turnKey3(view);
    const plan = mem.plan && mem.plan.turn === turn ? mem.plan : { turn, ...planTurn3(r, real, floorBid(r), rng) };
    const [next, ...rest] = plan.toPull;
    if (plan.stage === "pull" && next !== void 0 && r.dice[next]?.inCup) {
      const stage = rest.length ? "pull" : plan.rollCup || plan.intoCup.length ? "roll" : "bid";
      return {
        step: { delay: 800 + rng() * 400, action: { type: "pull", die: next } },
        memory: { ...mem, plan: { ...plan, toPull: rest, stage } }
      };
    }
    const cup = publicCupIndices(r);
    const tuck = plan.intoCup.filter((i2) => !r.dice[i2]?.inCup);
    if (plan.stage === "roll" && !r.rolled && plan.rollCup && (cup.length > 0 || tuck.length > 0)) {
      const action = { type: "roll", cup: cup.length > 0, table: [], intoCup: tuck };
      return { step: { delay: 1e3 + rng() * 500, action }, memory: { ...mem, plan: { ...plan, stage: "bid" } } };
    }
    return {
      step: { delay: 1400 + rng() * 800, action: { type: "bid", rank: chooseBid2(view, r, real, rng) } },
      memory: { ...mem, plan: { ...plan, stage: "bid" } }
    };
  };
  var trapper = {
    id: "trapper",
    name: "The Trapper",
    blurb: "Shows you rubbish, bids the truth, remembers every die \u2014 and calls the moment you overreach.",
    fresh: () => ({ plan: null, know: null }),
    decide(view, memory, rng) {
      const s = view.state;
      const r = s.round;
      const seen = snapshot(s, r);
      const mem = seen === null ? memory : { ...memory, know: seen };
      if (r.bid !== null && !r.touched) return { step: receive(view, r, mem.know, rng), memory: mem };
      return holding(view, r, mem, rng);
    }
  };

export {
  SHAKE, MIN_HIDDEN, JUNK_FACE, turnKey3, valueAt, shakesHeard, snapshot, exactRank,
  climbAhead, stickiness, stickyAhead, timidity, receive, planTurn3, chooseBid2, holding,
  trapper,
};
