// GENERATED by tools/legacy/extract-gin-ui.ts from legacy/gin-rummy/index.html; do not edit.
// The pure helpers of the multiplayer UI IIFE and the Score Counter IIFE, verbatim and function by
// function, inside a factory that supplies the free variables the page had in scope. Blocks cut
// from inside render() are wrapped in a generated function each (marked "wrapper"). The two
// copies of the rules list are exported as RULES_BLOCKS. Pinned to the page by
// test/fixtures/legacy/MANIFEST.json.
'use strict';
/**
 * deps: engine (window.GinEngine), $ (id -> element), document, app (the UI state object), fx
 * (the sound object), toast, Blob, URL, setTimeout and the scorer `state`; each is what the page
 * had under that name. Returns the cut functions; setState swaps the scorer state.
 */
module.exports = function legacyGinUi(deps) {
  const E = deps.engine;
  const $ = deps.$;
  const document = deps.document;
  const app = deps.app;
  const fx = deps.fx;
  const toast = deps.toast;
  const Blob = deps.Blob;
  const URL = deps.URL;
  const setTimeout = deps.setTimeout;
  let state = deps.state;
  // ---- legacy/gin-rummy/index.html lines 1332-1335
  function fmtDuration(ms) {
    ms = Math.max(0, ms); const t = Math.floor(ms / 1000), h = Math.floor(t / 3600), m = Math.floor((t % 3600) / 60), s = t % 60;
    return h ? `${h}h ${m}m` : m ? `${m}m ${s}s` : `${s}s`;
  }
  // ---- legacy/gin-rummy/index.html lines 1350-1361
  function fitTable() {
    const scr = $('tableScreen');
    if (!scr || scr.classList.contains('hidden')) return;
    const appEl = document.getElementById('app'), handEl = $('hand');
    const overflows = () => (appEl.scrollHeight > appEl.clientHeight + 1) || (handEl.scrollHeight > handEl.clientHeight + 1);
    let scale = 1;
    scr.style.setProperty('--tscale', '1');
    while (scale > 0.5 && overflows()) {
      scale = Math.round((scale - 0.05) * 100) / 100;
      scr.style.setProperty('--tscale', String(scale));
    }
  }
  // ---- legacy/gin-rummy/index.html lines 1429-1429
  const cueState = { key: null, turnKey: null };
  // ---- legacy/gin-rummy/index.html lines 1430-1461
  function playCuesFor(v) {
    const me = v.me.idx;
    if (app.role === 'local') {
      // one phone: turn chimes come from the curtain; hand/game results are shared, so use neutral-positive cues
      if (v.phase === 'roundOver' && v.result) { const k = 'round:' + v.result.ts; if (cueState.key !== k) { cueState.key = k; if (v.result.void) fx.neutral(); else if (v.result.outcome === 'gin') fx.gin(); else fx.knockGood(); } }
      else if (v.phase === 'gameOver') { const k = 'over:' + v.players.map(p => p.total).join(','); if (cueState.key !== k) { cueState.key = k; fx.win(); } }
      return;
    }
    if (v.phase === 'gameOver') {
      const k = 'over:' + v.handNumber + ':' + v.players.map(p => p.total).join(',');
      if (cueState.key !== k) { cueState.key = k; if (v.winner === me) fx.win(); else fx.lose(); }
      return;
    }
    if (v.phase === 'roundOver' && v.result) {
      const k = 'round:' + v.result.ts;
      if (cueState.key !== k) {
        cueState.key = k;
        if (v.result.void) fx.neutral();
        else if (v.result.scorerIdx === me) { if (v.result.outcome === 'gin') fx.gin(); else fx.knockGood(); }
        else fx.bad();
      }
      cueState.turnKey = null;
      return;
    }
    const tk = v.handNumber + ':' + v.phase + ':' + v.turn + ':' + (v.upcardStage || '');
    const prevWasMine = cueState.turnKey && cueState.turnKey.endsWith(':me');
    if (v.isMyTurn && v.phase !== 'discard') {
      if (cueState.turnKey !== tk + ':me' && !prevWasMine) fx.yourTurn();
      cueState.turnKey = tk + ':me';
    } else if (!v.isMyTurn) cueState.turnKey = tk + ':them';
    else cueState.turnKey = tk + ':me';
  }
  // ---- legacy/gin-rummy/index.html lines 1464-1469
  function cardHtml(c, opts) {
    opts = opts || {};
    const red = c.s === 'H' || c.s === 'D';
    const cls = ['card', red ? 'red' : 'black', opts.mini ? 'mini' : '', opts.big ? 'big' : '', opts.selected ? 'selected' : '', opts.dim ? 'dim' : '', opts.fresh ? 'fresh' : '', opts.locked ? 'locked' : ''].filter(Boolean).join(' ');
    return `<div class="${cls}" data-card="${c.id}"><span class="rank">${E.rankLabel(c.r)}</span><span class="suit">${E.SUIT_SYMBOL[c.s]}</span><span class="rank br">${E.rankLabel(c.r)}</span></div>`;
  }
  // ---- legacy/gin-rummy/index.html lines 1470-1470
  function backHtml(cls) { return `<div class="card back ${cls || ''}"></div>`; }
  // ---- legacy/gin-rummy/index.html lines 1471-1476
  function meldGroupsHtml(melds, extra, mini) {
    let html = '';
    melds.forEach((m, i) => { html += `<div class="meld-group m${i % 5}">${m.map(c => cardHtml(c, { mini })).join('')}</div>`; });
    if (extra) html += extra;
    return html;
  }
  // ---- legacy/gin-rummy/index.html lines 1514-1522
  // wrapper: the block below is cut from inside render()
  function legacyStatus(v) {
    const opp = v.opp;
    let status = '', sub = '';
    const oppTurnName = opp.name;
    if (v.phase === 'roundOver') { status = v.result && v.result.void ? 'Hand void' : 'Hand over'; sub = 'See results'; }
    else if (!v.isMyTurn) {
      status = `${oppTurnName}'s turn`;
      sub = v.phase === 'upcard' ? 'Deciding on the upcard…' : v.phase === 'draw' ? 'Drawing a card…' : 'Choosing a discard…';
    } else if (v.phase === 'upcard') { status = 'Your turn'; sub = 'Take the upcard or pass'; }
    else if (v.phase === 'draw') { status = 'Your turn'; sub = v.forceStock ? 'Both passed — tap the stock to draw' : 'Tap the stock or the discard pile'; }
    else if (v.phase === 'discard') { status = 'Your turn'; sub = app.selectedCard ? 'Discard it, or knock if you can' : 'Tap a card to select it'; }
    return { status, sub };
  }
  // ---- legacy/gin-rummy/index.html lines 1531-1538
  // wrapper: the block below is cut from inside render()
  function legacyDeadwoodText(v) {
    const me = v.me;
    let dwText;
    if (v.phase === 'discard' && v.isMyTurn && v.discardOptions) {
      if (app.selectedCard && !v.discardOptions[app.selectedCard].locked) dwText = `Deadwood after discard: ${v.discardOptions[app.selectedCard].deadwood}`;
      else {
        const best = Math.min(...Object.values(v.discardOptions).filter(o => !o.locked).map(o => o.deadwood));
        dwText = `Best possible deadwood: ${best}`;
      }
    } else dwText = `Deadwood: ${me.deadwoodValue}`;
    return dwText;
  }
  // ---- legacy/gin-rummy/index.html lines 1547-1549
  // wrapper: the block below is cut from inside render()
  function legacyHandHtml(v) {
    const me = v.me;
    const deadHtml = me.deadwood.length ? `<div class="meld-group dead">${me.deadwood.map(c => cardHtml(c, { selected: app.selectedCard === c.id, fresh: v.lastDrawnId === c.id, locked: v.drawnFromDiscard === c.id && v.phase === 'discard' && v.isMyTurn })).join('')}</div>` : '';
    let html = '';
    me.melds.forEach((m, i) => { html += `<div class="meld-group m${i % 5}">${m.map(c => cardHtml(c, { selected: app.selectedCard === c.id, fresh: v.lastDrawnId === c.id, locked: v.drawnFromDiscard === c.id && v.phase === 'discard' && v.isMyTurn })).join('')}</div>`; });
    return html + deadHtml;
  }
  // ---- legacy/gin-rummy/index.html lines 2099-2099
  const GIN_BONUS = 25, UNDERCUT_BONUS = 25;
  // ---- legacy/gin-rummy/index.html lines 2100-2100
  const KNOCK_LABELS = { knock: 'Knock', gin: 'Gin' };
  // ---- legacy/gin-rummy/index.html lines 2116-2116
  function totalFor(id) { return state.rounds.reduce((a, r) => a + (r.scores[id] || 0), 0); }
  // ---- legacy/gin-rummy/index.html lines 2119-2130
  function computeRoundScores(deadwood, knockerId, knockType) {
    const scores = {}; state.players.forEach(p => { scores[p.id] = 0; });
    const kdw = deadwood[knockerId] || 0;
    state.players.forEach(p => {
      if (p.id === knockerId) return;
      const odw = deadwood[p.id] || 0;
      if (knockType === 'gin') scores[knockerId] += GIN_BONUS + odw;
      else if (odw <= kdw) scores[p.id] += (kdw - odw) + UNDERCUT_BONUS;
      else scores[knockerId] += odw - kdw;
    });
    return scores;
  }
  // ---- legacy/gin-rummy/index.html lines 2289-2292
  function csvEscape(v) {
    v = String(v == null ? '' : v);
    return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
  }
  // ---- legacy/gin-rummy/index.html lines 2293-2325
  function exportGame() {
    if (!state || !state.rounds.length) { toast('No hands scored yet — nothing to export.'); return; }
    const players = state.players;
    const header = ['Hand', 'Time', 'Duration', 'Knocker', 'Type', ...players.map(p => p.name + ' Deadwood'), ...players.map(p => p.name + ' Score')];
    const rows = [header];
    state.rounds.forEach((r, i) => {
      const k = players.find(p => p.id === r.knockerId);
      const prevTs = i > 0 ? state.rounds[i - 1].ts : state.startedAt;
      rows.push([
        i + 1,
        new Date(r.ts).toLocaleString(),
        fmtDuration(r.ts - prevTs),
        r.void ? 'VOID' : (k ? k.name : ''),
        r.void ? 'void' : (KNOCK_LABELS[r.knockType] || 'Knock'),
        ...players.map(p => r.void ? '' : (r.deadwood && r.deadwood[p.id] != null ? r.deadwood[p.id] : '')),
        ...players.map(p => r.void ? 0 : (r.scores[p.id] || 0))
      ]);
    });
    rows.push([]);
    rows.push(['TOTAL', '', '', '', '', ...players.map(() => ''), ...players.map(p => totalFor(p.id))]);
    const csv = rows.map(row => row.map(csvEscape).join(',')).join('\r\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const stamp = new Date().toISOString().slice(0, 16).replace(/[:T]/g, '-');
    a.href = url;
    a.download = `gin-rummy-${players.map(p => p.name.replace(/[^a-z0-9]+/gi, '')).join('-vs-')}-${stamp}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 2000);
    toast('Exported the game as a CSV file.');
  }
  // ---- legacy/gin-rummy/index.html lines 2328-2328
  const NUM_ONES = { zero: 0, oh: 0, o: 0, one: 1, two: 2, three: 3, four: 4, for: 4, five: 5, six: 6, seven: 7, eight: 8, ate: 8, nine: 9, ten: 10, eleven: 11, twelve: 12, thirteen: 13, fourteen: 14, fifteen: 15, sixteen: 16, seventeen: 17, eighteen: 18, nineteen: 19 };
  // ---- legacy/gin-rummy/index.html lines 2329-2329
  const NUM_TENS = { twenty: 20, thirty: 30, forty: 40, fourty: 40, fifty: 50, sixty: 60, seventy: 70, eighty: 80, ninety: 90 };
  // ---- legacy/gin-rummy/index.html lines 2330-2339
  function wordsToNumber(text) {
    const tokens = text.toLowerCase().replace(/-/g, ' ').split(/\s+/).filter(Boolean);
    let total = 0, found = false;
    for (const t of tokens) {
      if (t === 'hundred') { total = (total || 1) * 100; found = true; continue; }
      if (NUM_TENS.hasOwnProperty(t)) { total += NUM_TENS[t]; found = true; continue; }
      if (NUM_ONES.hasOwnProperty(t)) { total += NUM_ONES[t]; found = true; continue; }
    }
    return found ? total : null;
  }
  // ---- legacy/gin-rummy/index.html lines 2340-2344
  function extractNumber(clause) {
    const m = clause.match(/\d+/);
    if (m) return parseInt(m[0], 10);
    return wordsToNumber(clause);
  }
  // ---- legacy/gin-rummy/index.html lines 2348-2376
  function parseVoiceScores(transcript, players) {
    const clauses = transcript.toLowerCase().split(/,|\band\b|&/).map(s => s.trim()).filter(Boolean);
    const heard = { knockerId: null, knockType: null, deadwood: {} };
    const matches = [];
    for (const clause of clauses) {
      let player = null;
      for (const p of players) {
        if (clause.includes(p.name.toLowerCase())) { if (!player || p.name.length > player.name.length) player = p; }
      }
      if (!player) continue;
      const isGin = /\bgin\b/.test(clause);
      const isKnock = /\bknock/.test(clause);
      if (isGin) {
        heard.knockerId = player.id; heard.knockType = 'gin'; heard.deadwood[player.id] = 0;
        matches.push(`${player.name}: Gin`);
      } else {
        const n = extractNumber(clause);
        if (isKnock) {
          heard.knockerId = player.id; heard.knockType = 'knock';
          if (n != null) heard.deadwood[player.id] = n;
          matches.push(`${player.name}: Knock${n != null ? ' (' + n + ')' : ''}`);
        } else if (n != null) {
          heard.deadwood[player.id] = n;
          matches.push(`${player.name}: ${n}`);
        }
      }
    }
    return { heard, matches };
  }
  return {
    fmtDuration, fitTable, cueState, playCuesFor, cardHtml, backHtml, meldGroupsHtml,
    legacyStatus, legacyDeadwoodText, legacyHandHtml,
    GIN_BONUS, UNDERCUT_BONUS, KNOCK_LABELS, totalFor, computeRoundScores, csvEscape, exportGame,
    NUM_ONES, NUM_TENS, wordsToNumber, extractNumber, parseVoiceScores,
    setState: (s) => { state = s; },
  };
};
// The two rules lists (lines 325-337, lines 527-539), verbatim.
module.exports.RULES_BLOCKS = [
  "      <ul class=\"rules-list\">\n        <li><strong>Goal:</strong> Arrange your 10 cards into melds — sets (3–4 of a kind) or runs (3+ in a row, same suit; Ace is low only).</li>\n        <li><strong>Deadwood:</strong> Unmelded cards. Ace = 1, face cards = 10, others face value. The app arranges your melds for you and shows your deadwood live.</li>\n      <li><strong>Choosing melds:</strong> When a card could serve two melds (5♠5♥5♦ vs 4♠5♠6♠), tap the deadwood readout above your hand to pick which melds you declare. It won't change your score, but it changes what your opponent can lay off if you knock.</li>\n        <li><strong>First turn:</strong> The non-dealer may take the face-up card or pass; then the dealer may. If both pass, the non-dealer draws from the stock.</li>\n        <li><strong>Each turn:</strong> Draw one card (stock or discard pile), then discard one. You may not discard the card you just took from the discard pile.</li>\n        <li><strong>Knock:</strong> After drawing, pick a discard — if your remaining deadwood is 10 or less, the Knock button lights up.</li>\n        <li><strong>Gin:</strong> Knock with 0 deadwood: +25 bonus plus all of your opponent's deadwood. No lay-offs against gin.</li>\n        <li><strong>Lay off:</strong> Against a normal knock, the opponent's deadwood cards that fit your melds are laid off automatically.</li>\n        <li><strong>Undercut:</strong> If the opponent's deadwood is equal to or less than the knocker's, the opponent scores the difference + 25.</li>\n        <li><strong>Void hand:</strong> If only two cards remain in the stock and nobody has knocked, the hand is void and is redealt.</li>\n        <li><strong>Winning:</strong> Points accumulate each hand; the loser of a hand deals the next. First to the target score (default 100) wins.</li>\n      </ul>",
  "    <ul class=\"rules-list\">\n      <li><strong>Goal:</strong> Arrange your 10 cards into melds — sets (3–4 of a kind) or runs (3+ in a row, same suit; Ace is low only).</li>\n      <li><strong>Deadwood:</strong> Unmelded cards. Ace = 1, face cards = 10, others face value. The app arranges your melds for you and shows your deadwood live.</li>\n      <li><strong>Choosing melds:</strong> When a card could serve two melds (5♠5♥5♦ vs 4♠5♠6♠), tap the deadwood readout above your hand to pick which melds you declare. It won't change your score, but it changes what your opponent can lay off if you knock.</li>\n      <li><strong>First turn:</strong> The non-dealer may take the face-up card or pass; then the dealer may. If both pass, the non-dealer draws from the stock.</li>\n      <li><strong>Each turn:</strong> Draw one card (stock or discard pile), then discard one. You may not discard the card you just took from the discard pile.</li>\n      <li><strong>Knock:</strong> After drawing, pick a discard — if your remaining deadwood is 10 or less, the Knock button lights up.</li>\n      <li><strong>Gin:</strong> Knock with 0 deadwood: +25 bonus plus all of your opponent's deadwood. No lay-offs against gin.</li>\n      <li><strong>Lay off:</strong> Against a normal knock, the opponent's deadwood cards that fit your melds are laid off automatically.</li>\n      <li><strong>Undercut:</strong> If the opponent's deadwood is equal to or less than the knocker's, the opponent scores the difference + 25.</li>\n      <li><strong>Void hand:</strong> If only two cards remain in the stock and nobody has knocked, the hand is void and is redealt.</li>\n      <li><strong>Winning:</strong> Points accumulate each hand; the loser of a hand deals the next. First to the target score (default 100) wins.</li>\n    </ul>",
];
