// GENERATED by tools/legacy/extract-gin-engine.ts from games/gin-rummy/index.html; do not edit.
// The GinEngine UMD block, verbatim, with the <script> tag stripped; it loads through its
// module.exports branch. Pinned to the page by test/fixtures/legacy/MANIFEST.json.
/* Gin Rummy engine — pure logic, no DOM. Host-authoritative.
 * Exposed as window.GinEngine in the browser or module.exports in Node. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.GinEngine = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const SUITS = ['S', 'H', 'D', 'C'];
  const SUIT_SYMBOL = { S: '♠', H: '♥', D: '♦', C: '♣' };
  const RANK_LABEL = { 1: 'A', 11: 'J', 12: 'Q', 13: 'K' };
  const KNOCK_LIMIT = 10;
  const GIN_BONUS = 25;
  const UNDERCUT_BONUS = 25;

  function makeCard(r, s) { return { id: rankLabel(r) + s, r, s }; }
  function rankLabel(r) { return RANK_LABEL[r] || String(r); }
  function cardValue(c) { return Math.min(c.r, 10); }
  function sumValue(cards) { return cards.reduce((a, c) => a + cardValue(c), 0); }
  function cardById(cards, id) { return cards.find(c => c.id === id) || null; }
  function without(cards, id) { return cards.filter(c => c.id !== id); }

  function makeDeck() {
    const d = [];
    for (const s of SUITS) for (let r = 1; r <= 13; r++) d.push(makeCard(r, s));
    return d;
  }

  function shuffle(cards, rng) {
    const a = cards.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(rng() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }

  // ---------- Meld detection ----------
  // Returns every possible meld (as arrays of cards) contained in `cards`.
  function allMelds(cards) {
    const melds = [];
    // sets
    const byRank = {};
    for (const c of cards) (byRank[c.r] = byRank[c.r] || []).push(c);
    for (const r in byRank) {
      const g = byRank[r];
      if (g.length >= 3) {
        if (g.length === 4) {
          melds.push(g.slice());
          for (let skip = 0; skip < 4; skip++) melds.push(g.filter((_, i) => i !== skip));
        } else melds.push(g.slice());
      }
    }
    // runs (ace low only)
    const bySuit = {};
    for (const c of cards) (bySuit[c.s] = bySuit[c.s] || []).push(c);
    for (const s in bySuit) {
      const g = bySuit[s].slice().sort((a, b) => a.r - b.r);
      let i = 0;
      while (i < g.length) {
        let j = i;
        while (j + 1 < g.length && g[j + 1].r === g[j].r + 1) j++;
        const len = j - i + 1;
        if (len >= 3) {
          for (let a = i; a <= j; a++) for (let b = a + 2; b <= j; b++) melds.push(g.slice(a, b + 1));
        }
        i = j + 1;
      }
    }
    return melds;
  }

  function isSet(meld) { return meld.length >= 3 && meld.every(c => c.r === meld[0].r); }

  // Memoised bitmask DP over a hand. `excluded` marks cards that are not part of the
  // hand for this query (e.g. the card about to be discarded, or cards laid off).
  // One solver answers every "what if I discard X" question for an 11-card hand.
  function meldSolver(cards) {
    const n = cards.length;
    const melds = allMelds(cards);
    const idx = {}; cards.forEach((c, i) => { idx[c.id] = i; });
    const meldMasks = melds.map(m => m.reduce((mask, c) => mask | (1 << idx[c.id]), 0));
    const byCard = Array.from({ length: n }, () => []);
    meldMasks.forEach((mask, mi) => { for (let i = 0; i < n; i++) if (mask & (1 << i)) byCard[i].push(mi); });
    const values = cards.map(cardValue);
    const FULL = (1 << n) - 1;
    const memo = new Map();
    const choice = new Map();

    function f(used) {
      if (used === FULL) return 0;
      const hit = memo.get(used);
      if (hit !== undefined) return hit;
      let i = 0; while (used & (1 << i)) i++;
      let best = values[i] + f(used | (1 << i));
      let pick = -1;
      for (const mi of byCard[i]) {
        if (meldMasks[mi] & used) continue;
        const v = f(used | meldMasks[mi]);
        if (v < best) { best = v; pick = mi; }
      }
      memo.set(used, best); choice.set(used, pick);
      return best;
    }

    function melding(excluded) {
      excluded = excluded || 0;
      const value = f(excluded);
      const chosen = []; const deadwood = [];
      let used = excluded;
      while (used !== FULL) {
        let i = 0; while (used & (1 << i)) i++;
        const pick = choice.get(used);
        if (pick === -1 || pick === undefined) { deadwood.push(cards[i]); used |= (1 << i); }
        else { chosen.push(melds[pick]); used |= meldMasks[pick]; }
      }
      return { melds: chosen.map(sortMeld), deadwood: sortCards(deadwood), value };
    }

    function maskOf(ids) { return ids.reduce((m, id) => m | (1 << idx[id]), 0); }
    return { melding, maskOf, value: (excluded) => f(excluded || 0) };
  }

  // Best melding: minimise deadwood value. Returns {melds, deadwood, value}.
  function bestMelding(cards) {
    if (!cards.length) return { melds: [], deadwood: [], value: 0 };
    return meldSolver(cards).melding(0);
  }

  // ---------- alternative meld arrangements ----------
  // A hand can often be melded several different ways for the SAME deadwood value
  // (e.g. 5S 5H 5D + 4S 6S — either the set of 5s or the 4-5-6 run; the 5S can only
  // go in one of them). Which melds you DECLARE matters when you knock, because the
  // opponent lays their deadwood off onto your melds. These helpers let the player
  // pick their preferred arrangement among equally-scoring ones.
  function meldSig(melds) {
    return melds.map(m => m.map(c => c.id).slice().sort().join('+')).sort().join('|');
  }
  function isValidMeldGroup(cs) {
    if (!Array.isArray(cs) || cs.length < 3) return false;
    const ranks = cs.map(c => c.r), suits = cs.map(c => c.s);
    if (ranks.every(r => r === ranks[0])) {                 // set: 3-4 of a rank, distinct suits
      return cs.length <= 4 && new Set(suits).size === cs.length;
    }
    if (!suits.every(s => s === suits[0])) return false;    // run: one suit, consecutive ranks
    const sorted = ranks.slice().sort((a, b) => a - b);
    for (let i = 1; i < sorted.length; i++) if (sorted[i] !== sorted[i - 1] + 1) return false;
    return true;
  }
  // Build a melding from explicit groups of card ids. Returns null unless the groups are
  // legal, non-overlapping melds drawn from cards actually present in `cards`.
  function meldingFromGroups(cards, groups) {
    if (!Array.isArray(groups)) return null;
    const byId = {}; cards.forEach(c => { byId[c.id] = c; });
    const used = new Set(); const melds = [];
    for (const g of groups) {
      if (!Array.isArray(g)) return null;
      const cs = [];
      for (const id of g) {
        if (typeof id !== 'string' || !byId[id] || used.has(id)) return null;
        used.add(id); cs.push(byId[id]);
      }
      if (!isValidMeldGroup(cs)) return null;
      melds.push(sortMeld(cs));
    }
    const dead = cards.filter(c => !used.has(c.id));
    return { melds, deadwood: sortCards(dead), value: sumValue(dead) };
  }
  const _altCache = new Map();
  // Every distinct arrangement that achieves the minimum deadwood value.
  function allOptimalMeldings(cards, limit) {
    limit = limit || 12;
    if (!cards.length) return [{ melds: [], deadwood: [], value: 0, sig: '' }];
    const key = cards.map(c => c.id).slice().sort().join(',') + '#' + limit;
    const hit = _altCache.get(key);
    if (hit) return hit;
    const minValue = bestMelding(cards).value;
    const melds = allMelds(cards);
    const n = cards.length;
    const idx = {}; cards.forEach((c, i) => { idx[c.id] = i; });
    const meldMasks = melds.map(m => m.reduce((mask, c) => mask | (1 << idx[c.id]), 0));
    const byCard = Array.from({ length: n }, () => []);
    meldMasks.forEach((mask, mi) => { for (let i = 0; i < n; i++) if (mask & (1 << i)) byCard[i].push(mi); });
    const values = cards.map(cardValue);
    const FULL = (1 << n) - 1;
    const out = []; const seen = new Set(); const chosen = [];
    let nodes = 0;
    function rec(used, dead) {
      if (out.length >= limit || nodes++ > 300000 || dead > minValue) return;
      if (used === FULL) {
        if (dead !== minValue) return;
        const arrangement = chosen.map(mi => sortMeld(melds[mi]));
        const sig = meldSig(arrangement);
        if (seen.has(sig)) return;
        seen.add(sig);
        const covered = chosen.reduce((m, mi) => m | meldMasks[mi], 0);
        out.push({ melds: arrangement, deadwood: sortCards(cards.filter((_, k) => !(covered & (1 << k)))), value: dead, sig });
        return;
      }
      let i = 0; while (used & (1 << i)) i++;
      for (const mi of byCard[i]) {
        if (meldMasks[mi] & used) continue;
        chosen.push(mi); rec(used | meldMasks[mi], dead); chosen.pop();
        if (out.length >= limit) return;
      }
      rec(used | (1 << i), dead + values[i]);
    }
    rec(0, 0);
    if (_altCache.size > 400) _altCache.clear();
    _altCache.set(key, out);
    return out;
  }

  // Given knocker's melds, lay off as many of `cards` as possible (chained). Returns {laidOff:[{card, ontoIndex}], remaining}.
  function maximalLayoff(cards, knockerMelds) {
    const melds = knockerMelds.map(m => m.slice());
    let remaining = cards.slice();
    const laidOff = [];
    let changed = true;
    while (changed) {
      changed = false;
      for (let ci = 0; ci < remaining.length && !changed; ci++) {
        const c = remaining[ci];
        for (let mi = 0; mi < melds.length; mi++) {
          const m = melds[mi];
          let fits = false;
          if (isSet(m)) fits = m.length < 4 && c.r === m[0].r && !m.some(x => x.s === c.s);
          else {
            const ranks = m.map(x => x.r);
            const lo = Math.min(...ranks), hi = Math.max(...ranks);
            fits = c.s === m[0].s && (c.r === lo - 1 || c.r === hi + 1);
          }
          if (fits) {
            m.push(c);
            laidOff.push({ card: c, onto: mi });
            remaining = remaining.filter(x => x.id !== c.id);
            changed = true;
            break;
          }
        }
      }
    }
    return { laidOff, remaining, extendedMelds: melds.map(sortMeld) };
  }

  // Opponent's best response to a knock: choose own melds + layoffs minimising deadwood.
  // Layoff feasibility is monotone (each slot accepts exactly one specific card), so the
  // maximal layoff set L is unique and every feasible layoff set is a subset of L.
  function bestMeldingWithLayoffs(cards, knockerMelds) {
    const L = maximalLayoff(cards, knockerMelds).laidOff.map(x => x.card);
    const solver = meldSolver(cards);
    let best = null;
    const total = 1 << L.length;
    for (let sub = 0; sub < total; sub++) {
      const S = L.filter((_, i) => sub & (1 << i));
      const lo = maximalLayoff(S, knockerMelds);
      if (lo.laidOff.length !== S.length) continue; // not feasible on its own (e.g. 9 without the 8)
      const m = solver.melding(solver.maskOf(S.map(c => c.id)));
      if (!best || m.value < best.value) {
        best = { melds: m.melds, laidOff: lo.laidOff, deadwood: m.deadwood, value: m.value, extendedMelds: lo.extendedMelds };
      }
    }
    return best;
  }

  function sortMeld(m) {
    return isSet(m) ? m.slice().sort((a, b) => SUITS.indexOf(a.s) - SUITS.indexOf(b.s)) : m.slice().sort((a, b) => a.r - b.r);
  }
  function sortCards(cards) {
    return cards.slice().sort((a, b) => (SUITS.indexOf(a.s) - SUITS.indexOf(b.s)) || (a.r - b.r));
  }

  // ---------- Game state ----------
  function createGame(opts) {
    const rng = opts.rng || Math.random;
    const state = {
      players: opts.players.map(p => ({ id: p.id, name: p.name, total: 0 })),
      target: opts.target || 100,
      dealer: opts.dealer != null ? opts.dealer : (rng() < 0.5 ? 0 : 1),
      turn: 0,
      phase: 'roundOver',
      hands: [[], []],
      stock: [],
      discard: [],
      upcardStage: null,
      drawnFromDiscard: null,
      forceStock: false,
      pendingDraw: null,
      meldPref: [null, null],
      lastAction: null,
      handNumber: 0,
      rounds: [],
      result: null,
      ready: [false, false],
      winner: null,
      startedAt: Date.now()
    };
    dealHand(state, rng);
    return state;
  }

  function dealHand(state, rng) {
    const deck = shuffle(makeDeck(), rng || Math.random);
    const nonDealer = 1 - state.dealer;
    const hands = [[], []];
    for (let i = 0; i < 10; i++) { hands[nonDealer].push(deck.pop()); hands[state.dealer].push(deck.pop()); }
    state.hands = hands;
    state.discard = [deck.pop()];
    state.stock = deck;
    state.turn = nonDealer;
    state.phase = 'upcard';
    state.upcardStage = 'nonDealer';
    state.drawnFromDiscard = null;
    state.forceStock = false;
    state.pendingDraw = null;
    state.meldPref = [null, null];
    state.handNumber += 1;
    state.result = null;
    state.ready = [false, false];
    state.lastAction = { text: `${state.players[state.dealer].name} dealt hand ${state.handNumber}. ${state.players[nonDealer].name} may take the upcard or pass.` };
    return state;
  }

  function otherPlayer(i) { return 1 - i; }

  // Returns { ok: true } or { ok: false, error }
  function applyAction(state, pIdx, action, rng) {
    rng = rng || Math.random;
    const me = state.players[pIdx];
    const type = action && action.type;
    const err = (m) => ({ ok: false, error: m });

    // Choosing how to arrange your own melds is a declaration, not a move — it's allowed
    // any time during play, including while waiting for the opponent.
    if (type === 'setMelds') {
      if (state.phase !== 'upcard' && state.phase !== 'draw' && state.phase !== 'discard') return err('You can only rearrange melds during play.');
      if (!state.meldPref) state.meldPref = [null, null];
      const myHand = state.hands[pIdx];
      const m = meldingFromGroups(myHand, action.melds || []);
      if (!m) return err("That meld arrangement doesn't fit your hand.");
      const auto = bestMelding(myHand);
      if (m.value !== auto.value) return err(`That arrangement would leave ${m.value} deadwood instead of ${auto.value}.`);
      state.meldPref[pIdx] = (action.melds || []).map(g => g.slice());
      return { ok: true };
    }

    if (state.phase === 'gameOver') {
      if (type === 'ready') {
        state.ready[pIdx] = true;
        if (state.ready[0] && state.ready[1]) {
          state.players.forEach(p => { p.total = 0; });
          state.rounds = [];
          state.winner = null;
          state.handNumber = 0;
          state.startedAt = Date.now();
          state.dealer = rng() < 0.5 ? 0 : 1;
          dealHand(state, rng);
        }
        return { ok: true };
      }
      return err('The game is over.');
    }

    if (state.phase === 'roundOver') {
      if (type !== 'ready') return err('Waiting for both players to continue.');
      state.ready[pIdx] = true;
      if (state.ready[0] && state.ready[1]) {
        const reached = state.players.map((p, i) => ({ i, t: p.total })).filter(x => x.t >= state.target);
        if (reached.length) {
          reached.sort((a, b) => b.t - a.t);
          state.winner = reached[0].i;
          state.phase = 'gameOver';
          state.ready = [false, false];
          state.lastAction = { text: `${state.players[state.winner].name} wins the game!` };
        } else {
          if (state.result && !state.result.void && state.result.loserIdx != null) state.dealer = state.result.loserIdx;
          dealHand(state, rng);
        }
      }
      return { ok: true };
    }

    if (pIdx !== state.turn) return err("It's not your turn.");
    const hand = state.hands[pIdx];
    const opp = otherPlayer(pIdx);

    if (state.phase === 'upcard') {
      if (type === 'takeUpcard') {
        const c = state.discard.pop();
        state.pendingDraw = { from: 'discard', cardId: c.id, prevPhase: 'upcard', prevUpcardStage: state.upcardStage, prevForceStock: state.forceStock, prevTurn: state.turn };
        hand.push(c);
        state.lastDrawn = { p: pIdx, id: c.id };
        state.drawnFromDiscard = c.id;
        state.phase = 'discard';
        state.upcardStage = null;
        state.lastAction = { text: `${me.name} took the ${pretty(c)} upcard.`, card: c.id, by: pIdx };
        return { ok: true };
      }
      if (type === 'passUpcard') {
        if (state.upcardStage === 'nonDealer') {
          state.upcardStage = 'dealer';
          state.turn = state.dealer;
          state.lastAction = { text: `${me.name} passed on the upcard. ${state.players[state.dealer].name} may take it or pass.`, by: pIdx };
        } else {
          state.upcardStage = null;
          state.phase = 'draw';
          state.turn = otherPlayer(state.dealer);
          state.forceStock = true;
          state.lastAction = { text: `Both passed. ${state.players[state.turn].name} must draw from the stock.`, by: pIdx };
        }
        return { ok: true };
      }
      return err('Take the upcard or pass.');
    }

    if (state.phase === 'draw') {
      if (type === 'drawStock') {
        const c = state.stock.pop();
        state.pendingDraw = { from: 'stock', cardId: c.id, prevPhase: 'draw', prevUpcardStage: state.upcardStage, prevForceStock: state.forceStock, prevTurn: state.turn };
        hand.push(c);
        state.lastDrawn = { p: pIdx, id: c.id };
        state.drawnFromDiscard = null;
        state.forceStock = false;
        state.phase = 'discard';
        state.lastAction = { text: `${me.name} drew from the stock.`, by: pIdx };
        return { ok: true, privateCard: c.id };
      }
      if (type === 'drawDiscard') {
        if (state.forceStock) return err('After both players pass, you must draw from the stock.');
        if (!state.discard.length) return err('The discard pile is empty.');
        const c = state.discard.pop();
        state.pendingDraw = { from: 'discard', cardId: c.id, prevPhase: 'draw', prevUpcardStage: state.upcardStage, prevForceStock: state.forceStock, prevTurn: state.turn };
        hand.push(c);
        state.lastDrawn = { p: pIdx, id: c.id };
        state.drawnFromDiscard = c.id;
        state.phase = 'discard';
        state.lastAction = { text: `${me.name} took the ${pretty(c)} from the discard pile.`, card: c.id, by: pIdx };
        return { ok: true };
      }
      return err('Draw a card from the stock or the discard pile.');
    }

    if (state.phase === 'discard') {
      if (type === 'undoDraw') {
        const pd = state.pendingDraw;
        if (!pd) return err('Nothing to undo.');
        const drawnCard = cardById(hand, pd.cardId);
        if (!drawnCard) return err('Nothing to undo.');
        state.hands[pIdx] = without(hand, drawnCard.id);
        if (pd.from === 'discard') state.discard.push(drawnCard); else state.stock.push(drawnCard);
        state.phase = pd.prevPhase;
        state.upcardStage = pd.prevUpcardStage;
        state.forceStock = pd.prevForceStock;
        state.turn = pd.prevTurn;
        state.drawnFromDiscard = null;
        state.lastDrawn = null;
        state.pendingDraw = null;
        state.lastAction = { text: `${me.name} undid their draw.`, by: pIdx };
        return { ok: true };
      }
      if (type !== 'discard' && type !== 'knock') return err('Discard a card, knock, or undo your draw.');
      const card = cardById(hand, action.cardId);
      if (!card) return err("That card isn't in your hand.");
      if (hand.length !== 11) return err('You must draw before discarding.');
      if (card.id === state.drawnFromDiscard) return err("You can't discard the card you just took from the discard pile.");

      if (type === 'discard') {
        state.hands[pIdx] = without(hand, card.id);
        state.discard.push(card);
        state.drawnFromDiscard = null;
        state.pendingDraw = null;
        state.lastAction = { text: `${me.name} discarded the ${pretty(card)}.`, card: card.id, by: pIdx };
        if (state.stock.length <= 2) {
          finishVoid(state);
        } else {
          state.turn = opp;
          state.phase = 'draw';
        }
        return { ok: true };
      }

      // knock — honour the player's chosen arrangement when it still fits the kept cards
      // and scores the same, since it decides what the opponent can lay off.
      const remaining = without(hand, card.id);
      const autoMine = bestMelding(remaining);
      const prefGroups = state.meldPref && state.meldPref[pIdx];
      const prefMine = prefGroups ? meldingFromGroups(remaining, prefGroups) : null;
      const mine = (prefMine && prefMine.value === autoMine.value) ? prefMine : autoMine;
      if (mine.value > KNOCK_LIMIT) return err(`You need ${KNOCK_LIMIT} or fewer deadwood points to knock (you'd have ${mine.value}).`);
      state.hands[pIdx] = remaining;
      state.discard.push(card);
      state.drawnFromDiscard = null;
      state.pendingDraw = null;
      const gin = mine.value === 0;
      const oppHand = state.hands[opp];
      const theirs = gin ? Object.assign({ laidOff: [], extendedMelds: mine.melds }, bestMelding(oppHand)) : bestMeldingWithLayoffs(oppHand, mine.melds);

      const scores = [0, 0];
      let outcome;
      if (gin) {
        scores[pIdx] = GIN_BONUS + theirs.value;
        outcome = 'gin';
      } else if (theirs.value <= mine.value) {
        scores[opp] = (mine.value - theirs.value) + UNDERCUT_BONUS;
        outcome = 'undercut';
      } else {
        scores[pIdx] = theirs.value - mine.value;
        outcome = 'knock';
      }
      state.players[0].total += scores[0];
      state.players[1].total += scores[1];
      const scorerIdx = scores[pIdx] > 0 ? pIdx : opp;
      const loserIdx = otherPlayer(scorerIdx);
      const ts = Date.now();
      state.result = {
        void: false,
        knockerIdx: pIdx,
        outcome,
        knockCard: card.id,
        knocker: { melds: mine.melds, deadwood: mine.deadwood, value: mine.value },
        opponent: { melds: theirs.melds, laidOff: theirs.laidOff || [], deadwood: theirs.deadwood, value: theirs.value, extendedMelds: theirs.extendedMelds || mine.melds },
        scores, scorerIdx, loserIdx, ts,
        totals: [state.players[0].total, state.players[1].total]
      };
      state.rounds.push({
        handNumber: state.handNumber, ts,
        knockerIdx: pIdx, outcome,
        deadwood: { [state.players[pIdx].id]: mine.value, [state.players[opp].id]: theirs.value },
        scores: { [state.players[0].id]: scores[0], [state.players[1].id]: scores[1] }
      });
      state.phase = 'roundOver';
      state.ready = [false, false];
      state.lastAction = { text: outcome === 'gin' ? `${me.name} went GIN!` : outcome === 'undercut' ? `${me.name} knocked but was undercut by ${state.players[opp].name}!` : `${me.name} knocked with ${mine.value}.`, by: pIdx };
      return { ok: true };
    }

    return err('Unknown phase.');
  }

  function finishVoid(state) {
    state.result = { void: true, ts: Date.now(), totals: [state.players[0].total, state.players[1].total] };
    state.rounds.push({ handNumber: state.handNumber, ts: Date.now(), void: true, scores: { [state.players[0].id]: 0, [state.players[1].id]: 0 } });
    state.phase = 'roundOver';
    state.ready = [false, false];
    state.lastAction = { text: 'Only two cards left in the stock — the hand is void. Same dealer redeals.' };
  }

  function pretty(c) { return rankLabel(c.r) + SUIT_SYMBOL[c.s]; }

  // ---------- Redacted per-player view ----------
  function viewFor(state, pIdx) {
    const opp = otherPlayer(pIdx);
    const hand = state.hands[pIdx];
    const solver = hand.length ? meldSolver(hand) : null;
    const autoBest = solver ? solver.melding(0) : { melds: [], deadwood: [], value: 0 };
    // Honour the player's chosen arrangement while it still fits and scores the same.
    const prefGroups = state.meldPref && state.meldPref[pIdx];
    const prefMelding = (prefGroups && hand.length) ? meldingFromGroups(hand, prefGroups) : null;
    const melding = (prefMelding && prefMelding.value === autoBest.value) ? prefMelding : autoBest;
    const inPlay = state.phase === 'upcard' || state.phase === 'draw' || state.phase === 'discard';
    let meldOptions = [];
    if (inPlay && hand.length) {
      meldOptions = allOptimalMeldings(hand, 12).slice();
      const autoSig = meldSig(autoBest.melds);
      if (!meldOptions.some(o => o.sig === autoSig)) {
        meldOptions.unshift({ melds: autoBest.melds, deadwood: autoBest.deadwood, value: autoBest.value, sig: autoSig });
      }
    }
    let discardOptions = null;
    if (state.phase === 'discard' && state.turn === pIdx && hand.length === 11) {
      discardOptions = {};
      for (const c of hand) {
        if (c.id === state.drawnFromDiscard) { discardOptions[c.id] = { locked: true }; continue; }
        const v = solver.value(solver.maskOf([c.id]));
        discardOptions[c.id] = { deadwood: v, canKnock: v <= KNOCK_LIMIT, isGin: v === 0 };
      }
    }
    const view = {
      me: { idx: pIdx, id: state.players[pIdx].id, name: state.players[pIdx].name, total: state.players[pIdx].total, hand: hand, melds: melding.melds, deadwood: melding.deadwood, deadwoodValue: melding.value },
      opp: { idx: opp, id: state.players[opp].id, name: state.players[opp].name, total: state.players[opp].total, cardCount: state.hands[opp].length },
      players: state.players.map(p => ({ id: p.id, name: p.name, total: p.total })),
      phase: state.phase,
      turn: state.turn,
      isMyTurn: state.turn === pIdx,
      dealer: state.dealer,
      upcardStage: state.upcardStage,
      stockCount: state.stock.length,
      discardTop: state.discard.length ? state.discard[state.discard.length - 1] : null,
      discardCount: state.discard.length,
      drawnFromDiscard: state.drawnFromDiscard,
      forceStock: state.forceStock,
      lastAction: state.lastAction,
      handNumber: state.handNumber,
      target: state.target,
      rounds: state.rounds,
      result: state.result,
      ready: state.ready,
      winner: state.winner,
      startedAt: state.startedAt,
      discardOptions,
      lastDrawnId: (state.lastDrawn && state.lastDrawn.p === pIdx && hand.some(c => c.id === state.lastDrawn.id)) ? state.lastDrawn.id : null,
      canUndo: !!(state.phase === 'discard' && state.turn === pIdx && state.pendingDraw),
      meldOptions,
      activeMeldSig: meldSig(melding.melds),
      knockLimit: KNOCK_LIMIT
    };
    return view;
  }

  // Legal action list for a view (used by UI + tests)
  function legalActions(view) {
    const acts = [];
    if (view.phase === 'roundOver' || view.phase === 'gameOver') { if (!view.ready[view.me.idx]) acts.push({ type: 'ready' }); return acts; }
    if (!view.isMyTurn) return acts;
    if (view.phase === 'upcard') return [{ type: 'takeUpcard' }, { type: 'passUpcard' }];
    if (view.phase === 'draw') {
      acts.push({ type: 'drawStock' });
      if (!view.forceStock && view.discardTop) acts.push({ type: 'drawDiscard' });
      return acts;
    }
    if (view.phase === 'discard') {
      if (view.canUndo) acts.push({ type: 'undoDraw' });
      for (const c of view.me.hand) {
        const o = view.discardOptions[c.id];
        if (o.locked) continue;
        acts.push({ type: 'discard', cardId: c.id });
        if (o.canKnock) acts.push({ type: 'knock', cardId: c.id });
      }
    }
    return acts;
  }

  return {
    SUITS, SUIT_SYMBOL, KNOCK_LIMIT, GIN_BONUS, UNDERCUT_BONUS,
    makeDeck, shuffle, makeCard, cardValue, sumValue, rankLabel, pretty,
    allMelds, bestMelding, bestMeldingWithLayoffs, maximalLayoff, isSet, sortCards,
    allOptimalMeldings, meldingFromGroups, meldSig,
    createGame, dealHand, applyAction, viewFor, legalActions
  };
});
