// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 610-663
// (bundle section "// src/net/client.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { decodeServerMessage } from './protocol.js';

  var CONNECT_TIMEOUT_MS = 12e3;
  var ClientSession = class {
    kind = "client";
    transport;
    events;
    rememberToken;
    conn = null;
    token;
    constructor(deps, opts) {
      this.transport = deps.transport;
      this.events = deps.events;
      this.rememberToken = deps.rememberToken;
      this.token = opts.savedToken;
      const timeout = deps.clock.setTimeout(() => {
        if (!this.conn) this.events.onClosed("Could not reach the host. Make sure their tab is still open, then try again \u2014 and if you're on a different network than the host, a relay (TURN) must be configured.");
      }, CONNECT_TIMEOUT_MS);
      this.transport.onOpen((c) => {
        deps.clock.clearTimeout(timeout);
        this.conn = c;
        c.onMessage((raw) => this.receive(raw));
        c.onClose(() => this.events.onClosed("The host closed the table."));
        this.events.onReady();
        this.send({ t: "hello", role: opts.role, name: opts.name, token: this.token });
      });
      this.transport.onError((kind) => {
        if (kind === "peer-unavailable") this.events.onClosed("No lobby found with that code. Check the code with your host.");
        else if (!this.conn) this.events.onClosed(`Connection problem: ${kind}`);
      });
      this.transport.onInfo?.((m) => this.events.onInfo(m));
    }
    act(action) {
      this.send({ t: "act", action });
    }
    close() {
      this.conn?.close();
      this.transport.close();
    }
    send(msg) {
      if (this.conn?.open) this.conn.send(msg);
    }
    receive(raw) {
      const decoded = decodeServerMessage(raw);
      if (!decoded.ok) return;
      const msg = decoded.value;
      if (msg.t === "state") {
        if (msg.you.token && msg.you.token !== this.token) {
          this.token = msg.you.token;
          this.rememberToken(msg.you.token);
        }
        return this.events.onState(msg.state, { seat: msg.you.seat, role: msg.you.role });
      }
      msg.t === "error" ? this.events.onError(msg.message) : this.events.onInfo(msg.message);
    }
  };

export { CONNECT_TIMEOUT_MS, ClientSession };
