// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 1892-2108
// (bundle section "// src/net/host.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { expect } from '../domain/result.js';
import { decodeClientMessage } from './protocol.js';
import {
  HOST, apply, bySeat, newGame, scheduleAutoNext, stampLog, startGame,
} from '../domain/game.js';
import { redactFor } from '../domain/publicState.js';
import { RANDOM_STRATEGY, describeProfile, profileFor } from '../bots/registry.js';
import { decide, emptyMemories } from '../bots/brain.js';
import {
  findSeat, hostSitsDown, hostStandsUp, makeBot, makeHuman, renameBot, seatPlayer, setBotProfile,
  setConnected, unseatPlayer, withSpectators,
} from '../domain/lobby.js';

  var AUTO_NEXT_MS = 7e3;
  var HostSession = class {
    kind = "host";
    transport;
    events;
    clock;
    rng;
    newId;
    hostId;
    guests = /* @__PURE__ */ new Map();
    tokens = /* @__PURE__ */ new Map();
    /** Players who act from this device (the host, plus pass-the-phone locals). */
    localIds;
    state;
    botMemories = emptyMemories;
    botTimer = null;
    nextTimer = null;
    closed = false;
    constructor(deps, opts) {
      this.transport = deps.transport;
      this.events = deps.events;
      this.clock = deps.clock;
      this.rng = deps.rng;
      this.newId = deps.newId;
      this.hostId = deps.newId();
      const base = newGame(opts.code, opts.lives);
      const seated = opts.watch ? { ...base, hostSeat: null } : expect(seatPlayer(base, makeHuman(this.hostId, opts.hostName, opts.lives)), "seat host");
      const locals = (opts.locals ?? []).map((name) => ({ id: deps.newId(), name }));
      const withLocals = locals.reduce((s, l) => expect(seatPlayer(s, makeHuman(l.id, l.name, opts.lives)), "seat local"), seated);
      this.localIds = /* @__PURE__ */ new Set([this.hostId, ...locals.map((l) => l.id)]);
      const withBots = Array.from({ length: opts.bots }).reduce((s) => this.addBotTo(s, opts.botChoice ?? RANDOM_STRATEGY), withLocals);
      this.state = opts.autostart ? expect(startGame(withBots, this.rng), "autostart") : withBots;
      this.transport.onOpen(() => {
        this.events.onReady();
        this.commit(this.state);
      });
      this.transport.onError((kind) => this.events.onError(`Connection problem: ${kind}`));
      this.transport.onConnection((c) => this.accept(c));
      this.transport.onInfo?.((m) => this.events.onInfo ? this.events.onInfo(m) : this.events.onError(m));
    }
    /* ---------- public API used by the controller ---------- */
    get snapshot() {
      return this.state;
    }
    /** True when several humans share this device (pass the phone). */
    get local() {
      return this.localIds.size > 1;
    }
    /** The seat whose turn it is, if that player acts from this device — the one holding the phone. */
    localHolder() {
      const r = this.state.round;
      if (this.state.phase !== "playing" || !r || this.state.reveal) return null;
      const p2 = this.state.players[r.holder];
      return p2 && this.localIds.has(p2.id) ? r.holder : null;
    }
    act(action) {
      const holder = this.localHolder();
      const actor = holder !== null ? bySeat(holder) : this.state.hostSeat === null ? HOST : bySeat(this.state.hostSeat);
      const r = apply(this.state, actor, action, this.rng);
      r.ok ? this.commit(r.value) : this.events.onError(r.error);
    }
    addBot() {
      const next = this.addBotTo(this.state);
      next === this.state ? this.events.onError("Table is full.") : this.commit(next);
    }
    removeBot(at) {
      const p2 = this.state.players[at];
      if (!p2?.bot || this.state.phase !== "lobby") return;
      this.commit(unseatPlayer(this.state, p2.id));
    }
    renameBot(at, name) {
      const p2 = this.state.players[at];
      if (!p2?.bot) return;
      const next = renameBot(this.state, p2.id, name);
      if (next !== this.state) this.commit(next);
    }
    /** `choice` is a strategy id or "random". */
    setBot(at, choice) {
      const p2 = this.state.players[at];
      if (!p2?.bot) return;
      const profile = profileFor(choice, this.rng);
      const next = setBotProfile(this.state, p2.id, profile, describeProfile(profile));
      if (next !== this.state) this.commit(next);
    }
    hostWatches(watching, hostName) {
      if (this.state.phase !== "lobby") return;
      this.commit(watching ? hostStandsUp(this.state) : hostSitsDown(this.state, makeHuman(this.hostId, hostName, this.state.lives)));
    }
    close() {
      this.closed = true;
      this.clearTimers();
      this.guests.forEach((_, c) => c.close());
      this.transport.close();
    }
    /* ---------- internals ---------- */
    addBotTo(s, choice = RANDOM_STRATEGY) {
      const r = seatPlayer(s, makeBot(s, this.newId(), profileFor(choice, this.rng)));
      return r.ok ? r.value : s;
    }
    viewerFor(g) {
      const at = g.playerId ? findSeat(this.state, g.playerId) : null;
      return g.role === "player" && at !== null ? { kind: "seat", seat: at } : { kind: "spectator" };
    }
    /** This device sees the table as whoever holds the phone; otherwise as the host. */
    mySeat() {
      const holder = this.localHolder();
      return holder !== null && this.local ? holder : this.state.hostSeat;
    }
    myViewer() {
      const seat2 = this.mySeat();
      return seat2 === null ? { kind: "spectator" } : { kind: "seat", seat: seat2 };
    }
    me() {
      const seat2 = this.mySeat();
      return { seat: seat2, role: seat2 === null ? "spectator" : "player" };
    }
    send(c, msg) {
      if (c.open) c.send(msg);
    }
    broadcast() {
      this.guests.forEach((g, c) => {
        const viewer = this.viewerFor(g);
        this.send(c, { t: "state", state: redactFor(this.state, viewer), you: { seat: viewer.kind === "seat" ? viewer.seat : null, token: g.token, role: g.role } });
      });
      this.events.onState(redactFor(this.state, this.myViewer()), this.me());
    }
    commit(next) {
      if (this.closed) return;
      this.state = stampLog(next, this.clock.now());
      this.broadcast();
      this.schedule();
    }
    accept(c) {
      c.onMessage((raw) => {
        const decoded = decodeClientMessage(raw);
        if (!decoded.ok) return this.send(c, { t: "error", message: decoded.error });
        const msg = decoded.value;
        if (msg.t === "hello") return this.greet(c, msg.role, msg.name, msg.token);
        const g = this.guests.get(c);
        if (!g?.playerId) return this.send(c, { t: "error", message: "Spectators cannot act." });
        const at = findSeat(this.state, g.playerId);
        if (at === null) return;
        const r = apply(this.state, bySeat(at), msg.action, this.rng);
        r.ok ? this.commit(r.value) : this.send(c, { t: "error", message: r.error });
      });
      c.onClose(() => this.farewell(c));
    }
    greet(c, role, name, token) {
      const returning = role === "player" && token ? this.tokens.get(token) ?? null : null;
      if (returning && findSeat(this.state, returning) !== null) {
        this.guests.set(c, { role: "player", playerId: returning, token });
        return this.commit(setConnected(this.state, returning, true, name ?? void 0));
      }
      if (role === "player") {
        const id = this.newId();
        const seated = seatPlayer(this.state, makeHuman(id, name ?? "Player", this.state.lives));
        if (seated.ok) {
          const fresh = this.newId();
          this.tokens.set(fresh, id);
          this.guests.set(c, { role: "player", playerId: id, token: fresh });
          return this.commit(seated.value);
        }
        this.send(c, { t: "info", message: `${seated.error} You're watching as a spectator.` });
      }
      this.guests.set(c, { role: "spectator", playerId: null, token: null });
      this.commit(withSpectators(this.state, 1));
    }
    farewell(c) {
      const g = this.guests.get(c);
      if (!g) return;
      this.guests.delete(c);
      if (g.role === "spectator") return this.commit(withSpectators(this.state, -1));
      if (!g.playerId) return;
      this.commit(this.state.phase === "lobby" ? unseatPlayer(this.state, g.playerId) : setConnected(this.state, g.playerId, false));
    }
    clearTimers() {
      if (this.botTimer !== null) this.clock.clearTimeout(this.botTimer);
      if (this.nextTimer !== null) this.clock.clearTimeout(this.nextTimer);
      this.botTimer = this.nextTimer = null;
    }
    /** After every commit: start the round timer if a reveal is showing, else queue the next bot step. */
    schedule() {
      const s = this.state;
      if (this.botTimer !== null) {
        this.clock.clearTimeout(this.botTimer);
        this.botTimer = null;
      }
      if (s.phase === "playing" && s.reveal) {
        if (this.nextTimer !== null) return;
        this.nextTimer = this.clock.setTimeout(() => {
          this.nextTimer = null;
          this.autoNext();
        }, AUTO_NEXT_MS);
        this.state = scheduleAutoNext(s, this.clock.now() + AUTO_NEXT_MS);
        this.broadcast();
        return;
      }
      if (this.nextTimer !== null) {
        this.clock.clearTimeout(this.nextTimer);
        this.nextTimer = null;
      }
      const decision = decide(s, this.botMemories, this.rng);
      const holder = s.round?.holder;
      if (!decision || holder === void 0) return;
      this.botMemories = decision.memories;
      this.botTimer = this.clock.setTimeout(() => {
        this.botTimer = null;
        const r = apply(this.state, bySeat(holder), decision.step.action, this.rng);
        if (r.ok) this.commit(r.value);
      }, decision.step.delay);
    }
    autoNext() {
      if (!this.state.reveal || this.state.phase !== "playing") return;
      const r = apply(this.state, HOST, { type: "next" }, this.rng);
      if (r.ok) this.commit(r.value);
    }
  };

export { AUTO_NEXT_MS, HostSession };
