// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 2111-2212
// (bundle section "// src/net/peerjs.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

  var peerCtor = () => {
    const ctor = globalThis.Peer;
    if (!ctor) throw new Error("PeerJS failed to load.");
    return ctor;
  };
  var peerIdFor = (code) => `fidice-${code.toLowerCase()}`;
  var wrap = (c) => ({
    get open() {
      return c.open;
    },
    send: (p2) => c.send(p2),
    onMessage: (fn) => c.on("data", fn),
    onClose: (fn) => c.on("close", fn),
    close: () => c.close()
  });
  var PATH_PROBE_MS = 3000;
  var NO_RELAY_INFO = "No relay configured \u2014 players must be on the same network to join.";
  /**
   * A Peer whose ICE servers (STUN/TURN) come from shared/ice.js. The Peer exists only once
   * HyperIce.load() resolves, so listeners registered before then are queued and replayed.
   * Without shared/ice.js the Peer is created immediately with PeerJS defaults, as before.
   */
  var deferredPeer = (id) => {
    const ice = globalThis.HyperIce;
    // Test hook (docs/ARCHITECTURE.md "Documented test hooks"): ?peer=host:port aims PeerJS at a local
    // PeerServer instead of 0.peerjs.com. Without the param the options are exactly what they were.
    const m = /^([^:/]+):(\d+)$/.exec(new URLSearchParams(globalThis.location?.search ?? "").get("peer") ?? "");
    const withPeerOverride = (o) => m ? { ...o, host: m[1], port: Number(m[2]), path: "/", secure: false } : o;
    let peer = null;
    let iceResult = null;
    let closed = false;
    const queued = [];
    const errorFns = [];
    const ready = (fn) => peer ? fn(peer, iceResult) : queued.push(fn);
    const create = (res) => {
      if (closed) return;
      iceResult = res;
      try {
        peer = new (peerCtor())(id, withPeerOverride(res ? { debug: 1, config: ice.peerConfig(res) } : { debug: 1 }));
      } catch (e) {
        errorFns.forEach((fn) => fn(e instanceof Error ? e.message : String(e)));
        return;
      }
      queued.splice(0).forEach((fn) => fn(peer, iceResult));
    };
    if (ice) ice.load().then(create, () => create(null));
    else peer = new (peerCtor())(id, withPeerOverride({ debug: 1 }));
    return {
      ready,
      onError: (fn) => {
        errorFns.push(fn);
        ready((p2) => p2.on("error", (e) => fn(e.type ?? "unknown")));
      },
      close: () => {
        closed = true;
        peer?.destroy();
      }
    };
  };
  /**
   * A while after the data channel opens, say so if it runs through a TURN relay. Fires after
   * TOAST_MS so it never replaces an info toast the host sends in reply to hello; a direct path
   * is the ordinary case and stays silent.
   */
  var describePath = (c, fn) => {
    const ice = globalThis.HyperIce;
    if (!ice) return;
    setTimeout(() => {
      if (!c.open) return;
      ice.describe(c.peerConnection).then((d) => {
        if (d.path === "relay") fn("Connected via relay");
      });
    }, PATH_PROBE_MS);
  };
  var hostTransport = (code) => {
    const p2 = deferredPeer(peerIdFor(code));
    return {
      onOpen: (fn) => p2.ready((peer) => peer.on("open", () => fn())),
      onError: p2.onError,
      onConnection: (fn) => p2.ready((peer) => peer.on("connection", (c) => fn(wrap(c)))),
      onInfo: (fn) => p2.ready((peer, res) => {
        if (res && !res.hasTurn) peer.on("open", () => fn(NO_RELAY_INFO));
      }),
      close: p2.close
    };
  };
  var clientTransport = (code) => {
    const p2 = deferredPeer(void 0);
    const infoFns = [];
    return {
      onOpen: (fn) => p2.ready((peer) => peer.on("open", () => {
        const c = peer.connect(peerIdFor(code), { reliable: true });
        c.on("open", () => {
          fn(wrap(c));
          describePath(c, (m) => infoFns.forEach((g) => g(m)));
        });
      })),
      onError: p2.onError,
      onInfo: (fn) => infoFns.push(fn),
      close: p2.close
    };
  };

export {
  peerCtor, peerIdFor, wrap, PATH_PROBE_MS, NO_RELAY_INFO, deferredPeer, describePath, hostTransport,
  clientTransport,
};
