// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 559-607
// (bundle section "// src/net/protocol.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

import { isRank } from '../domain/hands.js';
import { err, ok } from '../domain/result.js';

  var isRecord = (x) => typeof x === "object" && x !== null;
  var isRole = (x) => x === "player" || x === "spectator";
  var isIndexList = (x) => Array.isArray(x) && x.every((n) => Number.isInteger(n) && n >= 0 && n < 5);
  var decodeAction = (x) => {
    if (!isRecord(x) || typeof x["type"] !== "string") return err("Action must have a type.");
    switch (x["type"]) {
      case "start":
      case "next":
      case "peek":
      case "call":
      case "finish":
        return ok({ type: x["type"] });
      case "pull":
        return Number.isInteger(x["die"]) && x["die"] >= 0 && x["die"] < 5 ? ok({ type: "pull", die: x["die"] }) : err("pull needs a die index 0\u20134.");
      case "roll":
        return typeof x["cup"] === "boolean" && isIndexList(x["table"]) && (x["intoCup"] === void 0 || isIndexList(x["intoCup"])) ? ok({ type: "roll", cup: x["cup"], table: x["table"], intoCup: x["intoCup"] ?? [] }) : err("roll needs cup:boolean, table:number[] and optionally intoCup:number[].");
      case "bid":
        return isRank(x["rank"]) ? ok({ type: "bid", rank: x["rank"] }) : err("bid needs a rank 0\u2013251.");
      default:
        return err(`Unknown action type: ${String(x["type"])}`);
    }
  };
  var decodeClientMessage = (x) => {
    if (!isRecord(x)) return err("Message must be an object.");
    if (x["t"] === "hello") {
      if (!isRole(x["role"])) return err("hello needs a role.");
      const name = typeof x["name"] === "string" ? x["name"].slice(0, 16) : null;
      const token = typeof x["token"] === "string" ? x["token"].slice(0, 64) : null;
      return ok({ t: "hello", role: x["role"], name, token });
    }
    if (x["t"] === "act") {
      const action = decodeAction(x["action"]);
      return action.ok ? ok({ t: "act", action: action.value }) : action;
    }
    return err(`Unknown client message: ${String(x["t"])}`);
  };
  var decodeServerMessage = (x) => {
    if (!isRecord(x)) return err("Message must be an object.");
    if (x["t"] === "state" && isRecord(x["state"]) && isRecord(x["you"]) && isRole(x["you"]["role"])) {
      const you = x["you"];
      return ok({
        t: "state",
        state: x["state"],
        you: { seat: typeof you["seat"] === "number" ? you["seat"] : null, token: typeof you["token"] === "string" ? you["token"] : null, role: you["role"] }
      });
    }
    if ((x["t"] === "error" || x["t"] === "info") && typeof x["message"] === "string") return ok({ t: x["t"], message: x["message"] });
    return err(`Unknown server message: ${String(x["t"])}`);
  };

export { isRecord, isRole, isIndexList, decodeAction, decodeClientMessage, decodeServerMessage };
