// GENERATED by tools/legacy/debundle-fidice.ts from legacy/fidice/index.html lines 2215-2219
// (bundle section "// src/net/session.ts"): the body is verbatim, indentation included; the imports
// and exports were recovered by scope analysis. Do not edit: `npm run debundle:fidice` regenerates
// it and test/tools/debundle-fidice.test.ts checks it (docs/MIGRATION.md step 6; step 8 types it).

  var realClock = {
    now: () => Date.now(),
    setTimeout: (fn, ms) => Number(setTimeout(fn, ms)),
    clearTimeout: (id) => clearTimeout(id)
  };

export { realClock };
